### ISSUE TITLE
Running example code, many problems

### ISSUE THREAD

**Issue by bosung90** [computerjazz/react-native-draggable-flatlist#10]
I was very excited about your library and thank you for putting so much time and effort into making and sharing your code.

However, I find it hugely disappointing as it simply does not work very well.
Take a look, releasing items too early will cause it to not be dropped, sometimes re-ordered items cause them to render only white, scrolling while dragging is really laggy, and lastly the offset seems very off.

![test](https://user-images.githubusercontent.com/1477531/43501511-c6fcd24e-950a-11e8-817e-f5d45eef0111.gif)

**Comment by computerjazz** [comment]
What are your repro steps? Are you seeing this behavior on a device or just in an emulator? Remote debug mode on or off?

> I find it hugely disappointing

😞

**Comment by bosung90** [comment]
Hi @computerjazz 
I am running on a Galaxy S2 tablet (SM-T710) running on debug.
I also tried it on release mode as well and because it is not necessarily a JS lag very similar problem occurs.

I am not running on a simulator. I am running remote debug mode on, but I found same behaviour rather I have it on or not.

Sorry for some strong words!

**Comment by lachtos** [comment]
I had the same problems. Sometimes the items would just disappear (they are still in their place, but rendered empty). Sometimes the item would be rendered weird, almost transparent, and left in that state.

**Comment by computerjazz** [comment]
I've seen the transparent and semi-transpaent item happen sporadically and can't figure out when or why it happens. I could use some help tracking it down.

**Comment by computerjazz** [comment]
please try v2 and reopen an issue if still broken
