### ISSUE TITLE
`createAnimatedComponent` does not support stateless functional components; use a class component instead.

### ISSUE THREAD

**Issue by joennlae** [computerjazz/react-native-draggable-flatlist#100]
First of all thanks for your effort for the v2. @computerjazz 

When I tried to implement the new version into my current project. I got this error:

```
`createAnimatedComponent` does not support stateless functional components; use a class component instead.
```

This is because of the following line:

https://github.com/computerjazz/react-native-draggable-flatlist/blob/39d0788d47fb67704cc0e3f193384dd0dc223c9e/index.tsx#L23

Related Issue:
https://github.com/facebook/react-native/issues/22066

**This is fixed by updating the react-native-gesture-handler.** 
--> If someone else has the same problem

**Comment by joennlae** [comment]
FIX: UPDATE  react-native-gesture-handler.

**Comment by behealy** [comment]
@joennlae I'm seeing this issue myself. What version of react-native-gesture-handler did you update to? What about your react-native version? I'm currently working with react-native 0.59.5, so it doesn't look like any react-native-gesture-handler version above 1.4.0 is going to work for me.

**Comment by sathea** [comment]
@joennlae I am facing the same issue. I am using react-native version 0.59.4. 
@behealy Did you find a solution?

**Comment by 1Jesper1** [comment]
@sathea 
`react-native link react-native-gesture-handler` and `react-native link react-native-reanimated`
Also `npm start -- --reset-cache` is useful to clear cache.

I managed to get it working with:
"react-native-draggable-flatlist": "2.6.2",
"react-native-gesture-handler": "1.10.3",
"react-native-reanimated": "1.13.1",
"react-native": "0.59.10",
