### ISSUE TITLE
Android: No Dragging, Item Jumps to Top (RN 0.61.5)

### ISSUE THREAD

**Issue by chriszwickerocteris** [computerjazz/react-native-draggable-flatlist#103]
See video: 
![Screen-Recording-2019-12-18-at-13 48 44](https://user-images.githubusercontent.com/42444344/71088352-7b92f780-219e-11ea-8018-774242c6ea5b.gif)

## Repro

* `npx react-native init XXX --template react-native-template-typescript`
* Install peer dependencies
* Replace content of App.tsx with example code from readme
* Run on Android

## Package: Dependencies

  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-draggable-flatlist": "^2.0.10",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-reanimated": "^1.4.0"
  },

**Comment by DenisSokoloff** [comment]
Same issue

**Comment by computerjazz** [comment]
Have you followed the extra setup instructions for rngh in MainActivity? It's not 100% autolinked... https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html

**Comment by 5ur3** [comment]
Same issue here

**Comment by 5ur3** [comment]
I had the same issue, but following guide on proper installing react-native-gesture-handler mentioned by computerjazz solved this for me. https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html

**Comment by computerjazz** [comment]
@chriszwickerocteris did you try the above solution? Can we close this?

**Comment by chriszwickerocteris** [comment]
Indeed, that solves it, thanks - and sorry, hadn't had the time to review before!

I would suggest documenting this in the installation steps section of the README, though. In times of autolinking, I may not be the only one not checking peer dependencies' docs.

**Comment by Rega-Team** [comment]
@computerjazz hi I see this behaviour when the component is presented inside Modal. Once it is presented in regular view everything works as expected so I guess it's not installation issue.
Is there any known issue related to Modal ? I didn't find anything

**Comment by tamirla** [comment]
@computerjazz hi I see this behaviour when the component is presented inside Modal. Once it is presented in regular view everything works as expected so I guess it's not installation issue.
Is there any known issue related to Modal ? I didn't find anything

**Comment by Shedav** [comment]
> @computerjazz hi I see this behaviour when the component is presented inside Modal. Once it is presented in regular view everything works as expected so I guess it's not installation issue.
> Is there any known issue related to Modal ? I didn't find anything
> 
> anyway, for now my workaround is to simulate Modal behaviour using regular view.

the same

**Comment by juanjsebgarcia** [comment]
I can also confirm it does not work as expected inside a `Modal`

**Comment by prathammehta** [comment]
Hey guys, I've found the solution to getting it to work in side a modal. Just wrap the Component you want to use as the modal inside `gestureHandlerRootHOC`.
Example:

```
import {gestureHandlerRootHOC} from 'react-native-gesture-handler';

const MyModalComponent = (props) => {
    return (<View> .... </View>)
}

export default gestureHandlerRootHOC(MyModalComponent)
```

This got it working like a charm for me. :)
