### ISSUE TITLE
index is undefined

### ISSUE THREAD

**Issue by vikramkh** [computerjazz/react-native-draggable-flatlist#104]
Anyone have a problem, when after dragging and dropping, the index passed into render item is undefined?

Code in my componentLists folder:
```
export cost DraggableList = props => {
return (
 <Fragment>
     <DraggableFlatList
          data={props.data}
          renderItem={props.renderItem}
          keyExtractor={(item, index) =>  `draggable-item-${item.id}-${item.status}`}
          contentContainerStyle={{flexGrow: 1}}
          contentInset = {props.contentInset}
          onDragEnd={({ data }) => props.onDragEnd({data})}
          initialNumToRender={props.initialNumToRender || 20}
          onRefresh={props.onRefresh}
          refreshing={props.refreshing}
          style={[{backgroundColor: 'silver'}, props.listStyle]}
          extraData={props.data}
        />
    </Fragment>
)
}
```
Implementation:

```
<DraggableList
          listStyle={{backgroundColor: 'white'}}
          contentInset={{top: 0, left: 0, bottom: 70, right: 0}}
          data={data}
          renderItem={({item, index, drag, isActive}) => this.renderItem({item ,index, drag, isActive})}
          onDragEnd={({data})=> this.onDragEnd({data})}
        />

```

index is undefined

**Comment by Soul244** [comment]
I was struggling with the same problem. When i research it, i found this solution:

After drag, indexes become undefined.
![index-error-01](https://user-images.githubusercontent.com/20193416/71723992-b2743900-2e3f-11ea-8fcd-45390d7ed2b0.PNG)

But when you wait for a moment, indexes become normal:

![index-error-02](https://user-images.githubusercontent.com/20193416/71724094-0121d300-2e40-11ea-9866-2955ba86d835.PNG)

There is a async process. So if you want to do something with index, you have to wait it become available.

**Comment by LorsK** [comment]
I am having a similar issue right now, except the first item added to the list has the index 0. but any consecutive additions have undefined index. So I cannot drag anything a part from the first item. However, when I drag the first item to index 4 (for example) out of 8 items. The index becomes defined for all items with index less than 4. 

I will try to upload a video of this behaviour later on. I am not sure if this is my own issue where im forgetting something>

**Comment by computerjazz** [comment]
fixed in https://github.com/computerjazz/react-native-draggable-flatlist/releases/tag/v2.3.2

Please open a new issue if still seeing this behavior
