### ISSUE TITLE
DraggableFlatList causing problems with react-native-swipe-list-view

### ISSUE THREAD

**Issue by lixuanle** [computerjazz/react-native-draggable-flatlist#107]
I've notified the developer of [`react-native-swipe-list-view`](https://github.com/jemise111/react-native-swipe-list-view) of this conflict as well.

When using `DraggableFlatList` with `react-native-draggable-flatlist` version of v2.0.0 or higher, the `SwipeRow` component from `react-native-swipe-list-view` stops working as intended.

Video of both libraries working as intended with `react-native-draggable-flatlist` v1.1.19:
https://streamable.com/a5mvv

Video of `SwipeRow` not working as intended with `react-native-draggable-flatlist` v2.0.0:
https://streamable.com/wwkdg

When trying to swipe, the row does not open at all, and is instantly closed the moment you try to swipe.

Was there a major change in the code from v1.1.19 to v2.0.0 that affected animations and gesture handlers?

**Comment by computerjazz** [comment]
Yes, there are major breaking changes between 1.x and 2.x, which now uses Reanimated and React Native Gesture Handler. If you're not using Expo you now need to add those new deps.

I'm working on a post about rolling your own swipe list. If there is interest I may consider including it in react-native-draggable-flatlist. You can read the draft here: https://medium.com/@Daniel.Merrill/swipe-to-delete-with-reanimated-react-native-gesture-handler-bd7d66085aee

**Comment by lixuanle** [comment]
Sorry it took me so long to get back to you, but thanks so much for the reply and the article!

I read through it, and I will be trying to implement the swipe gesture with `DraggableFlatList` but was wondering if you think it'll cause any gesture conflicts since `DraggableFlatList` already has so nested gestures as stated in your article.

**Comment by computerjazz** [comment]
I just turned the tutorial into a package that I've tested with DraggableFlatList: https://github.com/computerjazz/react-native-swipeable-item/

Let me know if it works for you!

**Comment by lixuanle** [comment]
I had no problems installing and implementing the new package into my project.

However, I do have a few suggestions and was wondering if you could add them into the package:

- Support for swiping in both directions; currently your package only supports swiping left **or** right. Correct me if I'm wrong though.

- A parameter for allowing swiping all the way but if the user lets go, it'll snap back and stay open depending on the `underlayWidth` value.

- A function to programmatically close rows. For example, if I interact with another row I want to be able to call a `closeRow()` function on the other rows.

If you already had plans/are in the process of implementing these please ignore! Nonetheless, thank you for releasing a package for my issue so quickly after it was opened.

**Comment by computerjazz** [comment]
Cool, glad it's (basically) working! Sure go ahead and copy this to the new repo and let's continue discussion there.

**Comment by computerjazz** [comment]
Opened https://github.com/computerjazz/react-native-swipeable-item/issues/1#issue-545907896
