### ISSUE TITLE
Issues with Touchable component as renderitem

### ISSUE THREAD

**Issue by soumyamishra89** [computerjazz/react-native-draggable-flatlist#109]
When the row has a Touchable item, the user requires to long press on the item to be able to perform the action on the Touchable component.

Moreover, the AnimatedFlatList overrides extraData prop with the internal state, which prevents re render on external data. The extraData prop should be made available as a prop of DraggableFlatList

**Comment by ahmedreda97** [comment]
> When the row has a Touchable item, the user requires to long press on the item to be able to perform the action on the Touchable component.
> 
> Moreover, the AnimatedFlatList overrides extraData prop with the internal state, which prevents re render on external data. The extraData prop should be made available as a prop of DraggableFlatList

+1

**Comment by computerjazz** [comment]
I realize this issue was opened first but closing as #120 has more discussion. Thanks!
