### ISSUE TITLE
Support dnd between flatlists

### ISSUE THREAD

**Issue by milesscherrer** [computerjazz/react-native-draggable-flatlist#11]
Any plans on supporting this or suggestions on how to to it? 

Looking for a way to implement trello/kanban style dnd between horizontal flatlists and this is the closest thing I have found for React Native so it would be awesome.

**Comment by computerjazz** [comment]
Interesting idea. I don't plan on supporting this feature, but if I were to guess how to do it, it'd be by wrapping all FlatLists in an outer container, which is where the cloned element would be rendered. Not sure if there'd be added complexity in the adding/removing elements from adjacent lists.

**Comment by shakogegia** [comment]
It will be really helpful

**Comment by agnieszkabugla** [comment]
@milesscherrer, did you manage to implement trello-like dnd in React Native? I'm really curious as I need to build something similar and I couldn't find any library that supports dnd not only inside list, but also between horizontal flatlists...

**Comment by rodgomesc** [comment]
I need this feature too, please guys

**Comment by cenaHara** [comment]
hi @all any solution

**Comment by vasylnahuliak** [comment]
Possible solution https://github.com/KagasiraBunJee/react-native-swimlane
