### ISSUE TITLE
Problem with drag & drop for items with different size

### ISSUE THREAD

**Issue by simonecorsato** [computerjazz/react-native-draggable-flatlist#111]
I noticed a wrong behaviour while using drag & drop with items of different size.
When drag ends, on release, there is an animation that move the item in a wrong position in the list. If I switch to a list of items of the same size (height) drag & drop work correctly.
I tried to find the problem in react-native-draggable-flatlist code but I saw that cell size is already considered while evaluating drag & drop. Maybe I'm missing something.

**Comment by computerjazz** [comment]
Hm yeah i originally tested with items of different size as you saw in the code but you're right -- something's not right. Will look into it.

**Comment by simonecorsato** [comment]
Thank you. I'm testing the master branch, version 2.0.10.

**Comment by computerjazz** [comment]
Just released what I believe is the fix in 2.0.11 -- can you give it a try and see if it fixes your issue?

**Comment by simonecorsato** [comment]
Thank you for your fix. Now the list can handle properly cells with different size.
I just opened a pull request (https://github.com/computerjazz/react-native-draggable-flatlist/pull/118) because I needed to expose a few functions of FlatList, in case it will be accepted I will be able to use directly your master branch instead of my fork. Thanks for your support.
