### ISSUE TITLE
Getting many "Excessive number of pending callbacks: 501" errors

### ISSUE THREAD

**Issue by dereknelson** [computerjazz/react-native-draggable-flatlist#112]
Just migrated from 1.1.7 to 2.0.10, and now (mostly triggered by scrolling in my experience so far) I'm getting this warning:
```
Warning: Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {
"66781":{"module":"ReanimatedModule","method":"getValue"},
"66784":{"module":"ReanimatedModule","method":"getValue"},
"66787":{"module":"ReanimatedModule","method":"getValue"},
"66791":{"module":"ReanimatedModule","method":"getValue"},
"66794":{"module":"ReanimatedModule","method":"getValue"},
"66797":{"module":"ReanimatedModule","method":"getValue"},
"66800":{"module":"ReanimatedModule","method":"getValue"}, ...
```
I'm using 
```
"react-native": "0.61.4",
"react-native-reanimated": "~1.4.0",
"react-native-gesture-handler": "~1.5.0",
```
with expo sdk 36
This is my list setup:
```
<DraggableFlatlist
  onRef={ref => (this.tasksList = ref)}
  style={{ flex: 1 }}
  data={tasks}
  initialNumToRender={10}
  keyExtractor={task => `${task.id}`}
  renderItem={this.renderItem}
  extraData={this.props}
  keyboardShouldPersistTaps="handled"
  onRefresh={this.onRefresh}
  refreshing={refreshing}
  ItemSeparatorComponent={() => <ItemSeparator projectView={projectView} />}
  onEndReached={this.fetchNextPage}
  onEndReachedThreshold={0.5}
  ListFooterComponent={this.renderFooter}
/>

...

renderItem = ({ item, index, drag, isActive }) => {
  const props = {
    key: item.id,
    task: item,
    onLongPress: drag,
    index,
    ...otherPropsOmittedForClarity
  }
  return (
    <View
      style={isActive ? styles.draggingRow : {}}
      pointerEvents={isActive ? 'none' : 'auto'}
    >
      <TaskRow {...props} />
    </View>
  )
}
```

Not sure if it's related, but I am also getting a bunch of `## can't measure (key) reason: no ref` for tasks after the initial 10 ([I log the key if we're trying to measure](https://user-images.githubusercontent.com/6868432/71937192-ac50c600-3179-11ea-90d4-460a8dac1885.png)), and if I remove initialNumToRender I get in between 20-25 before the "can't measure" shows up. 

The list items are variably sized [tasks](https://user-images.githubusercontent.com/6868432/71936898-b8885380-3178-11ea-8f74-6eb3c4ebecef.png), where TaskRow is a <View> wrapping an animated View with gesture handlers for swiping left/right. Other than that, the items are pretty straightforward, I don't think I'm doing anything novel that warrants weird behavior like excessive pending callbacks.

Happy to provide more details as needed, I'm a huge reanimated fan so I'm very excited to see this library be written with it. Thanks for all your hard work!

**Comment by computerjazz** [comment]
Thanks for the writeup, if you can provide a repro snack that would be awesome.

There was also an animation bug when row items were not all the same size -- I just released 2.0.11 which should fix it. However, the bug was related to calculating which row is currently hovered-over and doesn't sound related to what you describe above.

Also, I recently released a swipeable item component that may be useful to you: https://github.com/computerjazz/react-native-swipeable-item/blob/master/README.md

**Comment by dereknelson** [comment]
@computerjazz hoping to get you a snack repro by tuesday, otherwise it'll be at some point next week. I'll check out your swipeable item library, thanks!

**Comment by dereknelson** [comment]
@computerjazz found [this issue](https://github.com/software-mansion/react-native-reanimated/issues/381) so I'm trying to factor that into my debugging to see if it's the cause, it seems it is. Thoughts?

**Comment by computerjazz** [comment]
Yeah I'm aware of that issue, but I've verified in my own projects that it was fixed in RN 0.61.2, so it doesn't seem like it should apply here.

**Comment by dereknelson** [comment]
@computerjazz I'm starting to narrow down the cases in which it happens, using fast refresh is definitely one of them. 
However, there are instances where the renderItem function I pass to the list is called with index undefined - my render item method depends on the index for some logic and I think that might have an effect, any idea why that would happen?

**Comment by computerjazz** [comment]
Oh yeah i've stopped using fast refresh after hitting a few other subtle bugs, which is too bad.
The only reason I can think of that an item wouldn't be called with an index is if it didn't exist in the `keyToIndex` map, which could be related to the ref issue above. Off the top of my head I'm not sure why that would be happening.

**Comment by computerjazz** [comment]
Yeah I had to include lots of performance optimization to make sure list items didn't rerender excessively. I'm sure there's room for improvement in getting items to rerender when we want them to.

**Comment by dereknelson** [comment]
I have two proposed solutions:
1. adding a this.setState after onNextFrame in componentDidUpdate such that the items are at least guaranteed to rerender with the index, and returning null in <RowItem /> so that people who rely on the index for rendering logic don't have crashes/unpredictable behavior
2. doing something in render like 
```
renderItem = () => {
...
if (!this.keyToIndex.get(itemKey) this.keyToIndex.set(itemKey)
```
but I don't like doing things with side effects in render

Going to try to the first solution and let you know if I get any weird behavior

**Comment by dereknelson** [comment]
@computerjazz not sure why I made it way more complicated than it had to be with the above solutions, I passed an "listIndex" where the index passed to the item is `keyToIndex.get(itemKey) || listIndex`

**Comment by dereknelson** [comment]
been using it in production and haven't had any issues with the pending callbacks

**Comment by eric-om** [comment]
@dereknelson hey I'm running into the same issue. Would you mind explaining your solutions and how to implement? Thanks!

**Comment by dereknelson** [comment]
@eric-om when you call the renderItem in props just do something like 
```
{ ...props, index: keyToIndex.get(itemKey) || listIndex }
```

**Comment by eric-om** [comment]
@dereknelson sorry for the newb question but I'm passing a renderItem function to the renderItem prop on the DraggableFlatList.

It looks like this: `const renderItem = ({ item, index, drag, isActive }) => { ... }`

I tried doing this in the renderItem prop `renderItem={(props) => renderItem({ ...props, index: keyToIndex.get(itemKey) || listIndex })}` but I got error `Can't find variable: keyToIndex`.

**Comment by rachellauyui** [comment]
@computerjazz @dereknelson Hey guys, another newbie here. Also have the same problem. Also don't understand what { ...props, index: keyToIndex.get(itemKey) || listIndex } means? I see there are a few open issue with this same errors too. I wonder if you have time just to write a short demo, nothing fancy, just start with <DraggableFlatList ... renderItem... etc/>

Thank you so much in advance!!

**Comment by kiennguyen-alobridge** [comment]
I also encounter this situation when scrolling the list too fast and that causes the view to be hidden or the list to display chaotically then return correctly.
