### ISSUE TITLE
extraData prop is not working

### ISSUE THREAD

**Issue by panda0603** [computerjazz/react-native-draggable-flatlist#119]
I am trying to make draggable bar show up when user clicks on edit button. 

I use state to check edit mode, i.e. isEdit=true or false. 

I need components in renderItem to re-render when this.state.isEdit changes, so I have used 

```
extraData={this.state.isEdit} 
```
This currently does not work in the latest version, 2.0.12.

**Comment by ivan-kalinin** [comment]
Vote! Yes, the same issue for me. Please, I would really appreciate it if it will be fixed soon @computerjazz

**Comment by computerjazz** [comment]
fixed in 2.0.13
