### ISSUE TITLE
Glitches after state updated with onDragEnd

### ISSUE THREAD

**Issue by calebmcelroy** [computerjazz/react-native-draggable-flatlist#123]
**See Screen Recording:**
https://tangentmedia.com/glitchy-draggable-flatlist.mp4

After onDragEnd and state is updated the list glitches and jumps around. This happens with the default example given. 

I've tested on Android emulator, iOS emulator, & physical iPhone 6, this it happens on them all.

Is this a known behavior? If not what can I do to fix?

Appreciate your help!

react-native: 0.61.3
react-native-draggable-flatlist: 2.0.14

**Comment by computerjazz** [comment]
There is a hand-off between the state of the list at the end of the drag, when some items need to be translated up/down to fill the space of the dragged item, and the next state of the rearranged list. It looks like you're seeing a frame or so of this handoff -- the items that had to shift are the ones that glitch.

However, I don't see this behavior when I run -- which version of Reanimated/RNGH are you on?

**Comment by computerjazz** [comment]
Also, is your example code exactly the code in the README?
Did you add any console logging anywhere? 
Debugger on/off?

**Comment by computerjazz** [comment]
Also, I just noticed you're not running the bare example, but embedded in a tab navigator -- is there anything expensive going on in your other tabs? 

I'm trying to repro in a snack here by adding lists to a bunch of tabs and still don't see the flash: https://snack.expo.io/@computerjazz/e1d0b0

**Comment by calebmcelroy** [comment]
Thanks for your response. Just got it working!

I was running:
```
react-native-gesture-handler: 1.5.0
react-native-reanimated: 1.3.0
```

Upgraded to:
```
react-native-gesture-handler: 1.5.3
react-native-reanimated: 1.6.0
```

And that fixed it.

**Comment by computerjazz** [comment]
great, there were major perf improvements introduced in reanimated 1.4

**Comment by computerjazz** [comment]
oh, btw there are some bugs in reanimated 1.6 -- might want to roll back to 1.4 until the fixes are released: https://github.com/software-mansion/react-native-reanimated/issues/561

**Comment by calebmcelroy** [comment]
Yea just ran into those bugs. Didn't crop up in the bare example, but did in my app. I just downgraded to 1.4 and working great. Thanks again!

**Comment by namanica** [comment]
I'm still experiencing the same issue in 2026, although I'm using best practices. Used packages:
`
 "react-native-gesture-handler": "~2.24.0",
 "react-native-reanimated": "~3.17.4",
"react-native-draggable-flatlist": "^4.0.3",
`

**Comment by Strelya72** [comment]
Still reproducible on `react-native-draggable-flatlist@4.0.3`.

Stack: `Expo SDK 55`, `React Native 0.83.6`, `Reanimated 4.2.1`, `React Native Gesture Handler 2.30.1`
Device: iOS.

Case: vertical list, 4 items, moving the first item to the last position, then updating state from `onDragEnd`.

Workaround that fixed it for us:

```tsx
const orderKey = items.map((item) => item.id).join('|');

<DraggableFlatList
  key={orderKey}
  data={items}
  onDragEnd={({ data }) => {
    requestAnimationFrame(() => setItems(data));
  }}
/>
```

This remounts the list after reorder, clearing stale animated/layout state.
Downside: internal list state is reset on each reorder.
