### ISSUE TITLE
Left/right swipe gestures getting swallowed

### ISSUE THREAD

**Issue by peeveen** [computerjazz/react-native-draggable-flatlist#125]
Hi,
I'm trying to use your component inside a tab view (https://github.com/react-native-community/react-native-tab-view). This view has three tabs , two of which contain normal FlatList components, and one that contains your DraggableFlatList.
I can swipe left/right to a different tab from a tab that contains a normal FlatList, but from the tab that contains the DraggableFlatList, the swiping gesture seems to get lost, presumably processed by the component and not propagated to the parent.
If it comes down to it, I'll just disable swiping and the user will have to navigate between the tabs by touching the tab headers, but it seems like a possible bug.

**Comment by computerjazz** [comment]
Hm yeah, I think this would require adding an activation threshold to the PanGestureHandler. Will look into it.

**Comment by computerjazz** [comment]
Added `activationDistance` prop to prevent swallowing parent gestures in 2.0.15. I set it to `5` and react-navigation tab swiping began to work again. The tradeoff is that now the finger must move 5px vertically before the item begins to move.

Please try >= 2.0.15 and let me know if that fixes your issue.
