### ISSUE TITLE
Sample code using scrollToIndex with DraggableFlatList?

### ISSUE THREAD

**Issue by tomgiam** [computerjazz/react-native-draggable-flatlist#126]
Hi,

I'm trying to add the scrollToIndex feature into DraggableFlatList , but I get the error: "_this.flatListRef.scrollToIndex is not a function..."

The code I'm using is a modified version of the example from FlatList which works. The issue is probably with this line:
onRef={onRef => {
            this.flatListRef = onRef;
          }}

import React, { Component } from "react";
import { Text, View, FlatList, Dimensions, Button, StyleSheet } from "react-native";
import DraggableFlatList from "react-native-draggable-flatlist";

const { width } = Dimensions.get("window");

const style = {
  justifyContent: "center",
  alignItems: "center",
  width: width,
  height: 50,
  flex: 1,
  borderWidth: 1
};

const COLORS = ["deepskyblue", "fuchsia", "lightblue "];

function getData(number) {
  let data = [];
  for (var i = 0; i < number; ++i) {
    data.push("" + i);
  }

  return data;
}

class ScrollToIndex extends Component {
  getItemLayout = (data, index) => ({ length: 50, offset: 50 * index, index });

  getColor(index) {
    const mod = index % 3;
    return COLORS[mod];
  }

  scrollToIndex = () => {
    let randomIndex = Math.floor(Math.random(Date.now()) * this.props.data.length);
    console.log(randomIndex);
    this.flatListRef.scrollToIndex({ animated: true, index: randomIndex });
  };

  scrollToItem = () => {
    let randomIndex = Math.floor(Math.random(Date.now()) * this.props.data.length);
    this.flatListRef.scrollToIndex({ animated: true, index: "" + randomIndex });
  };

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <Button onPress={this.scrollToIndex} title="Tap to scrollToIndex" color="darkblue" />
          <Button onPress={this.scrollToItem} title="Tap to scrollToItem" color="purple" />
        </View>
        <DraggableFlatList
          style={{ flex: 1 }}
          onRef={onRef => {
            this.flatListRef = onRef;
          }}
          keyExtractor={item => item}
          getItemLayout={this.getItemLayout}
          initialScrollIndex={50}
          initialNumToRender={2}
          renderItem={({ item, index }) => (
            <View style={{ ...style, backgroundColor: this.getColor(index) }}>
              <Text>{item}</Text>
            </View>
          )}
          {...this.props}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  header: {
    paddingTop: 20,
    backgroundColor: "darkturquoise",
    alignItems: "center",
    justifyContent: "center"
  }
});

export default class app extends Component {
  render() {
    return <ScrollToIndex data={getData(100)} />;
  }
}

Thanks
Tom

**Comment by computerjazz** [comment]
The flatlist ref is an Animated flatlist component, so the underlying flatlist is nested in the `_component` key. I recommend you log it out and have a look.

example usage: https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/index.tsx#L511

**Comment by tomgiam** [comment]
Hi,

Thanks for responding. I should not have titled this "Issue with using scrollToIndex", what I'm really looking for is example code using scrollToIndex with DraggableFlatlist. In fact let me change that.

Thanks
Tom

**Comment by tomgiam** [comment]
Oh wait, I think I figured it out... I need to use "this.flatListRef.current._component.scrollToIndex({ animated: true, index: "" + randomIndex });"

it's working... a bit slow though, but I need to upgrade to reanimated > 1.3
