### ISSUE TITLE
If an item is deleted, lower rows are not rerendered with the new index.

### ISSUE THREAD

**Issue by kdo1234** [computerjazz/react-native-draggable-flatlist#129]
If an item is deleted, lower rows are not rerendered with the new index 
Here is a snack that reproduces the issue.
https://snack.expo.io/S1UBdsQ_8

**Comment by computerjazz** [comment]
Hm this was originally by design -- rerendering the entire list on item deletion could be a performance hit. For now you could include `data.length` as `extraData`
