### ISSUE TITLE
Not working for the second time.

### ISSUE THREAD

**Issue by Harsh2402** [computerjazz/react-native-draggable-flatlist#130]
I have used this library, 

```
    "react": "16.9.0",
    "react-native": "0.61.0",
```

When I came in this screen, then the first time, it's working fine,
Then I go back and came again, then it behaves odd, can not drag the item as required, first and second item scroll automatically and selected item drag out of the screen.

Can you please help to check it once?

**Comment by Harsh2402** [comment]
@computerjazz Can you please help to check, the item which I need to drag is not able to see, can show black at there place and once I set new position after dragging, then I can see that item.

**Comment by computerjazz** [comment]
let's consolidate this conversation under the other issue you opened #131
