### ISSUE TITLE
onPress doesn't work 

### ISSUE THREAD

**Issue by matcwi** [computerjazz/react-native-draggable-flatlist#134]
This Bug exists in versions after @2.0.0(included). Till I use @1.1.7 and @1.1.9 everything was working fine. Previously (before upgrading to the newest release) I hadn't any problems with any functionality.
After upgrading to @2.0.0 (and newer) : When I try to add onPress function to a renderItem it doesn't have any actions. The problem is only with onPress function - onLongPress, and onDragEnd works properly. I checked this bug on my own code and on the example code from rn-draggable-flatlist, in both cases I couldn't do onPress func.

I use typescript & react-native & android.

Dependencies : 
 "react-native": "0.60.4",
"react-native-draggable-flatlist": "2.1.2",
"react-native-gesture-handler": "^1.3.0",
"react-native-reanimated": "^1.2.0",

**Comment by curiousdustin** [comment]
See #120 for more info. This is a duplicate.

**Comment by computerjazz** [comment]
closing in favor of #120
