### ISSUE TITLE
Custom Item Component does not rerender

### ISSUE THREAD

**Issue by FrankFundel** [computerjazz/react-native-draggable-flatlist#137]
**Describe the bug**
Custom components do not rerender when props change in renderItem function.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: ios
 - React Native or Expo version: React Native
 - Reanimated version: 1.4.0
 - React Native Gesture Handler version: 1.5.3

**Additional context**
Custom component is a PureComponent. With FlatList every item rerenders.

**Comment by FrankFundel** [comment]
On 1.1.19 it works

**Comment by computerjazz** [comment]
List items are heavily memoized for performance. If you need items to re-render try passing an `extraData` prop to the flatlist.

**Comment by FrankFundel** [comment]
I have that. As I said with FlatList every item rerenders.

**Comment by FrankFundel** [comment]
I still have that issue.

**Comment by FrankFundel** [comment]
Solved, I had multiple `extraData `attributes like `extraData={this.state.xxx || this.state.yyy}` instead it should be `extraData={[this.state.xxx, this.state.yyy]} `
