### ISSUE TITLE
TouchableOpacity in renderItem is clicked while on scroll 

### ISSUE THREAD

**Issue by panda0603** [computerjazz/react-native-draggable-flatlist#138]
**Describe the bug**
I have TouchableOpacity component in renderItem. While trying to scroll down the list, item(on which my thumb stands on first touch trying to scroll) is automatically clicked. 
Following warning is reproduced right after: 

```
Sending 'onAnimatedValueUpdate' with no listeners registered.
```

**To Reproduce**
TouchableOpacity component in renderItems. Enough Items to enable scrolling down. 

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: IOS, Android
 - React Native or Expo version: 0.61.5
 - Reanimated version: 1.7.0
 - React Native Gesture Handler version: 1.5.6

**Comment by panda0603** [comment]
found the cause, it happens when I use onPressOut(due to the current ongoing issue with onPress) within renderItem component.

**Comment by computerjazz** [comment]
Thanks for the followup. Closing as underlying issue is #120
