### ISSUE TITLE
Support for flat list with columns

### ISSUE THREAD

**Issue by bhumit1709** [computerjazz/react-native-draggable-flatlist#14]
This works very nice with single column FlatList but drag and drop fails when working with multiple columns. Like for example I can only drag the item up and down not side ways, so I cant move item form column 1 to column 2.

Do you have ideas how can I achieve this?  I have also attached screenshot to show what I am talking about.

Thanks for this.
![img_2bea02ddd87e-1](https://user-images.githubusercontent.com/16148136/44983079-8881dc80-af95-11e8-9e5f-bfc3fd4bf41a.jpeg)

**Comment by wowtrxqn** [comment]
can you find good idea for this situation？

**Comment by wowtrxqn** [comment]
i tested but seems that no effects

**Comment by luan-nvg** [comment]
alguém conseguiu resolver?

**Comment by XeeshanAnsari** [comment]
Same issue here.
If someone already fixes this issue so let me know, please.

**Comment by luan-nvg** [comment]
> O mesmo problema aqui.
> Se alguém resolver esse problema, entre em contato.

friend, ready to use another react-native-sortable-grid plugin
I tested the responsiveness of it and it is perfect on small J1 cell phones, I just had to configure it to pause the scroll and not use TouchableOpacity components in react native, I used View with tap
