### ISSUE TITLE
Is it possible to add a dragHandle functionality

### ISSUE THREAD

**Issue by jaredgreener** [computerjazz/react-native-draggable-flatlist#141]
I'm new to react and used to working with jQuery. I would like to maintain the normal scroll functionality while also utilizing 'onPressIn' vs 'onLongPress' for usability. The ideal solution would be a drag handle element that only initiates the drag functionality of the entire item when a small icon is touched.

**Comment by computerjazz** [comment]
This is totally possible, but the UI is up to you to implement. `renderItem` gives you a `drag` method, so instead of calling `onLongPress={drag}`, you could call `onPressIn={drag}` on your icon touchable.

**Comment by creambyemute** [comment]
@jaredgreener My ListItem does that,

It renders the Text/Data on the left and icons on the right.

```javascript
<IconButton
    animated={true}
    icon={"drag-handle"}
    size={20}
    onPress={this.onPressDragIcon}
    onLongPress={this.onMoveListItem}
    delayLongPress={100}
/>
```

The UI and when the drag is activated on the item is up to you to decide

**Comment by computerjazz** [comment]
closing as the solution has been posted above
