### ISSUE TITLE
Cannot have Touchables within renderItem

### ISSUE THREAD

**Issue by evancloutier** [computerjazz/react-native-draggable-flatlist#142]
**Describe the bug**
With version 2.2.0 -- I cannot have a nested Touchable within my `renderItem` prop, since there is a wrapper `TapGestureHandler` that is always present on the child.

However, it looks like you have already fixed this on master (forked to confirm). Do you have a timetable for releasing the new version?

Thanks! This is a great library @computerjazz.

**Comment by computerjazz** [comment]
Thanks for testing out the changes! 
I'd like to get a few more people to test before I release, but I haven't run into any issues so far, so likely soon.

Closing as this issue is thoroughly discussed in #120
