### ISSUE TITLE
V2. Add support for shouldChangeOrder prop.

### ISSUE THREAD

**Issue by alekseyanikin** [computerjazz/react-native-draggable-flatlist#143]
Sometimes you need the ability to restrict moving the row lower or upper.

It might look like this

```
<DraggableFlatList
    data={this.state.data}
    renderItem={this.renderItem}
    keyExtractor={(item, index) => `draggable-item-${item.key}`}
    onDragEnd={({data}) => this.setState({data})}
    shouldChangeOrder={({activeIndex, nextIndex, items}) => {
        if (items[nextIndex].someCondition) {
            return true;
        }
        return activeIndex > nextIndex;
     }}
 />
```

**Comment by computerjazz** [comment]
Interesting idea, but unfortunately this would require a call back to JS during the gesture, which would partially defeat the purpose of the react-native-gesture-handler + reanimated performance benefits.

**Comment by computerjazz** [comment]
Also, what would the release animations look like in the case that the row should not change? Would it snap back to its original place? Or go to the next-available spot? 

These kinds of complexity make it unlikely that I'll integrate this feature. As a workaround, you could do the check after the drag has taken place, and do the reordering then.

**Comment by alekseyanikin** [comment]
> Also, what would the release animations look like in the case that the row should not change? Would it snap back to its original place? Or go to the next-available spot?
> 
> These kinds of complexity make it unlikely that I'll integrate this feature. As a workaround, you could do the check after the drag has taken place, and do the reordering then.

For v1, I did so, if the row can not get to the desired position, then it returns to the previous available

![demo-1](https://media.giphy.com/media/YleWBqpdqhY6sRgczj/giphy.gif) ![demo-2](https://media.giphy.com/media/j3KIBndb7eDcIEh48a/giphy.gif)

**Comment by computerjazz** [comment]
What happens if you drag `4` or `5` ? Can you pick them up as a group?

**Comment by alekseyanikin** [comment]
> What happens if you drag `4` or `5` ? Can you pick them up as a group?
You can drag these, because `shouldChangeOrder` allows it.
No group pickup.
