### ISSUE TITLE
Slow show and hide DraggableFlatList 

### ISSUE THREAD

**Issue by bkitduy** [computerjazz/react-native-draggable-flatlist#148]
I have a feature when user click button, the button will collapsed and expanding the view. It's means show and hide the DraggableFlatList when the button is clicked. But it's make the event click to slow, about 2s - 3s if DraggableFlatList have about 4 items. The more items in DraggableFlatList, the more delay to show and hide DraggableFlatList.
Example:
`<View>
{ isShow?
  <View/>
  :
  <DraggableFlatList .../>
}
</View>`

**Comment by computerjazz** [comment]
Please fill out the issue template

**Comment by computerjazz** [comment]
Hm I just tested here and hide/show is pretty immediate with 40 items: https://snack.expo.io/@computerjazz/rndf-togglehidden

There is a small delay, but much shorter than 2-3 sec. Are you sure you're not just rendering very expensive items?

**Comment by bkitduy** [comment]
I'm rendering expensive items than your example. Can you explain why there is a delay when I using DraggableFlatlist? No issue when I using Flatlist

**Comment by computerjazz** [comment]
Each row has a fairly complex animated value that is necessary to track and respond to gestures. The addition of `proc` in reanimated 1.4 speeds up mount time a lot -- what version of reanimated are you on?

**Comment by bkitduy** [comment]
The current version of reanimated I'm on 1.2. After I upgraded to newest version 1.7, there is a small delay but still OK. Thanks for your support.
