### ISSUE TITLE
move is not  a function.(In 'move()',move is undefined ).On upgrading react-native-draggable-flatlist to 2.1.1 version on dragging it gives this error

### ISSUE THREAD

**Issue by AswathiRevathi** [computerjazz/react-native-draggable-flatlist#153]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**

**To Reproduce**
Link a snack if possible.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform:
 - React Native or Expo version:
 - Reanimated version:
 - React Native Gesture Handler version:

**Additional context**

**Comment by computerjazz** [comment]
all `move` functionality has been renamed `drag` in v2, see readme

**Comment by AswathiRevathi** [comment]
thank you..
