### ISSUE TITLE
In ios,items are correctly dragging and placing.But in android when we try to drag an item to top of screen ,its getting added to bottom of list.Sometimes when i drag,it leaves white space with the same height of an item in between items in the list.

### ISSUE THREAD

**Issue by AswathiRevathi** [computerjazz/react-native-draggable-flatlist#154]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**

**To Reproduce**
Link a snack if possible.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform:
 - React Native or Expo version:
 - Reanimated version:
 - React Native Gesture Handler version:

**Additional context**

**Comment by AswathiRevathi** [comment]
![Screenshot_1583401268](https://user-images.githubusercontent.com/31061550/75969351-d6620280-5ef4-11ea-892a-e19ac9401eca.png)

**Comment by AswathiRevathi** [comment]
![2020-03-05](https://user-images.githubusercontent.com/31061550/75969497-0c9f8200-5ef5-11ea-9621-d79963406a21.jpg)

**Comment by puneetkansal04** [comment]
This issue still persists in IOS on react-native 0.61.5
