### ISSUE TITLE
Adding an onScroll event

### ISSUE THREAD

**Issue by Karthik-B-06** [computerjazz/react-native-draggable-flatlist#158]
How can I add my own onScroll event to the Flatlist like this?
```  
const _onScroll = Animated.event(
    [{ nativeEvent: { contentOffset: { y: scrollY } } }],
    { useNativeDriver: false },
  )
```
I am listening to the scrollY value but its not changing even though the list gets scrolled.

**Comment by computerjazz** [comment]
see https://github.com/computerjazz/react-native-draggable-flatlist/issues/127

**Comment by Karthik-B-06** [comment]
Thanks a ton. It worked.

**Comment by Manu206** [comment]
@Karthik-B-06 Could you give a sample on how you solved it with the newly added `onScrollOffsetChange`?
In a reanimated scrollview I would call a Animated.Event like you mentioned however `onScrollOffsetChange` will just handle a number if I set the scrollY via state it is very slow and not smooth.

**Comment by Karthik-B-06** [comment]
@Manu206 Hey I did not get an opportunity to work with the latest react native reanimated version. 
Since `onScrollOffsetChange` returns the offset we cant pass in an Animated event like in `onScroll`. 

Check/Try [this](https://github.com/computerjazz/react-native-draggable-flatlist/issues/127#issuecomment-588537742)
