### ISSUE TITLE
Haptic Support / Custom Function for onReorder

### ISSUE THREAD

**Issue by nestedJSObject** [computerjazz/react-native-draggable-flatlist#169]
**Is your feature request related to a problem? Please describe.**
It is common for apps to provide haptic feedback when reordering items in a list, but this package currently lacks that functionality.

**Describe the solution you'd like**
I would like either (A) haptic support (i.e. a prop like **hapticFeedback={true}**) where haptic feedback is provided when (1) row becomes active, AND (2) list changes due to moving the row;
or (B) props like **onReorder={() => void}** which is called when the active row causes the list to change (or when the rows animate).

**Describe alternatives you've considered**
I actually was able to code my own solution but now I cannot because the file is .tsx not .js.

**Additional context**

**Comment by computerjazz** [comment]
this feature is out of scope for this package.

**Comment by jmparsons** [comment]
@computerjazz I'm actually trying to implement haptic as well. It's pretty straight forward, but I think it's also out of the scope for this package as well. If there was a `onDragUpdate` method with access to `spacerIndex` then we could wire it in with something like this:

```js
import * as Haptics from 'expo-haptics';

<DraggableFlatList
  data={this.state.data}
  renderItem={this.renderItem}
  keyExtractor={(item, index) => `draggable-item-${item.key}`}
  onDragEnd={({ data }) => this.setState({ data })}
  onDragUpdate={({ spacerIndex }) => {
    // where method only fires on drag, not after release
    if (spacerIndex >= 0) {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    }
  }}
/>
```
