### ISSUE TITLE
## measure error -- index:  0 -1

### ISSUE THREAD

**Issue by JoseATP** [computerjazz/react-native-draggable-flatlist#17]
Hi
I'm implementing this library in my project.
I am importing this  : import DraggableFlatList from 'react-native-draggable-flatlist'
in two different components and I set different data through the <DraggableFlatList>
data1.js 
<DraggableFlatList
                    data={this.props.data1}
------------------------------------------
data2.js
<DraggableFlatList
                    data={this.props.data}

After a while I get this error :
## measure error -- index:  0 -1
Error: Unable to find node on an unmounted component.

Do you know why?
Thanks

**Comment by SirishaBellam** [comment]
Hi @computerjazz, 

I am using this library, and updated it to 1.1.7. Im getting same error **unable to find node on an unmounted component** at react-native-draggable-flatlist\index.js:346:12
![crash](https://user-images.githubusercontent.com/28588436/52711641-50f17480-2fb8-11e9-8a06-9400c980c16c.png)
