### ISSUE TITLE
Dragging is bugged on android device when inside Modal

### ISSUE THREAD

**Issue by DavidFlores91** [computerjazz/react-native-draggable-flatlist#170]
**Describe the bug**
When the DraggableFlatList is inside a modal on an android device, the drag and drop stops working.

https://drive.google.com/open?id=1VEXv8Ws3-IC1bHKD3xYoG582EhJt6Tz-

**Platform & Dependencies**
 - react-native-gesture-handler version: 1.5.6
 - react-native-draggable-flatlist version: 2.3.2
 - Platform: Android
 - React Native: 0.60.5
 - Reanimated version: 1.7.1

**Additional context**
In iOS the DraggflatList works inside a modal, in android it works if it is outside the modal

**Comment by DavidFlores91** [comment]
**Solution**
https://github.com/software-mansion/react-native-gesture-handler/blob/master/docs/getting-started.md#usage-with-modals-on-android

"react-native-gesture-handler": "^1.6.1"
"react-native-draggable-flatlist": "^2.3.2"

**Comment by Treelab-Will** [comment]
> **Solution**
> https://github.com/software-mansion/react-native-gesture-handler/blob/master/docs/getting-started.md#usage-with-modals-on-android
> 
> "react-native-gesture-handler": "^1.6.1"
> "react-native-draggable-flatlist": "^2.3.2"

Can you provide details of your implementation? This still doesn't work for me

**Comment by maps82** [comment]
A current version of the document is here: https://github.com/software-mansion/react-native-gesture-handler/blob/master/docs/docs/getting-started.md#usage-with-modals-on-android

But it still doesn't work for me (DraggableFlatList in a modal: dragging works on iOS but not on Android). Ist there a solution? Can we re-open this ticket?

**Comment by DavidFlores91** [comment]
this was solved by reading the version documentation : https://github.com/computerjazz/react-native-draggable-flatlist/issues/170#issuecomment-612231975, Thanks to everyone for your replies

**Comment by DavidFlores91** [comment]
I attach the code of my implementation:
![Uploading Screenshot at Aug 13 17-34-18.png…]()
![Screenshot at Aug 13 17-35-45](https://user-images.githubusercontent.com/63429994/90194541-2dfe7700-dd8d-11ea-827b-317280544feb.png)

**Comment by maps82** [comment]
I wrapped the DraggableFlatList in the `gestureHandlerRootHOC` and also adjusted MainActivity.java as described [here](https://github.com/software-mansion/react-native-gesture-handler/blob/master/docs/docs/getting-started.md#updating-mainactivityjava) but without success. Is there more todo?

**Comment by DavidFlores91** [comment]
> I wrapped the DraggableFlatList in the and also adjusted MainActivity.java as described [here](https://github.com/software-mansion/react-native-gesture-handler/blob/master/docs/docs/getting-started.md#updating-mainactivityjava) but without success. Is there more todo?`gestureHandlerRootHOC`

I show you my mainActivity.java :

![Screenshot at Aug 13 18-02-42](https://user-images.githubusercontent.com/63429994/90195559-5ab38e00-dd8f-11ea-8c6e-3c1b6fd5aa60.png)

**Comment by maps82** [comment]
I have the very same ReactActivityDelegate method here. Still no success. 

- react-native-gesture-handler 1.7.0
- react-native-draggable-flatlist 2.3.6
- react-native 0.63.2
- react-native-reanimated 1.13.0

**Comment by DavidFlores91** [comment]
> Tengo el mismo método ReactActivityDelegate aquí. Aún no hay éxito.
> 
> * react-native-gesture-handler 1.7.0
> * react-native-draggable-flatlist 2.3.6
> * reaccionar nativo 0.63.2
> * react-native-reanimated 1.13.0

This worked for me:
- "react-native-gesture-handler": "^1.6.1"
- "react-native-draggable-flatlist": "^2.3.2"
- "react-native": "0.60.5"
- "react-native-reanimated": "^1.7.1"

**Comment by jaydips2020** [comment]
@DavidFlores91  its works) for me thanks
