### ISSUE TITLE
refreshControl preventing scroll on Android

### ISSUE THREAD

**Issue by AndyRC6** [computerjazz/react-native-draggable-flatlist#174]
**Describe the bug**
On Android, passing a refreshControl as a prop to DraggableFlatList interferes with scrolling gestures on the flatlist. This prevents you from being able to scroll the flat last at all. Swiping down anywhere on the flatlist will just bring down the refresh component. 

**To Reproduce**
                  <DraggableFlatList
                    data={items}
                    ref={ref}
                    refreshControl={
                        <RefreshControl
                          onRefresh={() =>{
                            refreshList();
                        }}
                        title={'loading...'}
                        refreshing={loading}
                        />
                    }
                    renderItem={ item => <ListComponent
                    id={item.id} 
                    data={item}  
                    />
                   }
                    keyExtractor={item => item.id }
                    onDragEnd={({ data }) => {
                        reorderList(data);
                        })
                    }}
                    />

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: Android
 - React Native or Expo version: Expo SDK 36.0.0
 - Reanimated version: 1.4.0
 - React Native Gesture Handler version: 1.5.0

**Additional context**
I have found that adding an activationDistance prop to the draggableFlatList fixes the scrolling issue on Android. HOWEVER, it then interferes with dragging functionality - causing elements to be offset by the same number set in the activationDistance prop. If you set activationDistance to 50 for example, when you try to drag anything in the flatlist, it will be offset by 50 pixels from your finger. This is not a solution that will work as it makes dragging things very janky.

**Comment by computerjazz** [comment]
duplicate https://github.com/computerjazz/react-native-draggable-flatlist/issues/135
