### ISSUE TITLE
OnScrollOffsetChange

### ISSUE THREAD

**Issue by rickchi2003** [computerjazz/react-native-draggable-flatlist#177]
**Describe the bug**

when scroll to the bottom of the list, onScrollOffsetChange will be triggered infinitely

**To Reproduce**

onScrollOffsetChange ={ offset => console.log(offset)}

try to scroll to the end of the list, it will print offset infinitely.

**Comment by computerjazz** [comment]
Can you provide a repro snack? I am not seeing this behavior.
