### ISSUE TITLE
Improve speed

### ISSUE THREAD

**Issue by GreDiSe** [computerjazz/react-native-draggable-flatlist#178]
Hi, sorry so this, but I have a question?

I am newcomer in your community, and I liked the features of this library.
In my app I don't need to wait second before drag&drop turning on. How can I remove this delay?

Thanks.

**Comment by aleksandarbos** [comment]
so if you copied over the example https://github.com/computerjazz/react-native-draggable-flatlist#example just like i did, note that 
`onLongPress={drag}` line which is registered per each `TouchableOpacity` in `renderItem` function.

you can assign drag to some other handler like `onPressIn` like described in here https://github.com/computerjazz/react-native-draggable-flatlist/issues/271#issuecomment-803639979 and set the delay which suits you the best :)

if you want no delay then handler would look like `onPressIn={drag}` but that would probably make the most sense if scroll was disabled within `DraggableFlatList`
```
              <DraggableFlatList
                data={valuesData}
                scrollEnabled={false}
                ...
```
