### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by rogueturnip** [computerjazz/react-native-draggable-flatlist#18]
Hi all,
So this module appears to work really well in iOS but I'm getting the following crash on android.
com.facebook.react.bridge.ReadableNativeMap.getValue
ReadableNativeMap.java - line 122
com.facebook.react.bridge.NoSuchKeyException: translateY

Anyone else?  Ideas?  It happens the moment I long click the item I want to move.

**Comment by toddpi314** [comment]
Ref: https://github.com/facebook/react-native/issues/19591

Looks like `measureInWindow` and `measure` are both returning nulls in some cases on React-Native 0.57 (which i'm on over here)

**Comment by toddpi314** [comment]
Confirmed fixed if you add `onLayout={() => null}` to the wrapper view at https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/index.js#L343

Looks like this is already patched on master: https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/index.js#L344-L346
