### ISSUE TITLE
List item appears to lose state on drag

### ISSUE THREAD

**Issue by skidave** [computerjazz/react-native-draggable-flatlist#180]
**Describe the bug**
I have a list of sliders that I want to reorder. 
The drag to reorder works, however on drag the slider component appears to lose its current state and revert to its initial state. i.e. I've set the slider to 5, on drag it goes back to 1, then to 5 on release.
I've reproduced it in the snack below, and I've attached screen shots.

**To Reproduce**
https://snack.expo.io/@skidave/draggablelist-bug

**Platform & Dependencies**
 - Platform: iOS and Android
 - React Native or Expo version: Expo 37.0.1
 - Reanimated version: 1.7.0
 - React Native Gesture Handler version: 1.6.0
 - @react-native-community/slider: 2.0.9,

![Asset 1](https://user-images.githubusercontent.com/13379259/81953709-e9cdd000-95ff-11ea-9db6-f09b383062df.png)

**Comment by computerjazz** [comment]
Right, this component works by creating a copy of the list item that is visible on drag, which is why it loses local state. I'll have to investigate whether it works to use the node itself instead of the copy.

**Comment by skidave** [comment]
That makes sense. Thank you for investigating.

**Comment by samaneh-kamalian** [comment]
Hi. I have a same problem. in each row I have a swipeRow that in the bottom layer I have a time Interval that compute a number in each 30 seconds.
when I drag one Item or delete it, computational parameters are mixed and return error.

**Comment by computerjazz** [comment]
this will be fixed in an upcoming version: https://github.com/computerjazz/react-native-draggable-flatlist/pull/281
