### ISSUE TITLE
Peer dependencies issue

### ISSUE THREAD

**Issue by Albinzr** [computerjazz/react-native-draggable-flatlist#182]
After npm install react-native-draggable-flatlist getting this issue

> react-native-draggable-flatlist@2.3.3 requires a peer of react-native-reanimated@^1.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by curiousdustin** [comment]
Have you installed `react-native-reanimated`? What version?

**Comment by Albinzr** [comment]
Should it have auto installed?

**Comment by curiousdustin** [comment]
No. It is a peer dependency. Thus the message: 

> You must install peer dependencies yourself.

**Comment by Albinzr** [comment]
Cool thanks.
