### ISSUE TITLE
Custom view instead of spacer

### ISSUE THREAD

**Issue by malashkevich** [computerjazz/react-native-draggable-flatlist#185]
**Is your feature request related to a problem? Please describe.**
Is it possible to render some custom view at the spacer? It would be nice to have such feature. The example is on the image below (taken from [here](https://dribbble.com/shots/3336590--18-3-Drag-Drop))
![image](https://user-images.githubusercontent.com/1452064/82588658-cd073e80-9ba3-11ea-87b0-fdf131e002fb.png)

**Describe the solution you'd like**
I would say it could be done the same way as renderItem

**Describe alternatives you've considered**
I've tried to relate on `isActive`, but the full item is rendered on top, so there is no way to do this.

If you can suggest how to implement this I could try to create PR. But it would be nice to have some suggestions/hints.

**Comment by computerjazz** [comment]
what would happen when the spacer index changes as you drag? Would the custom view animate/translate to the new spacer index?

**Comment by malashkevich** [comment]
Yes, it could be just animation/translation between spacer and row item. Currently it animates leaving free space there.

**Comment by computerjazz** [comment]
Whoops sorry for the delayed response. 
I took a stab at implementing this -- would be great to get a test in before merging:
https://github.com/computerjazz/react-native-draggable-flatlist/pull/208

snack with the new code dropped in:
https://snack.expo.io/@computerjazz/renderplaceholder

**Comment by malashkevich** [comment]
@computerjazz well done! Looks really good.
