### ISSUE TITLE
'onRef' inyecting null ref on event handler

### ISSUE THREAD

**Issue by mcama** [computerjazz/react-native-draggable-flatlist#186]
**Issue**

Hi there! The `onRef` event's handler is inyecting `null` ref (`{ current: null }`) when mounting the `<DraggableFlatList />` component. Any ideas why could this be?

Here's my code:
```
<DraggableFlatList
    onRef={ref => {
	alert(JSON.stringify(ref));
    }} ... />
```

**Platform & Dependencies**
 - Platform: Android
 - React Native: 0.61.5
 - Reanimated version: 1.8.0
 - React Native Gesture Handler version: 1.6.1

Thanks in advance for your help.

**Comment by computerjazz** [comment]
Refs are always null on first render -- there's no backing element until the component has mounted. Typically you'd do any ref-based logic in `componentDidMount` or equivalent.

Is the ref correctly populated once mounted?

**Comment by terrorpixel** [comment]
> **Issue**
> 
> Hi there! The `onRef` event's handler is inyecting `null` ref (`{ current: null }`) when mounting the `<DraggableFlatList />` component. Any ideas why could this be?
> 
> Here's my code:
> 
> ```
> <DraggableFlatList
>     onRef={ref => {
> 	alert(JSON.stringify(ref));
>     }} ... />
> ```
> 
> **Platform & Dependencies**
> 
> * Platform: Android
> * React Native: 0.61.5
> * Reanimated version: 1.8.0
> * React Native Gesture Handler version: 1.6.1
> 
> Thanks in advance for your help.

I have the same probem :/

**Comment by mcama** [comment]
> Refs are always null on first render -- there's no backing element until the component has mounted. Typically you'd do any ref-based logic in `componentDidMount` or equivalent.
> 
> Is the ref correctly populated once mounted?

Thanks for answering! Nope. As @terrorpixel points out, we are getting a null ref everytime. 

By the way, I'm using version 2.3.2 of the plugin.

**Comment by computerjazz** [comment]
@mcama are you sure about that?

I just did a quick hacky check by logging the ref in a `setTimeout` and I see the populated ref:
```tsx
          onRef={ref => { 
            console.log("initial ref", ref.current)
            setTimeout(() => console.log("timeout ref", ref))
          }}
```

**Comment by terrorpixel** [comment]
Now it's working! 🎉 

```JavaScript
<DraggableFlatList
   onRef={ ref => { exampleRef = ref }} 
   />

// somewhere else
exampleRef.current._component.scrollToOffset({offset: 100, animated: true});
```
(Functional component)

My fault was to define exampleRef as a ref in addition by this line:
```JavaScript
let exampleRef = React.useRef(); // don't use that
```
In that case exampleRef just persists "null". Sorry, I'm a rookie :neckbeard:

**Comment by mcama** [comment]
The issue was in fact a mistake in my code too... My bad! Thanks for your feedback @terrorpixel and thanks @computerjazz for this awesome plugin.

**Comment by eric-om** [comment]
@terrorpixel could you explain why you don't have to declare exampleRef before onRef?
