### ISSUE TITLE
[Question] How can I handle on drag item style?

### ISSUE THREAD

**Issue by NelsonPRSousa** [computerjazz/react-native-draggable-flatlist#187]
**Is your feature request related to a problem? Please describe.**
It will be a feature request if isn't currently possible to do. But first, I'd like to ask if it's possible with current properties (there's no section here - only feature request or bug report).

**Describe the solution you'd like**
I'd like to style how the item I'm dragging is styled. Right now it is ignoring the FlatList properties and I didn't find a way to deny that behaviour.

**Describe alternatives you've considered**
I've read the documentation but didn't found what is causing the current behaviour.

**Additional context**
This is my DraggableFlatList:
![image](https://user-images.githubusercontent.com/8364345/83363804-32251600-a394-11ea-88b8-bd71fe58007b.png)

This is how the item is styled when I press it to drag it:
![image](https://user-images.githubusercontent.com/8364345/83363814-54b72f00-a394-11ea-983b-58b9e800c536.png)

As you can see, is looks like the item is ignoring the styling that I applied to my DraggableFlatList:
```javascript
<DraggableFlatList
	data={pointsOfInterest}
	extraData={pointsOfInterest}
	showsVerticalScrollIndicator={false}
	contentContainerStyle={{
		backgroundColor: theme.colors.WHITE,
		paddingTop: theme.mixins.widthPercentageToDP(4),
		paddingHorizontal: theme.mixins.widthPercentageToDP(4),
	}}
	renderItem={renderItem}
	keyExtractor={keyExtractor}
	onDragEnd={onDragEnd}
	activationDistance={30}
	autoscrollSpeed={200}
/>
```

I also tried using the same properties with style props but the behaviour is the same. Thank you 🚀

**Comment by NelsonPRSousa** [comment]
Edit: I solved it by adding the paddingHorizontal to the item component instead of FlatList.

@computerjazz If this is what is expecting from the library, feel free to close the issue. Thank you 👍

**Comment by computerjazz** [comment]
I'll need to see a more complete example to know for sure, but yes, styling of the active list item is meant to be handled by the item itself.
