### ISSUE TITLE
refreshControl breaks regular scrolling on Android

### ISSUE THREAD

**Issue by aabraamyan** [computerjazz/react-native-draggable-flatlist#189]
**Describe the bug**
When **refreshControl** is added to DraggableFlatList, the regular scrolling of the FlatList on Android is disabled.

You are able to pull down to trigger the refresh control. However, you are not able to scroll up to see items lower in the FlatList.

The actually dragging is also very difficult and often interferes with the refresh control.

**If you replace DraggableFlatList with a regular FlatList**, scrolling works as expected.

**To Reproduce**
**Snack:** https://snack.expo.io/@aabraamyan/85b993

**Platform & Dependencies**
 - Platform: Android

**Additional context**
This problem is only happening on Android.

**Comment by computerjazz** [comment]
dupllictae https://github.com/computerjazz/react-native-draggable-flatlist/issues/135
