### ISSUE TITLE
Animated: `useNativeDriver` was not specified.

### ISSUE THREAD

**Issue by pistou** [computerjazz/react-native-draggable-flatlist#191]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**
Each time I implement this library, I have a warning in the console:

> Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false` 
    in SortableFlatList 

**To Reproduce**
-

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: iOS
 - React Native or Expo version: 0.62.2
 - Reanimated version: 1.8.0
 - React Native Gesture Handler version: 1.5.3

**Additional context**
-

**Comment by computerjazz** [comment]
Which `react-native-draggable-flatlist` version are you on?

**Comment by emcee22** [comment]
It happens for me in the current version: `2.3.3`

**Comment by creambyemute** [comment]
@computerjazz I think it's a new requirement in the animated api to always specify useNativeDriver to be either false or true.

@emcee22 Which react-native version are you on? I'm on 0.61.5 and not facing this problem. Did you upgrade to 0.62?
According to https://github.com/react-native-community/releases/blob/master/CHANGELOG.md it's a change in 0.62

**Comment by computerjazz** [comment]
@pistou appears to be using v1 of this package, which hasn't been updated in a long time. The component hasn't been named `SortableFlatList` in a while. Also, this package doesn't use `react-native` Animated anymore -- it now uses `react-native-reanimated`.

@emcee22 is it possible you're using React Native Animated somewhere else in your app?
