### ISSUE TITLE
Draggable flatlist doesn't check if item moved out of bounds

### ISSUE THREAD

**Issue by Inomezi** [computerjazz/react-native-draggable-flatlist#199]
Hi, when i dragging item - it doesn't check condition if item is in out of bounds and give a chance move item above or below list

**To Reproduce**
```js
<View style={{ flex: 1 }}>
        <DraggableFlatList
          onDragBegin={() => ReactNativeHapticFeedback.trigger("impactMedium", haptic_options)}
          style={styles.exercise_list}
          data={creation_training_store.exercises}
          ItemSeparatorComponent={ItemSeparator}
          renderItem={({ item, drag }) => {
            const TrainingIcon = TrainingIcons[item.icon]
            return (
              <Exercise
                title={item.name}
                icon={<TrainingIcon height="50%" width="50%" />}
                remove_exercise={() => remove_exercise(item.name)}
                edit_exercise={() => edit_exercise(item.name)}
                drag={drag}
              />
            )
          }}
          onDragEnd={({ data }) => creation_training_store.set_exercises(data)}
          keyExtractor={(item) => item.name}
          getItemLayout={(data, index) => (
            { length: ExerciseRowHeight, offset: ExerciseRowHeight * index, index }
          )}
        />
      </View>
```

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: IOS
 - React Native: 0.62.2
 - Reanimated version: 1.9.0
 - React Native Gesture Handler version: 1.6.1

**Comment by kurnal** [comment]
same issue here don't know how to remedy it it's making the component unusable

**Comment by Richrosh3** [comment]
Having the same issue as the ones described above. The boundaries of the DraggableFlatList become non-existent once I start dragging items to the top or bottom

**Comment by JramR7** [comment]
Hey guys, any workoround on this?

**Comment by Maddumage** [comment]
I am having the same issue. Any solution?

**Comment by creambyemute** [comment]
@Maddumage  @JramR7  @Richrosh3  @kurnal  @Inomezi  Did you guys try updating? 
This it not happening for me anymore with the newest RN-Draggable-Flatlist + RN-Gensture-Handler + RN-Reanimated versions. Worth a shot!

**Comment by Yandamuri** [comment]
@creambyemute As of posting this comment, I am using latest version of RN-Draggable-Flatlist + RN-Gensture-Handler + RN-Reanimated. But Still I am facing this issue. Any solution for this?

**Comment by Maddumage** [comment]
@creambyemute I have updated to the latest one. but still having the issue.

**Comment by computerjazz** [comment]
fixed via https://github.com/computerjazz/react-native-draggable-flatlist/pull/211
