### ISSUE TITLE
Horizontal flatlist support?

### ISSUE THREAD

**Issue by ilyausorov** [computerjazz/react-native-draggable-flatlist#2]
Would it be possible to also expose support for horizontal FlatLists? Thanks!

**Comment by computerjazz** [comment]
All the positioning calculations are based on `y` positions and vertical offsets, so it would take a bit of work to convert those to `x` and calculate horizontal offsets. I don't have plans to tackle that at the moment.

**Comment by ilyausorov** [comment]
Hey @computerjazz , so I actually messed it up and got it to work for horizontal. Basically replaced all the Y's for X's and all the heights for widths, and added a flexDirection: 'row' to the main view of the RowItem so that it renders the spacing horizontally. Happy to share that with you or fork your repo and put it up. What do you prefer?

**Comment by batjko** [comment]
@computerjazz Sounds like a PR on this repo would be perfect, perhaps simply by adding a `direction="horizontal"` prop, which then simply uses your version?

**Comment by computerjazz** [comment]
@ilyausorov I'd love to see what you did to get it working. If it's as easy as replacing a few variables with ternary statements I'd go that route: `const someOffset = horizontal ? pos.x : pos.y`. I don't want to split this into two separate components as that'd be a maintenance headache.

**Comment by computerjazz** [comment]
@ilyausorov thanks for that, I used your changes as a reference and updated the component to support horizontal lists in 1.1.0

**Comment by ilyausorov** [comment]
Awesome, thanks man! I'll take the one on my profile down.
