### ISSUE TITLE
Drag-and-Drop not working on Android (RN 0.57.0)

### ISSUE THREAD

**Issue by websurgeon** [computerjazz/react-native-draggable-flatlist#20]
# Issue

Item dragging functionality does not work on Android for RN 0.57.0

This is not an issue on react-native <= 0.56.0

Thanks to computerjazz and contributors for making this a very useful component.
I hope a solution can be found soon. 

If I find the cause of this issue I'll provide a PR a.s.a.p.

# Expected behaviour

Item spacer should appear and move between items when an item is being dragged.
Releasing the dragged item should drop it onto the spacer location.

# Actual behaviour

Works as expected on iOS but on Android the spacer does not appear and the dragged item (which is removed from the list) hovers over other items but is just left wherever it is dropped.
On attempting to drag another item, the initially dropped item (that was left overlapping other items) jumps to the new drag location and becomes the currently dragged item (as if the previous drag-and-drop never completed).

I have confirmed this issue exists for emulators and devices.

# Environment being tested on:

This was tested with a clean 'react-native init MyApp --version 0.57.0' generated project. Replacing App.js code with the [Example](https://github.com/computerjazz/react-native-draggable-flatlist#example) code.

$ react-native info

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
      Memory: 37.84 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.9.4 - ~/.nvm/versions/node/v8.11.3/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2
        API Levels: 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by computerjazz** [comment]
released in 1.1.5
