### ISSUE TITLE
Does this library support grid ? 

### ISSUE THREAD

**Issue by eraldoforgoli** [computerjazz/react-native-draggable-flatlist#201]
Hello, i am trying to use this library to drag and drop elements in a grid flat list (`numColumns={3}`), 
but it does not seem to work. The drag and drop only works vertically, but not horizontally.
Does this library work with grid flatlist ?

**Comment by computerjazz** [comment]
nope, not supported

**Comment by lakshyastech** [comment]
@eraldoforgoli Did you find any solution?
