### ISSUE TITLE
Does this works for Flatlist of 2 or more columns?

### ISSUE THREAD

**Issue by felire** [computerjazz/react-native-draggable-flatlist#204]
Nothing else. I want to know if this works for Flatlist with two, three or more columns

**Comment by computerjazz** [comment]
no. may add in the future, but it would likely require a pretty hefty rewrite

**Comment by emclab** [comment]
multiple columns will be a great feature. There is no one else (draggable list?grid) is as popular as this module, or even close. Multiple columns will certainly increase its adoption.

**Comment by lyseiha** [comment]
anything update yet?

**Comment by khushal87** [comment]
Any update on this?

**Comment by hwhh** [comment]
Would also like this :)

**Comment by VukMNE** [comment]
Just wanted to check if there would be an update
