### ISSUE TITLE
 TypeError:proxy object's 'set' trap returned falsy value for property '_val'

### ISSUE THREAD

**Issue by leoabacade** [computerjazz/react-native-draggable-flatlist#207]
I can't reproduce the sample script, it returned TypeError as below, anyone knows what is this going on?

<img width="396" alt="截圖 2020-07-24 下午3 04 30" src="https://user-images.githubusercontent.com/2664504/88368088-dee1a980-cdbf-11ea-86a2-4d59ae9eab41.png">

**『 environment 』 :**

 "name": "*",
  "version": "0.0.1",
  "description": "**",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/creativetimofficial/argon-react-native.git"
  },
  "dependencies": {
    "expo": "^36.0.2",
    "expo-asset": "~8.0.0",
    "expo-barcode-scanner": "~8.0.0",
    "expo-calendar": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-facebook": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-image-manipulator": "~8.0.0",
    "expo-image-picker": "~8.0.1",
    "expo-localization": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "expo-sqlite": "~8.0.0",
    "galio-framework": "^0.6.3",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-autolink": "^3.0.0",
    "react-native-draggable-flatlist": "^2.3.6",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-qrcode-svg": "^6.0.3",
    "react-native-svg": "9.13.3",
    "react-navigation": "^3.11.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "react-native-reanimated": "~1.4.0"
  },

**『 sample script 』:** 

import React, { Component } from "react";
import { View, TouchableOpacity, Text } from "react-native";
import DraggableFlatList from "react-native-draggable-flatlist";

const exampleData = [...Array(20)].map((d, index) => ({
  key: `item-${index}`, // For example only -- don't use index as your key!
  label: index,
  backgroundColor: `rgb(${Math.floor(Math.random() * 255)}, ${index *
    5}, ${132})`
}));

class Example extends Component {
  state = {
    data: exampleData
  };

  renderItem = ({ item, index, drag, isActive }) => {
    return (
      <TouchableOpacity
        style={{
          height: 100,
          backgroundColor: isActive ? "blue" : item.backgroundColor,
          alignItems: "center",
          justifyContent: "center"
        }}
        onLongPress={drag}
      >
        <Text
          style={{
            fontWeight: "bold",
            color: "white",
            fontSize: 32
          }}
        >
          {item.label}
        </Text>
      </TouchableOpacity>
    );
  };

  render() {
    return (
      <View style={{ flex: 1 }}>
        <DraggableFlatList
          data={this.state.data}
          renderItem={this.renderItem}
          keyExtractor={(item, index) => `draggable-item-${item.key}`}
          onDragEnd={({ data }) => this.setState({ data })}
        />
      </View>
    );
  }
}

export default Example;

**Comment by lededje** [comment]
After adding the package be sure to recompile the application.

Also use backticks to format your code when providing examples.

**Comment by TaylorWizard** [comment]
the same to me
