### ISSUE TITLE
Able to drag items outside of the view Containing the DraggableFlatList

### ISSUE THREAD

**Issue by Richrosh3** [computerjazz/react-native-draggable-flatlist#210]
When dragging an item to the top or bottom of the DraggableFlatList, the item is able to be dragged past the View Component containing the DraggableFlatlist. Functionally it works properly, however the UI looks really bad. 

<img width="538" alt="Screen Shot 2020-07-28 at 1 29 54 PM 1" src="https://user-images.githubusercontent.com/44792204/88700607-ef9f6180-d0d6-11ea-9276-14cbeda88110.png">

As you can see in this image, the goldfish is able to move past where it says "McKeldin Mall (Location Label)". The View that contains the Draggable Component is located directly under the "McKeldin Mall (Location Label)" text and ends at the red bar above "Chained Blocks", so this should not be happening.

**Comment by arjungandhi521** [comment]
@computerjazz This issue still seems to exist even with these changes to the index file.

**Comment by computerjazz** [comment]
@arjungandhi521 this package is built so you won't see the changes just by replacing the `.tsx` file -- you'll have to either rebuild or point `"main"` in  `package.json` to `src/index.tsx` -- have you done either of those?

**Comment by arjungandhi521** [comment]
@computerjazz What do you mean by rebuild, like just rebuilding the app in Xcode and restarting my metro bundler (I have tried this)?

**Comment by computerjazz** [comment]
I mean rebuild the typescript -- you'll have to `cd` into `node_modules/react-native-draggable-flatlist`, run `yarn`, then `yarn tsc`

That should build the typescript files into the exported `index.js`.
Or you could just modify `package.json` as described above.

 Note that this is just to verify that it works and will be wiped out on next node modules install -- the actual changes will be included in the next release.

**Comment by arjungandhi521** [comment]
@computerjazz So after changing my `package.json `I get this error in my simulator. (I changed that line to "`main": "src/index.tsx`",)
Error: Parameter mismatch when calling reanimated function. Expected 25 parameters, got 26.

```
This error is located at:
    in CellRenderer (at VirtualizedList.js:767)
    in RCTScrollContentView (at ScrollView.js:1038)
    in RCTScrollView (at ScrollView.js:1178)
    in ScrollView (at createNativeWrapper.js:47)
    in NativeViewGestureHandler (at createNativeWrapper.js:46)
    in ComponentWrapper (at GestureComponents.js:52)
    in VirtualizedList (at FlatList.js:676)
    in FlatList (at GestureComponents.js:49)
    in ForwardRef (at createAnimatedComponent.js:233)
    in AnimatedComponent(Component) (at src/index.tsx:980)
    in RCTView (at createAnimatedComponent.js:233)
    in AnimatedComponent(Component) (at src/index.tsx:973)
    in PanGestureHandler (at src/index.tsx:967)
    in DraggableFlatList (at redbar.js:134)
    in RCTView (at redbar.js:133)
    in RCTView (at redbar.js:110)
    in RCTView (at redbar.js:214)
    in RCTView (at redbar.js:190)
    in RCTView (at redbar.js:189)
    in RedBar (created by SceneView)
    in SceneView (at StackViewLayout.tsx:900)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at src/index.native.js:103)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:975)
    in RCTView (at src/index.native.js:134)
    in ScreenContainer (at StackViewLayout.tsx:384)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:374)
    in PanGestureHandler (at StackViewLayout.tsx:367)
    in StackViewLayout (created by withOrientation)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (created by Navigator)
    in Navigator (created by KeyboardAwareNavigator)
    in KeyboardAwareNavigator (created by NavigationContainer)
    in NavigationContainer (at memley-se/index.js:117)
    in Provider (at memley-se/index.js:116)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)
```

```
<anonymous>
    AnimatedFunction.js:44:8
DraggableFlatList#setCellData
    index.tsx:433:39
DraggableFlatList#renderItem
    index.tsx:852:64
CellRenderer#render
    VirtualizedList.js:1895:6
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
callFunctionReturnFlushedQueue
    [native code]:0
```

Then I tried to restore my `package.json` to what main originally points to and tried the other option you said. `yarn` works fine but `yarn tsc` gives me this. Note: the only place in my project where `react-native-reanimated` is used is in the draggable flatlist node module.

```
`arjunkumargandhi@Arjuns-MacBook-Pro react-native-draggable-flatlist % yarn tsc                          
yarn run v1.22.4
warning ../../package.json: No license field
node_modules/react-native-reanimated/react-native-reanimated.d.ts:237:36 - error TS2314: Generic type 'Adaptable' requires 1 type argument(s).

237     export function proc<A extends Adaptable[]>(
                                       ~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
```

**Comment by Maddumage** [comment]
@computerjazz  Is this fixed? What is the solutions? I also getting this

**Comment by computerjazz** [comment]
@Maddumage try upgrading to version 2.4.0
