### ISSUE TITLE
onPress event not getting triggered in Android

### ISSUE THREAD

**Issue by slenin** [computerjazz/react-native-draggable-flatlist#213]
Hi,

I am using the latest version with Expo

    "react-native-draggable-flatlist": "^2.3.6",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.9.0",

Repro:
I simply copy-pasted the Example code and tried to log the onPress event of TouchableOpacity item. When the item is pressed, onPress fires in iOS but not in Android. onLongPress, onPressIn and onPressOut works in both.

**Comment by computerjazz** [comment]
strange, that was an issue pre-2.3.0 (https://github.com/computerjazz/react-native-draggable-flatlist/releases/tag/v2.3.0), but I haven't seen it since. I just tested via a snack and onPress works:
https://snack.expo.io/@computerjazz/da7cf6

**Comment by slenin** [comment]
Thanks for the response. Expo client on the Android device did not properly refresh from the old version (2.2.0), which I was testing before.
