### ISSUE TITLE
Dragging of new item starts at the offset of previous moved item during fast reordering (since v2.3.0)

### ISSUE THREAD

**Issue by slenin** [computerjazz/react-native-draggable-flatlist#214]
**Describe the bug**
I have a scenario where users try to rearrange a list as fast as they can. So the drag method is attached to onPressIn and the restSpeedThreshold and restDisplacementThreshold in the animation config are set to a high value. The ability to quickly rearrange items works great in v2.2.0.

Since v2.3.x, there is an issue: When the interaction on an item starts with a swipe (instead of press and swipe), which is a common case when users are interacting fast, the item jumps to the location of the previous item that was moved. The drag starts from there.

I have a video of it here.
https://drive.google.com/file/d/1_nwl8Kov_L_NI8-gbSPnBDeO-B1XSTsJ/view?usp=sharing

**To Reproduce**
Here is a simple example: 
https://snack.expo.io/@slenin/draggable-flatlist-test

It takes the example code
- Drag method is attached to onPressIn
- Number of items to changed to 5 instead of 20
- scrollEnabled is set to false

I can easily repro it in a iOS and Android device as well.

**Comment by mtalhagaoglu** [comment]
i think i have same problem with you. my situtation like this:
default order => 1 2 3 4 5 6 7
when i longPress to 1 and drag to end it works good
new order => 2 3 4 5 6 7 1
but if i longPress 1, it starts dragging from previous position (top of the list) even my finger still on current (end of the list) position.

**Comment by CaioQuirinoMedeiros** [comment]
Same here. I would be happy to downgrade to v2.2, but there I get the _onPress_ bug, which is even worse 😅.
Does anyone have a workaround for this issue?

**Comment by bradbumbalough** [comment]
I've been having this exact issue too -- I had no idea what was going on. Thank you for posting the steps to reproduce. Do we have any idea what was the change from 2.2 -> 2.3?

**Comment by computerjazz** [comment]
please try `v2.5.3` and let me know if it's fixed

**Comment by joluet** [comment]
I still see this issue in version `2.5.3`. Only in version `2.2.0` it's fine.

**Comment by indvinoth** [comment]
Hi @computerjazz ,

I am still facing this issue in iOS, I tried in both 2.5.3 and 2.5.4
