### ISSUE TITLE
Android instruction link not working

### ISSUE THREAD

**Issue by gokulbalaji16** [computerjazz/react-native-draggable-flatlist#215]
Android instruction link not working 

https://docs.swmansion.com/react-native-gesture-handler/docs/getting-started.html#android

**Comment by daiboss** [comment]
same issue

**Comment by computerjazz** [comment]
fixed in https://github.com/computerjazz/react-native-draggable-flatlist/commit/36199261ebeb2c06e281af09d3aa404be1211282
