### ISSUE TITLE
Exclude element todrag

### ISSUE THREAD

**Issue by TechSupportPlugnotes** [computerjazz/react-native-draggable-flatlist#217]
**Is your feature request related to a problem? Please describe.**
Hi,i like your plugins, i have just an idea because sometimes we ask me to have possibilities to block drag when we reached specifique element in array.

Exemple 

[
{ id : 1, valid : true},
{ id : 2, valid : true},
{ id : 3, valid : true},
{ id : 4, valid : false},
{ id : 5, valid : false},
]
Objectif =>
Drag beetween element 1,2,3 , but if you want to drag element 1 with 4 and 5, i would like to stop this.

Have you and idea to resolve this request ?

**Comment by computerjazz** [comment]
you could combine 4 and 5 into a single list item
