### ISSUE TITLE
[Question] Fix the position of the first block

### ISSUE THREAD

**Issue by wanderbon** [computerjazz/react-native-draggable-flatlist#222]
Hello.
Tell me please, How can I fix the position of the first block (index 0).
It must not move or swap places with other blocks.

Thank you.

**Comment by efec89** [comment]
Add this code begging of render item.
```
    if(index == 0){
      return(<View/>);
    }
```

**Comment by wanderbon** [comment]
> Add this code begging of render item.
I need it to have a normal display, but the position should always be index = 0

**Comment by CKLFish** [comment]
What about splitting the `data` array to `[firstItem, ...restItems]`
and 
```
<DraggableFlatList
...
ListHeaderComponent={/* firstItem's Component */}
data={restItems}
...
/>
```

the `ListHeaderComponent` is from `FlatList`

**Comment by wanderbon** [comment]
> What about splitting the `data` array to `[firstItem, ...restItems]`
> and
> 
> ```
> <DraggableFlatList
> ...
> ListHeaderComponent={/* firstItem's Component */}
> data={restItems}
> ...
> />
> ```
> 
> the `ListHeaderComponent` is from `FlatList`

The first element must have `index = 0` for the rest of the internal logic to work correctly
