### ISSUE TITLE
Prop to set how much to scale on drag?

### ISSUE THREAD

**Issue by tfsjohan** [computerjazz/react-native-draggable-flatlist#225]
Is there a simple way to set how much the dragged item should scale up?

Could not find that in the docs or easily understand from looking at the code. I did see an example, but it look overly complex for a simple thing.

**Comment by computerjazz** [comment]
there's no such thing as "simple" when you're dealing with gesture-based animations 😅

kidding aside, scaling and other implementation-specific styles are out of scope for the core package. 
I may add some wrappers for commonly-requested functionality in the future. In the meantime, here's the example you probably found:
https://gist.github.com/computerjazz/1df4a146bdb260882f52d8d565fd3558
