### ISSUE TITLE
Images flicker 

### ISSUE THREAD

**Issue by gsavvid** [computerjazz/react-native-draggable-flatlist#226]
Everything works fine with the example code but if I replace `<Text>` with `<Image>` (which loads images from local uris), then as soon as the drag ends, the image flickers for a blink of eye. I've only tested it on iOS.

Say I drag item A from index 0 to index 3. As soon as I release, the image from item A will appear first at index 0 and then at index 3. 

I can see that when the dragging ends my component re-renders only once. I also tried wrapping `<Image>` with `useMemo()` without any luck (which is I guess is expected since there are no more than 1 re-renderings anyhow).

Any help would be greatly appreciated.

**Comment by gsavvid** [comment]
Ok, I found the issue. It was a silly mistake using `index` as the `keyExtractor`. Using a unique key solves the problem.

**Comment by bmitioglov** [comment]
I had the same mistake (I used a sample from readme), you saved me @gsavvid !!! thank you!

**Comment by knudcb28** [comment]
I still have this issue, even when using a unique key. 

```
   <DraggableFlatList
        data={factors}
        onDragEnd={handleDragEnd}
        keyExtractor={(item) => item.id}
        renderItem={({ item, drag, isActive }) => (
          <TouchableOpacity
            onLongPress={drag}
            delayLongPress={100}
            disabled={isActive} // Disable long press when item is active
            className="px-[24px] sm:px-[134px]"
          >
            <View
              className={clsx(
                'flex flex-row w-full px-[8px] py-[9px] rounded-[4px] mb-[4px]',
                'justify-between items-start gap-[77px]',
                'border border-[#DEDEDE] dark:border-[#2E2E2E]',
                'bg-white dark:bg-[#1C1C1C]',
              )}
            >
              <View className="flex-row items-center justify-start">
                <ReorderDotsIcon />
                <RWBody className="text-rw-grey-800 text-[10px] dark:text-rw-cloud pl-[10px]">{item.label}</RWBody>
              </View>
              <QuestionMarkIcon />
            </View>
          </TouchableOpacity>
        )}
        ListHeaderComponent={<TitleSection />}
        contentContainerStyle={{ paddingBottom: 100 }}
      />
```

**Comment by petars22** [comment]
Same issue for me...can't get rid of the flicker even with unique key.

**Comment by alexkhazzam** [comment]
@knudcb28 @petars22 have either of you been able to solve the issue? encountered this as well recently and tried a bunch of things...but to no avail

**Comment by mohammedfarzaan** [comment]
i also have the same issue i am testing on an android device and its flickering
