### ISSUE TITLE
I need a draggable list of items in plain View, not a Flatlist

### ISSUE THREAD

**Issue by arnaudambro** [computerjazz/react-native-draggable-flatlist#229]
**Is your feature request related to a problem? Please describe.**
I build a cooking app, where I need some steps to cook my meal, and some ingredients too. Usually, I have between 5 to 15 steps, and 5 to 15 ingredients. When I edit a recipe, I need to be able to move the steps order and/or the ingredients order, therefore I need two draggable lists, on the same parent view, which has to be a `ScrollView`.
When I use this lib, I always have the warning `VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.`, even if I put the `scrollEnabled={false}` prop to the `DraggableFlatList`.

**Describe the solution you'd like**
I wish I could decide if the draggable list is a FlatList or a plain View.

**Describe alternatives you've considered**
I don't know if it is feasible actually...

**Comment by computerjazz** [comment]
Have you tried following the warning and using another virtualized list container as your parent?
This is super hacky, but I'm curious what happens:

```tsx
  <FlatList
    data={["ingredients", "steps" ]}
    renderItem=({ item } => {
      return item === "ingredients" ? <IngredientsDraggableList /> : <StepsDraggableList />
  })
  />

```

**Comment by arnaudambro** [comment]
Thanks for the tip ! I actually never really understood what the warning wanted me to do, you made it clear to me...
So what I did: 
```jsx
 <FlatList
    scrollEnabled={false}
    horizontal
    data={[]}
    ListEmptyComponent=(<DraggableList />)
  />
