### ISSUE TITLE
Getting some warnings during development.

### ISSUE THREAD

**Issue by brunohkbx** [computerjazz/react-native-draggable-flatlist#235]
Hello everyone.
I've been getting some warnings because of this console.log at [line 557](https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/src/index.tsx#L557).
Not a big deal, but there are a few recommendations out there suggesting removing console.log statements when it comes to performance.

Can we remove or disable them? maybe we could use a `DEBUG` var to enable them during development.
I can help to send a PR if you would like.

**Comment by computerjazz** [comment]
👍 there's already a `debug` prop, we can hide the logs behind that: https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/src/index.tsx#L112

a PR would be great
