### ISSUE TITLE
Question: What to use for making a "hovering"/"elevated" effect?

### ISSUE THREAD

**Issue by creambyemute** [computerjazz/react-native-draggable-flatlist#241]
Hey @computerjazz 

I'm a so far a really, really happy user since V1. V2 was a great improvement. Kudos for the incredible library (despite the ScrollView weirdness :D)!

To the question:
I'm trying to make a hover/elevated effect on the ListItem dragged
```
<View style={isActive ? { backgroundColor: Theme.colors.active (very light grey), opacity: 0.9, elevation: 2 } : undefined }>
    <ListItem ...>
</View>
``` 
but it looks kinda weird and not really how I'm used to elevation.

Have you ever done that and have a quick solution? Am I doing it wrong 👍 ?

**Comment by computerjazz** [comment]
yeah you'll have to roll your own hover animations based on the drag state. 
 
Here's an example:
https://snack.expo.io/@computerjazz/5508f3

The short version is: there is a single animated value that is driven by hover state, and whichever item is active uses that animated value to drive its own styles.

![RNDFL-hoverEffect](https://user-images.githubusercontent.com/6730148/97484593-25dac000-1916-11eb-8ccc-2110adaed7f4.gif)
![RNDFL-hoverEffect-android](https://user-images.githubusercontent.com/6730148/97484663-4440bb80-1916-11eb-9423-a69b5f05505a.gif)

**Comment by creambyemute** [comment]
@computerjazz Alright, I'll figure it out then.
