### ISSUE TITLE
Pull to refresh is not working

### ISSUE THREAD

**Issue by dev-sathish** [computerjazz/react-native-draggable-flatlist#242]
**Describe the bug**
Pull to refresh is not working even though using refreshControl. Refresh control prevents draggable-flatlist from scrolling. using two-finger I can able to scroll but that not we need. 

please add support for,
**onRefresh** = {this.PullToRefresh}
**refreshing** = {this.state.iRefreshing}

I have tried for **closed issue** #135 as well but it also not working. 

**Platform & Dependencies**
 - Platform: Android
 - React Native version: 0.59.9
 - Reanimated version: 1.8.0
 - React Native Gesture Handler version:1.6.1

Thanks in advance.

**Comment by dev-sathish** [comment]
Hello All, 

Please use like below those who are not able to handle pull to refresh,

const App = () => {
  const [refreshing, setRefreshing] = React.useState(false);
  const [data,setData] = React.useState(exampleData)
  const onRefresh = React.useCallback(() => {
    setRefreshing(true);
    wait(2000).then(() => setRefreshing(false));
  }, []);

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView
        contentContainerStyle={styles.scrollView}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
        }
      >
      <View style={styles.dragList}>
        <DraggableFlatList
            scrollingContainerOffset={scrollOffset}
            data={data}
            renderItem={renderItem}
            keyExtractor={(item, index) => `draggable-item-${item.key}`}
            onDragEnd={({ data }) => setData(data)}
            />
      </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 20,
  },
  scrollView: {
    flex: 1,
    width: "100%",
    backgroundColor: 'gray',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1
  },
  dragList: {
    width: "90%",
    height: '90%',
    zIndex: 0,
    position: 'absolute',
  }
});

**Comment by Hibbem** [comment]
Did you even try this code? :D you create a variable onRefresh but you never use it..

**Comment by dev-sathish** [comment]
> Did you even try this code? :D you create a variable onRefresh but you never use it..

use inside scroll view refreshcontrol, but this is not working in android. i think there is a gesutre problem. using two finger pull it will invoking the refresh control method, but thats not a good way.

**Comment by gdoudeng** [comment]
@dev-sathish Are you sure this code works?

**Comment by sathishsubramani-2103** [comment]
I'm not sure @gdoudeng. Seems it works in ios.

**Comment by gdoudeng** [comment]
> I'm not sure @gdoudeng. Seems it works in ios.

No problem in iOS, but not working in Android

**Comment by hraschan** [comment]
Same problem. Works on IOS but not on Android

**Comment by minhchinh97h** [comment]
I was able to have `refreshControl` prop working in Android by creating a native wrapper for `RefreshControl`, forcing the `DraggableFlatList`'s underlaid `FlatList` to prioritise the native `RefreshControl` and controlling the `RefreshControl`'s `enabled` prop on with `onDragBegin` & `onDragEnd` handlers to prevent refresh-on-dragging issue (while at the very top of the list). Here's my working version:

````
import React from 'react'
import {RefreshControl} from 'react-native'
import {createNativeWrapper} from 'react-native-gesture-handler'
import DraggableFlatList from 'react-native-draggable-flatlist'

const AndroidRefreshControl = createNativeWrapper(RefreshControl, {
  disallowInterruption: true,
  shouldCancelWhenOutside: false
})

export class MyDraggableList extends React.Component{
 refreshControlRef = React.createRef()

 state = {
  enabled: true
 }

 render(){
   <DraggableFlatList 
     ... 
     onDragBegin={() => {this.setState({enabled: false})}} 
     onDragEnd={() => {this.setState({enabled: true})}}
     waitFor={this.refreshControlRef}
     refreshControl={
      <AndroidRefreshControl
        ...
        ref={this.refreshControlRef}
        enabled={this.state.enabled}
      />
     }
   />
 }
}
````

The original idea of the workaround was from https://github.com/software-mansion/react-native-gesture-handler/issues/1067#issuecomment-898400208.

**Comment by mordechaim** [comment]
❗❗ 

To fix this issue, use the `RefreshControl` component from `react-native-gesture-handler` instead:

```diff
-import { RefreshControl } from 'react-native'
+import { RefreshControl } from 'react-native-gesture-handler'
```

**Comment by Ovodo** [comment]
Thank you @mordechaim , this worked

**Comment by MelihaDuman** [comment]
Thanks a lot @mordechaim. It works now!
