### ISSUE TITLE
Change the drop animation?

### ISSUE THREAD

**Issue by tfsjohan** [computerjazz/react-native-draggable-flatlist#243]
Is it possible to control the speed and animation curve when you are releasing a dragged item?

I'd like to to be a bit softer.

**Comment by computerjazz** [comment]
yep! you can pass your own spring configuration (be sure not to pass in your own `toValue` though):
https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/src/index.tsx#L106
https://github.com/software-mansion/react-native-reanimated/blob/cd0b0e2e682bf668856f4655154f5c7f2bcaa361/react-native-reanimated.d.ts#L133-L138

**Comment by tfsjohan** [comment]
I tried to play around with those values, but it seemed like it only affected how each items is moved? 

I mean when I  drop the dragged item.

**Comment by scaralfred** [comment]
Did you try this?
animationConfig={{ restDisplacementThreshold: 100 }}
The drop animation is very fast with that parm.
