### ISSUE TITLE
Calling getNode() on the ref of an Animated component is no longer necessary

### ISSUE THREAD

**Issue by omarmahili** [computerjazz/react-native-draggable-flatlist#244]
**Describe the bug**
When using DraggableFlatList react-native shows this warning:

> ReactNativeFiberHostComponent: Calling getNode() on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release.

From the stack I can see that it comes from:

> DraggableFlatList: 
> [...]node_modules\react-native-draggable-flatlist\lib\index.js:304:9

**Platform & Dependencies**
 - React Native version: 0.63.2
 - Reanimated version: 2.0.0-alpha.8
 - React Native Gesture Handler version: 1.7.0
 - React Native Draggable FlatList: 2.5.0

**Comment by nelsonprsousa** [comment]
Thanks for opening this issue and for the pull request 🙏

**Comment by leandro-andrade-candido** [comment]
Do you intend to merge this update?

**Comment by omarmahili** [comment]
For anyone getting this warning, you are probably using reanimated v2 instead of v1, which is the actual peer dependency for this library. So to get rid of it use reanimated v1.

**Comment by slavagoreev** [comment]
Author himself decided to just ignore this error:
```tsx
LogBox.ignoreLogs([  "ReactNativeFiberHostComponent: Calling getNode() on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release.",]);
```

You may do this by yourself or try to install the latest version if it includes this commit (there is still no version 2.6.2 in expo installer configs)
![image](https://user-images.githubusercontent.com/4031952/120205706-f0db7680-c232-11eb-83d8-5f486b882e1c.png)
