### ISSUE TITLE
dragHitSlop property wrong data type

### ISSUE THREAD

**Issue by g4rb4g3** [computerjazz/react-native-draggable-flatlist#249]
**Describe the bug**
dragHitSlop is an object not a number

**Additional context**
![image](https://user-images.githubusercontent.com/646435/99970985-e41a2980-2d9c-11eb-8dce-0a275b09f01d.png)

Hello there, you created a nice module here! :+1: 
VS Code is just complaining about wrong type that I pass to the dragHitSlop property.

**Comment by computerjazz** [comment]
thanks! fixed in `2.5.1`

**Comment by g4rb4g3** [comment]
That was quick! Thank you!
