### ISSUE TITLE
Not able to drag in android

### ISSUE THREAD

**Issue by deepaktringapps** [computerjazz/react-native-draggable-flatlist#250]
I have installed react-native-gesture-handler and react-native-reanimated packages,
I have some native implementation available in Main Activity for use some native screens, In the main activity set the content view as follows    

Used react screen as Fragment but all fragment inside the FrameLayout as below

**setContentView(R.layout.activity_welcome);**

layout file is 

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fragment_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>

When commenting the setContentView then able to enable Gesture and dragging the item, But when we use set content view not able to drag also Gesture not recognized

**Platform & Dependencies**
 - Platform: Android
 - React Native or Expo version: 0.62.2
 - react-native-draggable-flatlist : ^2.3.1
 - Reanimated version: ^1.7.1
 - React Native Gesture Handler version: ^1.1.3

Also tried with the latest version Still issue exists, Please help to resolve the problem

**Comment by deepaktringapps** [comment]
I have fixed the issue

import { gestureHandlerRootHOC } from 'react-native-gesture-handler';

use the HOC and wrap with the MainComponent

**Comment by sami3898** [comment]
> I have fixed the issue
> 
> import { gestureHandlerRootHOC } from 'react-native-gesture-handler';
> 
> use the HOC and wrap with the MainComponent

hey can you elaborate example in a bit details

**Comment by deepaktringapps** [comment]
Refer [here](https://docs.swmansion.com/react-native-gesture-handler/docs/#for-library-authors) for using HOC in gesture package

https://docs.swmansion.com/react-native-gesture-handler/docs/#for-library-authors

**Comment by sami3898** [comment]
`<GestureHandlerRootView style={{flex: 1}}>
                  <DraggableFlatList
                    style={{ flex: 1 }}
                    activationDistance={20}
                    data={search != '' ? searchData : data}
                    renderItem={this.renderItem}
                    keyExtractor={item => item.tagId}
                    onDragEnd={({ data }) =>
                      this.dragedItem(data)
                    }
                    extraData={this.state}
                    dragItemOverflow={true}
                  />
                  </GestureHandlerRootView>`

I have used this but I still can't able to drag items 
it's working fine on Android!!!!

**Comment by RicardoBrito1938** [comment]
Hello @sami3898 , did you mange to solve the issue, i am facing the same issue right now

**Comment by deepaktringapps** [comment]
Try like this 

import { gestureHandlerRootHOC } from 'react-native-gesture-handler';

class Test extends Component {
    render() {
        return (
            <DraggableFlatList ... />
        )
    }
}

export default gestureHandlerRootHOC(Test)

**Comment by RicardoBrito1938** [comment]
thanks it worked fine

**Comment by geroale** [comment]
Same issue here. Version 2.5.1 was working fine.

**Comment by stanleycyang** [comment]
Hitting a block, even when trying with `gestureHandlerRootHOC` on expo for Android. Any help on how this was fixed? Works perfectly on iOS. 

Version: 2.5.4

**Comment by 1Jesper1** [comment]
Thanks @deepaktringapps it worked!
