### ISSUE TITLE
Documentation should be updated to note reanimated v2+ incompatibility.

### ISSUE THREAD

**Issue by mikeportanova** [computerjazz/react-native-draggable-flatlist#252]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**
The documentation instructs the reader to follow the reanimated instructions for installation. The reanimated instructions lead the user to installing v2.x. This is incompatible with the package.

**To Reproduce**

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform:
 - React Native or Expo version:
 - Reanimated version:
 - React Native Gesture Handler version:

**Additional context**
Nothing to add really, just a quick change to the readme would help a lot of people out.

**Comment by computerjazz** [comment]
according to the announcement blog post, Reanimated 2 was intended to be 100% backwards compatible. Is this not the case?
>we wanted to assure you that version 2 will be backward compatible with Reanimated 1.x to allow for incremental adoption (you will be able to use the same old API and libraries that depend on it as well as adapt new API in other places of your app)

https://blog.swmansion.com/introducing-reanimated-2-752b913af8b3

**Comment by nelsonprsousa** [comment]
I am using reanimated v2 and this lib is working. Unfortunately is using v1 code, which means we do have some code being sent thro the bridge. But until there's an update to reanimated v2, we will need to live with it as it is!

**Comment by Yandamuri** [comment]
@computerjazz Does it mean that `react-native-draggable-flatlist` is absolutely fine with  `reanimated v 1+`? if so how long can we use this package with `reanimated V1` only?

**Comment by nelsonprsousa** [comment]
> @computerjazz Does it mean that `react-native-draggable-flatlist` is absolutely fine with `reanimated v 1+`? if so how long can we use this package with `reanimated V1` only?

No, this package shouldn't be used with reanimated v2, there's warnings being fired: https://github.com/computerjazz/react-native-draggable-flatlist/issues/244#issuecomment-777841894

**Comment by Yandamuri** [comment]
@nelsonprsousa I just installed `"react-native-reanimated": "1.13.2",`. When I ran the project got following error

> Error: Unable to resolve module `./reanimated2` from `node_modules\react-native-reanimated\src\Animated.js`:

I don't se this error if I install `reanimated V2`. Can you please let me know how can I get rid of this error and what version exactly should I use?

**Comment by Yandamuri** [comment]
After I cleaned the cache issue got resolved
