### ISSUE TITLE
item of list is jumps on LongPress for drag for first time 

### ISSUE THREAD

**Issue by kp72-dev** [computerjazz/react-native-draggable-flatlist#256]
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Memory: 24.75 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    
    
 I dont know but using latest version of dragable flatlist still its jumps and when trying longPress
 
```
  <PlatformTouchable
            onLongPress={item.drag}
          >
            <Image source={Menu_Icon} style={{ height: 20, width: 20,tintColor:'#696969',marginLeft:10}} resizeMode='contain'/>
          </PlatformTouchable>  
```
Issue in android and IOS
@computerjazz

**Comment by computerjazz** [comment]
can you provide a snack? https://snack.expo.io/

**Comment by kp72-dev** [comment]
Thank you for response its solved now.

**Comment by indvinoth** [comment]
Hi @kp72-dev,

Could you please share me the details on how you fixed this issue, I am also facing the same issue.

**Comment by kp72-dev** [comment]
> Hi @kp72-dev,
> 
> Could you please share me the details on how you fixed this issue, I am also facing the same issue.

 import { GestureHandlerRootView } from 'react-native-gesture-handler';
<GestureHandlerRootView style={{ flex: 1 }}>
<App/>
 </GestureHandlerRootView>
