### ISSUE TITLE
Is it possible to decrease the onLongPress touch duration

### ISSUE THREAD

**Issue by Yandamuri** [computerjazz/react-native-draggable-flatlist#257]
Seems like it takes at least one second to activate dragging when user do onLongPress. Is it possible to customize this time?. 

I want to activate this dragging with in less than a second.

**Comment by computerjazz** [comment]
`onLongPress` is a property of the Touchable you're using and is unrelated to this package.

**Comment by systemride** [comment]
FWIW just noting this here in case anyone comes looking for this answer. Touchable components usually have a `delayLongPress` prop, eg:

```
<TouchableOpacity delayLongPress={0} onLongPress={onLongPress} />
```

**Comment by Pau1fitz** [comment]
thanks @systemride and good question @computerjazz  👍
