### ISSUE TITLE
List item is going beyond the list items boundaries 

### ISSUE THREAD

**Issue by Yandamuri** [computerjazz/react-native-draggable-flatlist#258]
**Describe the bug**
My Flatlist contains header component as well. so obviously header renders above the list items. When I try to drag any item up it's going over the header which is out of bounds of list data. I want item to be draggable with in the list items boundary. 

**To Reproduce**
Just render the simple Draggable Flatlist and try to drag any item in the list. Then you can notice that Item is being draggable beyond the bounds of Flatlist

**Platform & Dependencies**.
 - Platform: android
 - React Native version: 0.63.2 
 - Reanimated version: 2.0.0-rc.2
 - React Native Gesture Handler version: 1.9.0

**Comment by computerjazz** [comment]
did you set `dragItemOverflow={false}`?

see props: https://github.com/computerjazz/react-native-draggable-flatlist#props

**Comment by Yandamuri** [comment]
@computerjazz  This props doesn't show any effect.
![Screenshot_1611729850](https://user-images.githubusercontent.com/31983789/105953788-c9647980-6099-11eb-9ff8-6ccb5dc5ea85.png)

I would like to drag an item inside red box only.  Even though said prop is given, item is being dragged beyond the red box. And the content with blue background is single component which is being rendered as Flatlist header. IF I remove `ListHeaderComponent` and render that component as separate component this item is dragged inside the red box only.

So, `dragItemOverflow={false}` doesn't show any effect for me. Am I missing anything here?

**Comment by computerjazz** [comment]
right, i see, no you're not missing anything. we'd need to measure the header size and exclude that area from the draggable area. A workaround would be if your list did not render a header and the actual "header" was a separate component.

**Comment by Yandamuri** [comment]
@computerjazz Thank You for your suggestion. If any plan to implement in future please tag this issue :)
