### ISSUE TITLE
Clarification: Can we able to delete the drag and dropped items

### ISSUE THREAD

**Issue by nihp** [computerjazz/react-native-draggable-flatlist#26]
@computerjazz I need to delete the drag and dropped items. Is there any way to delete the dropped items.

If not kindly add this support.

**Comment by computerjazz** [comment]
You can delete any item by removing it from the `data` array. It's up to you to determine how/when this happens.

**Comment by nihp** [comment]
No I need to delete the dropped item by any close mark indication or any thing. 


Eg: I am rendering lot of images and doing drag and dropping the image. Then I need to delete the dropped image.
