### ISSUE TITLE
Horizontal multiple rows - draggable-flatlist

### ISSUE THREAD

**Issue by Zurdge** [computerjazz/react-native-draggable-flatlist#263]
### Example
![image](https://user-images.githubusercontent.com/10058489/106354406-81d42c80-62e9-11eb-83d4-28e08c8ac356.png)

I'm looking for a solution that will let me reorder an array of items.
react-native-draggable-flatlist looks like it will do the trick however I can't seem to find out how I can get the content to wrap onto multiple rows.  Currently, it creates one long horizontal row.

Does anyone know a solution to this?

**Comment by computerjazz** [comment]
not possible with this library, good luck!

**Comment by lakshyastech** [comment]
@Zurdge Did you find any solution?
