### ISSUE TITLE
Possibility to deny dagged item drop to current placeholder position

### ISSUE THREAD

**Issue by juhanilamma** [computerjazz/react-native-draggable-flatlist#265]
I am asking if it would be possible (or already is, but I have not found how) to give the react-native-draggable-flatlist information during drag if the item can actually be dropped at current position?

One idea would be to have a callback from the list (e.g. onPlaceholderIndexChange), which would return true|false depending if item can be dropped to current placeholder position. If item cannot be dropped in the position, then it'd return (animated) to original position where drag began.

**Comment by sergeymild** [comment]
I ran into the same problem, I really miss this feature

**Comment by computerjazz** [comment]
not on the roadmap, sorry!
