### ISSUE TITLE
What is the recommended version of 'react-native-reanimated' that best suits for react-native-draggable-flatlist

### ISSUE THREAD

**Issue by Yandamuri** [computerjazz/react-native-draggable-flatlist#266]
**Describe the bug**
For this issue [#244 (comment)](https://github.com/computerjazz/react-native-draggable-flatlist/issues/244#issuecomment-777841894) some one suggested to install `reanimated v1` --   Then I installed `reanimated- 1.13.2` then I got following error

> Error: Unable to resolve module ./reanimated2 from node_modules\react-native-reanimated\src\Animated.js:

This error is apparently stating that `reanimated 2` must be installed then I installed - `reanimated": "2.0.0-rc.3"`. Then I got following error

> TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

Even though I followed [this thread](https://github.com/software-mansion/react-native-reanimated/issues/1127) I haven't found a clear solution for this. Here I am not sure about what version of `reanimated `should be installed.

**To Reproduce**
Please install `reanimated `package as I mentioned above. Then you can encounter this error.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: **android**
 - React Native: **0.63.2**
 - Reanimated version: **I tried both "2.0.0-rc.3" and 1.13.2**
 - React Native Gesture Handler version: **"1.9.0"**

**Additional context**
I just want to mention that at some point of time `Draggable Flatlist` worked fine with both `reanimated `versions mentioned above. But all of sudden both versions of package are giving error.

I want to here from package manager that what exact version is suitable to `Draggable Flatlist` and I want same thing to be mentioned in the package documentation.

**Comment by Svarto** [comment]
I suspect your errors are only related to reanimated, and not this library. Go over the installation instructions again for reanimated and make sure to clear your cache before switching between the two - the first error when downgrading from reanimated two is a cache error.

**Comment by Yandamuri** [comment]
@Svarto I agree with you that errors are related to `reanimated `only. But I would like to know the suitable version of `reanimated`. Can you tell me the suitable version if you are using `react-native-draggable-flatlist`?

**Comment by Svarto** [comment]
I have used both reanimated v1.13.2 and reanimated v2.0.0-rc0 with no issues other than a yellow warning for v2, but that could easily be silenced and is already a known issue here in the repo.

**Comment by Yandamuri** [comment]
@Svarto  I have installed  v2.0.0-rc.0. This is also giving same error in command prompt

![Capture](https://user-images.githubusercontent.com/31983789/108664339-8f4f9180-74f8-11eb-9bbe-e8e7f4339100.PNG)

due to which I am unable to proceed for further. Others also getting the same error - [Issue - #1127](https://github.com/software-mansion/react-native-reanimated/issues/1127). But hey are getting this issue when they enabled debug mode. for that some one suggested this [solution ](https://github.com/software-mansion/react-native-reanimated/issues/1127#issuecomment-772868632).But I am getting this error even though I didn't enable debug mode.

Can you please suggest any solution for this?

**Comment by Svarto** [comment]
I would suggest you ask that question in the reanimated repo. From the looks of it you are using the Hermes js engine /turbo modules that reanimated doesn't like that - either due to you not cleaning out cache before startup or it's actually incompatible. I am on expo right now, so don't have experience with reanimated in RN-cli.

**Comment by Yandamuri** [comment]
@Svarto Thank you for your suggestion.
