### ISSUE TITLE
QUESTION:

### ISSUE THREAD

**Issue by lluisemper** [computerjazz/react-native-draggable-flatlist#271]
Is it posible to change the time that it will take the element to become draggable? 
Example: 
- Hold the item 5 seconds and after that the item is draggable
- Hold the item 200 miliseconds to make the item draggable

**Comment by computerjazz** [comment]
sure, it's up to you to decide when the item becomes draggable by calling `drag` -- this package makes no assumptions and provides no implementation for that.

so you could do something like:

```ts
<TouchableOpacity onPressIn={() => setTimeout(drag, 5000)} />
```

```
