### ISSUE TITLE
Dragged item jumps to the top of the list when the drag starts

### ISSUE THREAD

**Issue by heikkimantere** [computerjazz/react-native-draggable-flatlist#275]
**Describe the bug**
An item jumps to the top of the list when the drag starts—with certain conditions. 

**To Reproduce**
Press and hold any item any item to call `onDragBegin`. Drag the item anywhere, and release the item, but _before the animation is completed_ and `onDragRelease` is called—try to swipe the screen up or down (no matter whether or not the screen actually scrolls). Then, press and hold any item again to call `onDragBegin` again, and the item suddenly jumps to the top of the list. 

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: iOS 14.4.2
 - React Native or Expo version: RN 0.63.2, Expo 14.3.4 
 - Reanimated version: 1.13.0, tried with 2.1.0 too
 - React Native Gesture Handler version: 1.10.3 

My `DraggableFlatList` is not inside a ScrollView. It's inside a `SectionList`, but even if I place it inside a `View`, the issue persists. 

Edit: The bug persists with react-native-draggable-flatlist v. 2.6.0. I tried to place my draggable lists inside a ScrollView (from RNGH) and add a `simultaneousHandlers` prop as suggested [here](https://github.com/computerjazz/react-native-draggable-flatlist/pull/273). 

https://user-images.githubusercontent.com/12067936/114315371-5e0e3d80-9b07-11eb-9551-0c1ccd4676c2.mp4

**Comment by heikkimantere** [comment]
The bug doesn't exist with react-native-draggable-flatlist v. 2.2.0, but that version doesn't support the `dragHitSlop` which is needed to be able to scroll the list. Version 2.5.0 introduced that property, and the bug exists with that version, too. 

My `DraggableFlatList` has a prop 
```
dragHitSlop={{ left: -(w - 62)}}
```

to only allow dragging items from the end of the row. Otherwise scrolling the list is not possible. (Which is another issue, for which using `dragHitSlop` is a workaround).

**Comment by computerjazz** [comment]
this was fixed in 2.5.5, but looks like it was accidentally dropped in 2.6.0, will re-add and release 2.6.1
https://github.com/computerjazz/react-native-draggable-flatlist/compare/v2.5.5...v2.6.0#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405L779

**Comment by heikkimantere** [comment]
> edit: done, can you try `2.6.1` and see if this solves your issue @heikkimantere ?

Seems to work, thank you! 😀 

I had an occasional offset bug when using `ListHeaderComponent` and `contentContainerStyle`, but can't reproduce it now... I'll report here if that occurs again.

**Comment by computerjazz** [comment]
if your header changes height you may have to pass a `layoutInvalidationKey` to force remeasurement. https://github.com/computerjazz/react-native-draggable-flatlist/issues/136
