### ISSUE TITLE
Component fails to render altogether (simple example)

### ISSUE THREAD

**Issue by jonlambert** [computerjazz/react-native-draggable-flatlist#279]
**Describe the bug**
Component fails to render altogether when testing with a very basic example 😞

**To Reproduce**

```
<FlatList
  data={['a', 'b', 'c']}
  renderItem={({item}) => <Text>{item}</Text>}
  keyExtractor={(item) => item}
/>
```

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: macOS
 - React Native or Expo version: `react-native@0.63.4`
 - React Navigation: 5.15.1
 - Reanimated version: 2.1.0
 - React Native Gesture Handler version: 1.10.3

**Comment by computerjazz** [comment]
can you post a snack reproduction? 
I can't reproduce your example: 
https://snack.expo.io/@computerjazz/rndfl-simple-repro

see "a b c" along top left edge:
![Screen Shot 2021-04-19 at 9 12 27 ](https://user-images.githubusercontent.com/6730148/115268724-6bbb5880-a0ef-11eb-8dc6-c3589b205437.png)
