### ISSUE TITLE
List disappears on long press

### ISSUE THREAD

**Issue by dquessenberry** [computerjazz/react-native-draggable-flatlist#280]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

All dependencies have been installed with the latest version of each.

**Describe the bug**
Whenever I long press a touchable item, the entire list disappears and dragging does not work properly. I have tested this on a bare bones screen with essentially the same component structure and styling as the example, yet the same issue occurs. 

**To Reproduce**
Link a snack if possible.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: iOS & Android
 - React Native or Expo version:  0.63.4
 - Reanimated version: 2.1.0
 - React Native Gesture Handler version: 1.10.3
 
 - react-native-router-flux: 4.3.1
 - react-native-screens:  2.15.2
 - @react-native-community/masked-view: 0.1.10

**Additional context**
![draggable-list](https://user-images.githubusercontent.com/10273674/115778725-f27c6980-a36b-11eb-8b6b-14af07169606.gif)

**Comment by computerjazz** [comment]
can you share a snack that displays this behavior? I cannot repro.

**Comment by hengkx** [comment]
same problem

**Comment by computerjazz** [comment]
Please post a snack, otherwise I will have to close this issue, as I cannot repro.

**Comment by hengkx** [comment]
my code
```jsx
<View style={{ flex: 1, paddingBottom: insets.bottom }}>
      <SectionHeader title="长按拖拽排序" />
      <DraggableFlatList
        keyExtractor={keyExtractor}
        data={items}
        onDragEnd={({ data }) => handleDragEnd(data)}
        renderItem={({ item, drag }) => (
          <TouchableWithoutFeedback
            onLongPress={() => {
              ReactNativeHapticFeedback.trigger('impactLight');
              drag();
            }}
          >
            <View
              style={{
                flexDirection: 'row',
                alignItems: 'center',
                paddingHorizontal: 15,
                backgroundColor: colors.primaryBg,
                borderBottomWidth: borderWidth,
                borderColor: colors.border,
                height: 50,
              }}
            >
              <Text style={{ color: colors.title, fontSize: 18, flex: 1 }}>
                {featureMap[item.key].title}
              </Text>
              <Switch
                disabled={item.key === 'my'}
                value={item.show}
                onValueChange={val => handleShowChange(item, val)}
              />
            </View>
          </TouchableWithoutFeedback>
        )}
      />
    </View>
```

**Comment by hengkx** [comment]
My fault, my key is not uniq.
