### ISSUE TITLE
Auto scroll not working in local project but works on snack

### ISSUE THREAD

**Issue by KrisLau** [computerjazz/react-native-draggable-flatlist#285]
**Describe the bug**
When dragging an item from the list, auto scroll dos not trigger at all but when I created a snack with the same settings, it worked fine. Snack is linked below.

**To Reproduce**
https://snack.expo.io/@kris_lau/witty-watermelon

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: Android
 - React Native or Expo version: ^0.64.0 (not using expo)
 - Reanimated version: ^2.1.0
 - React Native Gesture Handler version:^1.10.3

all my dependencies:
```
    "@react-native-clipboard/clipboard": "^1.7.0",
    "@react-native-community/datetimepicker": "^3.4.7",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-picker/picker": "^1.15.0",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "@storybook/react": "^6.2.7",
    "html-loader": "^2.1.2",
    "html-webpack-plugin": "^5.3.1",
    "intl": "^1.2.5",
    "lodash": "^4.17.21",
    "react": "^17.0.2",
    "react-native": "^0.64.0",
    "react-native-calendars": "^1.1258.0",
    "react-native-camera": "^3.43.6",
    "react-native-draggable-flatlist": "^2.6.1",
    "react-native-elements": "^3.4.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-google-places-autocomplete": "^2.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "0.28.0",
    "react-native-reanimated": "^2.1.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.1",
    "react-native-swipeable-item": "^1.5.7",
    "react-native-track-player": "^1.2.7",
    "react-native-vector-icons": "^8.1.0",
    "react-native-webview": "^11.4.3",
    "webpack": "^5.32.0",
    "webpack-cli": "^4.6.0",
    "webpack-dev-server": "^3.11.2"
```

**Additional context**
I followed all the steps for the dependencies as well as this library. The only part I didn't follow was enabling hermes in `build.gradle` because it crashed my application.

**Comment by computerjazz** [comment]
hm i'm not sure how to respond, since the snack works as expected, sounds like the issue is within your app.

Keep in mind that autoscroll will only work if the draggable flatlist container is smaller than the screen height. For example, if your list is nested in a scrollview and is allowed to expand however tall it wants, it will never autoscroll, since it cannot "know" that the drag has reached the boundary.

**Comment by computerjazz** [comment]
ah! this is probably due to this issue: https://github.com/computerjazz/react-native-draggable-flatlist/issues/283
please try the latest version: https://github.com/computerjazz/react-native-draggable-flatlist/releases/tag/v2.6.2

**Comment by KrisLau** [comment]
Thanks for helping to look into it! I tried upgrading and that didn't seem to fix it either unfortunately and I really have no either what might be causing the issue either haha. Sometimes it does a little stutter as if its trying to scroll but nothing happens after that. Everything else about the library seems to be working so it's really strange. I really appreciate you looking into it though!

**Comment by KrisLau** [comment]
Not sure what caused it but I created a repo with the exact same settings and libraries which seems to have fixed it (albeit with very slow scrolling haha)

**Comment by gabriellend** [comment]
> Keep in mind that autoscroll will only work if the draggable flatlist container is smaller than the screen height. For example, if your list is nested in a scrollview and is allowed to expand however tall it wants, it will never autoscroll, since it cannot "know" that the drag has reached the boundary.

@computerjazz  Curious what you mean here as I'm having this issue with DraggableFlatlists inside a FlatList. It sounds like "if the draggable flatlist container is smaller than the screen height", you wouldn't need to auto scroll in the first place so I'm confused. Isn't the point of auto scroll that the list extends beyond the screen and you might need to drag the top item to the very bottom? Thanks in advance!
