### ISSUE TITLE
Changing the height of an item adds an offset when dragging items below

### ISSUE THREAD

**Issue by MarioUnlam** [computerjazz/react-native-draggable-flatlist#286]
I have a list of items that have dynamic height. Dragging them around works fine the first render, but if one of them changes the height, all the items below start having an offset when I try to drag them. I've seen this bug reported a few times here, but most people said they solved it by updating the plugin, removing a parent ScrollView, or installing react-native-draggable-dynamic-flatlist. I have the latest plugin version, my page (using react-navigation) doesn't have any ScrollView, and installing react-native-draggable-dynamic-flatlist is not an option, that plugin is outdated and buggy. Is there a way to force the plugin to recalculate dimensions?

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: Android 10
 - React Native or Expo version: React Native (CLI) 0.63.2
 - Reanimated version: 1.13.3
 - React Native Gesture Handler version: 1.10.3

**Comment by MarioUnlam** [comment]
I just noticed there's a prop called layoutInvalidationKey. It recalculates item heights when the string changes. Sadly, I can't do that right before starting to drag, so I'll need to recalculate when the size change happens. Maybe I can do something with onLayout. But anyways, this is what I was looking for.

**Comment by SrBrahma** [comment]
> I just noticed there's a prop called layoutInvalidationKey.

You saved me! Thanks! :smile:
