### ISSUE TITLE
dragHitSlop does not prevent item from becoming active

### ISSUE THREAD

**Issue by heikkimantere** [computerjazz/react-native-draggable-flatlist#289]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**
If I reduce an item's responsive area by giving my `DraggableFlatList` a prop `dragHitSlop`, it affects the area where an item can be dragged, but it does not prevent the item from becoming active. The item will have a prop `isActive: true` even when it's touched outside of the responsive area. 

**To Reproduce**

```
<DraggableFlatList
    ...
    dragHitSlop={{ left: -100 }}
/>
```

As a result the items can not be dragged if they are touched within their first 100 pixels from the left, but the items still become active (`isActive: true`) when touched within the first 100px. If the items have a different style when they are active, it looks like they could be dragged, even if they can not. 

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: iOS 14.4
 - React Native or Expo version: Expo 4.4.3
 - Reanimated version: 1.13.0 
 - React Native Gesture Handler version: 1.10.3

**Comment by computerjazz** [comment]
I'm confused -- You as the developer decide when to call `drag()` on your component, I'm not sure how `dragHitSlop` changes this. 

`dragHitSlop` has a very specific purpose -- see discussion: https://github.com/computerjazz/react-native-draggable-flatlist/issues/184#issuecomment-707590641

**Comment by heikkimantere** [comment]
I'm doing exactly like in the example that you linked. I call `onLongPress={drag}`

> hitSlop is set to ignore gesture events on all parts of the item except the drag handle

My issue is that while gesture events (drag) are ignored on other parts than the drag handle, the item still gets `isActive` prop no matter where it is touched. `dragHitSlop` doesn't affect the area where an item becomes active, it only prevents dragging from anywhere.

**Comment by heikkimantere** [comment]
I got my head around this and fixed it by simply moving `onLongPress={drag}` from the item row component to its drag handle component.
