### ISSUE TITLE
List Item jumps 44 points down on long press when animation starts

### ISSUE THREAD

**Issue by aaronbalthaser** [computerjazz/react-native-draggable-flatlist#29]
First off, nice job. This is the first drag drop component I found that was adaptable to my project. I am having an issue with this component. It works fine until I attempt to dynamically add another component which adds additional height to the container. My markup is as follows in the render function:

```
<View style={Styles.container}>
	{this._renderListAddSection()}
	<View style={{ flex: 1 }}>
		<DraggableFlatList
			isModerator={sessionModerator}
			// contentContainerStyle={Styles.contentContainer}
			data={this.state.data}
			renderItem={this._renderItem}
			scrollPercent={5}
			onMoveEnd={this._onMoveEnd}
		/>
	</View>
	<ButtonAction
		onClickHandler={this.onActionPress}
		active={listPending}
	/>
	<ListItemAdd
		visible={this.state.addModalVisible}
		closeModal={this.closeAddListModal}
		userId={this.props.user.id}
	/>
</View>
```

When the component initially loads it works as expected. The app allows a person to take administrative privileges by selecting a button in the header. That re renders the component and runs the _renderListAddSection method with basically adds another component to the view that has additional buttons

```
<ListAdd
	onPressHandler={this.openAddListModal}
	title="Tap to add a name"
/>
```

After the additional component is added with a height of 44 your component basically starts behaving unexpectedly. When long pressing the active row jumps 44 points down when activated. I have tried for a day to figure out why and am hoping you might be able to understand the issue.

It's weird because the layout seems to adjust accordingly. Before the additional component is added the layout log you added reports a height of 812 and after it update following the component being added it reports 768 as the height, which is 812 - 768 = 44 which is the additional height of the added component. 

So the problem is after adding the new component, when I press on the row to drag, instead of it becoming active in hover mode and simply changing opacity in the position it was in, it jumps down the amount of points of the added component.

Thanks.

**Comment by aaronbalthaser** [comment]
Additionally it for sure has to do with dynamically adding the component because when I remove the flag for adding the dynamic component and add it on the initial render everything works fine. Below you can see the added component which is black and says "Tap to add a name". When I add this component on the initial view load and then select the list item to drag it doesn't jump down, but if I add this component dynamically by pressing the headset button in the toolbar at the top the list item jumps down the exact height of the component.

<img width="423" alt="screen shot 2018-10-31 at 5 09 05 am" src="https://user-images.githubusercontent.com/611869/47787137-2a3e5500-dccb-11e8-9176-5ef943cb6f7e.png">

**Comment by aaronbalthaser** [comment]
Below it the position it jumps on after the long press is detected before dragging is attempted.

<img width="545" alt="screen shot 2018-10-31 at 5 14 34 am" src="https://user-images.githubusercontent.com/611869/47787378-029bbc80-dccc-11e8-9c7a-e48317acc496.png">

**Comment by dancork** [comment]
I'm using this component with react-native-navigation v2. Inside a stack it seems like some of the animations are calculating the positions wrong which causes it to jump about. I've not investigated fully yet but the difference in the y axis seems to be similar to the height of the top navigation bar.

**Comment by dancork** [comment]
Found a workaround for now which is to drawBehind to true and create a spacer view

```
  static options = {
    topBar: {
      drawBehind: true
      }
  }
...
  render () {
    return (
      <View style={styles.screen}>
        <View style={styles.spacer} />
        <DraggableFlatList
...
const styles = StyleSheet.create({
  screen: {
    flex: 1
  },
  spacer: {
    height: 88
  },
```

**Comment by mhopey** [comment]
> This is an update. I tried the following branch found in your pull requests and it fixed my issue.
> 
> https://github.com/computerjazz/react-native-draggable-flatlist/blob/9f810f4b8c7bf70d1a3ea41867175d7062b95b75/index.js

Fixes the issue on iOS but not for android

**Comment by aaronbalthaser** [comment]
@dancork I used a different branch but I guess it's not working in Android. I having a hard time following your work around. I don't see any drawBehind value in the source code.

**Comment by dancork** [comment]
@aaronbalthaser yes, so I allow the screen to draw behind the header then add a spacer view that then sits underneath.

**Comment by aaronbalthaser** [comment]
Your fix probably won't work for me. I have a tab navigation with a custom top navbar, and to make matters worse I have a component in between that animated open and closing actions which can show any of 4 child components. Lol I gotta just make this work. Its also a real time app and I am now trying to work my way through the best way to update this thing from the db while not getting outa sync with the other users.

**Comment by computerjazz** [comment]
please try v2 and reopen if there's still an issue
