### ISSUE TITLE
Demo Not Working

### ISSUE THREAD

**Issue by chrisdel101** [computerjazz/react-native-draggable-flatlist#297]
**Describe the bug**
The demo linked to in this repo is not functioning properly. The drag and drop does not work.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: MaxOS 11.1, Chrome & FireFox; Ubuntu 18, Firefox

**Additional context**
The pages loads but the D&D does not work. Tested on multiple browsers and in incognito mode.

**Comment by KrisLau** [comment]
https://snack.expo.io/@computerjazz/rndfl-example 
https://snack.expo.io/@computerjazz/rndfl-dragwithhovereffect
Both of these demos seem to work for me. I use Chrome to view them and I also use this library in my project and it's been working great for me

**Comment by chrisdel101** [comment]
I just tried again and still doesn't work for me. Could just be me; I tried tried mac and linux. Maybe it only works on windows.

**Comment by hoangvvo** [comment]
It works for me on Linux. Make sure you hold it for a while before dragging because it is a `onLongPress`.
