### ISSUE TITLE
Android crash when component mounted

### ISSUE THREAD

**Issue by Sfirleaalex** [computerjazz/react-native-draggable-flatlist#299]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**
Using the example in android app crashes when mounted with `Can not read property y of undefined` which is happening here https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/src/index.tsx#L740. 

**To Reproduce**
Link a snack if possible.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: Android 
 - React Native or Expo version: `react-native@0.63.3`
 - Reanimated version: `react-native-reanimated@1.13.1`
 - React Native Gesture Handler version: `react-native-gesture-handler@1.8.0`

**Additional context**
App is used with Hermes activated, using `react-navigation 5` and `react-native-screens`. 
Tried both with `react-native-draggable-flatlist@2.6.2` and with `react-native-draggable-flatlist@2.5.5`

**Comment by Sfirleaalex** [comment]
After more digging in our codebase we found that this `"proxy-polyfill": "^0.3.2",` is causing the behaviour.

**Comment by wq13718048209** [comment]
@Sfirleaalex    I ran into the same problem but I didn't proxy-polyfill this
