### ISSUE TITLE
How to change item order  by code instead of using  draging gesture

### ISSUE THREAD

**Issue by River-w** [computerjazz/react-native-draggable-flatlist#301]
I would like to change item order with animation by code, but i can not find any api to do this.
Would you please tell me how can i change order without using draging gesture

**Comment by computerjazz** [comment]
This is not a supported use case. If you _really_ wanted to, you could manually drive the animated values that are currently driven by gestures, and should end up with the same result, but that'd be a lot of work to wire up.
