### ISSUE TITLE
Slow render compared to FlatList

### ISSUE THREAD

**Issue by ShavaShav** [computerjazz/react-native-draggable-flatlist#309]
**Describe the bug**
The `DraggableFlatList` component takes about 3-4x as long to render it's items as react-native's `FlatList`

**To Reproduce**
See the following snack: https://snack.expo.dev/duZ9cEKe6
Note that FlatList finishes rendering in < 10ms. 
![image](https://user-images.githubusercontent.com/17697598/130531463-2820a9e8-590d-42b7-bdbf-33844562bc2e.png)

Replace `FlatList` with `DraggableFlatList`, and note it takes considerably longer to render:
![image](https://user-images.githubusercontent.com/17697598/130531486-383bed1c-1c16-47b7-a5f0-9aee7691cb56.png)

When rendering non-trivial items (not just `<Text/>`), this can lead to the user waiting quite a bit for the list to load.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: react-native
 - React Native or Expo version: 0.64.1
 - Reanimated version: ^2.2.0
 - React Native Gesture Handler version: ^1.10.3
 - React-navigation/native: ^5.9.4

**Comment by computerjazz** [comment]
Not too surprising, there is a LOT of animation/optimization going on under the hood. Hopefully this gets faster as reanimated improves performance.

**Comment by Orange9000** [comment]
I've already done the getItemLayout optimization, any tips on improving render performance even more?
