### ISSUE TITLE
when performing an update on the content, this does not reflect for the listing

### ISSUE THREAD

**Issue by henriqueweiand** [computerjazz/react-native-draggable-flatlist#31]
I am updating the content of DraggableFlatList, in the data attribute via redux, but I noticed that when updating in the variable that is defined in the date, it does not update the listing, this only occurs when the drag drop

Example with DraggableFlatList:

![com draggableflatlist](https://user-images.githubusercontent.com/6539492/48365041-e23b0d00-e690-11e8-9ef5-5418d35246b0.gif)

code:

```js
<DraggableFlatList
        data={data}
        renderItem={this.renderItem}
        keyExtractor={item => `key-${item.interno}`}
        scrollPercent={5}
        onMoveEnd={({ data }) => this.props.ordenacaoActions.setOrderUnidadesRequest({ data })}
        contentContainerStyle={{ marginHorizontal: metrics.baseMargin }}
        ItemSeparatorComponent={() => <View style={styles.separator} />}
      />
```

Example without DraggableFlatList and use original FlatList

![flatlist](https://user-images.githubusercontent.com/6539492/48365106-131b4200-e691-11e8-9fc4-99013ccea571.gif)

code:

```js
<FlatList
        data={data}
        renderItem={this.renderItem}
        keyExtractor={item => `key-${item.interno}`}
        scrollPercent={5}
        onMoveEnd={({ data }) => this.props.ordenacaoActions.setOrderUnidadesRequest({ data })}
        contentContainerStyle={{ marginHorizontal: metrics.baseMargin }}
        ItemSeparatorComponent={() => <View style={styles.separator} />}
      />
```

I believe the lib, is not considering in your shouldComponentUpdate when there is update in the input values, or something of the genre ...

Am I correct about this procedure?

**Comment by bomei** [comment]
`FlatList` is pureComponent, you should add `extraData={data}` or something similar in your code.

**Comment by HaywoodSolutions** [comment]
Is there any update on this problem as still having this issue

**Comment by kelsonic** [comment]
I solved this using @bomei's suggestion. Passing the prop `extraData` with the nested data that can change resolved the issue for me. Check out the docs on this prop here: https://facebook.github.io/react-native/docs/flatlist#extradata

It might be clearer if we added a link in the readme to all the `FlatList` props you can pass as well so this doesn't happen in the future: https://facebook.github.io/react-native/docs/flatlist#props

**Comment by computerjazz** [comment]
yep, extraData seems like the answer here
