### ISSUE TITLE
Items maintain old position when data array altered outside of DraggableFlatList

### ISSUE THREAD

**Issue by rissois** [computerjazz/react-native-draggable-flatlist#310]
DESCRIPTION:
It is sometimes useful to sort the data array outside of the DraggableFlatList (for instance, when resetting the data array to its original state). However, the positions of the items do not correct themselves immediately.

e.g. 
START: A B C D
MOVE: B C D A
Even if you setState back to A B C D, when you touch item A, it jumps to the post-move position B C D A

Here is a repro that should be helpful: move Item 1 down a few positions, then hit the green button on the bottom. Then grab Item 1 again.
https://snack.expo.dev/JYXhahSpj

**Comment by rissois** [comment]
My solution for now:

const [remeasure, setRemeasure] = useState('')

useEffect(() => setRemeasure((Date.now()).toString()), [data])

<DraggableFlatList
    data={data}
    keyExtractor={item => item}
    renderItem={renderItem}
    onDragEnd={({ data }) => setData(data)}
    layoutInvalidationKey={remeasure}
  />

**Comment by computerjazz** [comment]
good catch, yeah, since the keys haven't changed RNDFL doesn't think that it needs to remeasure the layout. changing the `layoutInvalidationKey` sounds like a good solution for now.
