### ISSUE TITLE
Uknown error while using it for the first time

### ISSUE THREAD

**Issue by Ruzen1** [computerjazz/react-native-draggable-flatlist#311]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**
I have already installed react native reanimated and rngh . I installed flatlist for the first time but it shows the following error.

**To Reproduce**
Link a snack if possible.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: 
 - React Native or Expo version: RN 0.61.3
 - Reanimated version: 1.3.1
 - React Native Gesture Handler version:1.5.3

**Additional context**
![Simulator Screen Shot - iPhone 11 - 2021-08-30 at 13 40 26](https://user-images.githubusercontent.com/25242058/131286295-e9674f28-649a-4c2d-8647-a09df3086dbb.png)

**Comment by computerjazz** [comment]
Can you provide a reproduction via snack?
