### ISSUE TITLE
Allow an underlying list that is not based on `VirtualizedList`

### ISSUE THREAD

**Issue by tncbbthositg** [computerjazz/react-native-draggable-flatlist#318]
**Is your feature request related to a problem? Please describe.**
I have a page that needs to scroll.  Inside it I have a list that does not need to scroll.  As far as I know, there's no way to get the `FlatList` not to render as a `VirtualizedList`.  

**Describe the solution you'd like**
I'd like to have a prop that let me indicate to the `DraggableFlatList` that I'd like to render some other parent component . . . probably just a View.

**Describe alternatives you've considered**
I looked for a property that would allow me to indicate to the `FlatList` that all elements should be fully rendered and that the full list should be displayed at all times and thus it should not scroll and the external `ScrollView` should have priority.

Others recommend using the `FlatList` with the header and footer properties specified, but the result is still a scrollable list . . . which I'd like not to have.

**Additional context**
Thanks a lot for this library; it's super helpful and looks great.  :)

**Comment by SrBrahma** [comment]
Have you figured out a workaround? I have a nested draggable flatlist and can't scroll the main view when my touch is over a nested item.

**Comment by haveneersrobin** [comment]
There was a similar issue I believe which was closed without a 'real' solution: https://github.com/computerjazz/react-native-draggable-flatlist/pull/288

It should not be too hard to create a PR for this 😉

**Comment by computerjazz** [comment]
a non-flatlist version of react-native-draggable-flatlist is not in scope for this package, as it has been created around the flatlist api.
