### ISSUE TITLE
Auto-scroll with DraggableFlatList inside ScrollView does not work

### ISSUE THREAD

**Issue by richardwu** [computerjazz/react-native-draggable-flatlist#319]
**Describe the bug**
When we have a DraggableFlatList inside a ScrollView, one cannot drag and autoscroll.

That is, in the below snack, if you begin to drag box 1 beyond box 9/10, ScrollView does not autoscroll.

**To Reproduce**
Credits to @computerjazz from [his comment here](https://github.com/computerjazz/react-native-draggable-flatlist/issues/220#issuecomment-843307010) and his Snack: https://snack.expo.dev/@computerjazz/rndfl-nested-scrollview-example

**Platform & Dependencies**
```
{
  "dependencies": {
    "react-native-reanimated": "~1.13.0",
    "react-native-gesture-handler": "~1.10.0",
    "react-native-draggable-flatlist": "2.6.2"
  }
}
```

**Comment by TechSaq** [comment]
User normal `View` with `maxHeight` instead of `ScrollView`

**Comment by Kralfallah** [comment]
Debugger mode on ios blocks drag and drop

**Comment by computerjazz** [comment]
Nesting support added in `3.1.0`: https://github.com/computerjazz/react-native-draggable-flatlist/releases/tag/v3.1.0

**Comment by hamzaawais96** [comment]
@computerjazz  using v3.1.2 and auto-scroll still doesn't work. Wrapped `NestableDragFlalist` with `NestableScrollContainer`.
