### ISSUE TITLE
Load other card when you reach the end of the list

### ISSUE THREAD

**Issue by Manitta1998** [computerjazz/react-native-draggable-flatlist#320]
**Is your feature request related to a problem? Please describe.**
I want to load my cards in lazy load, when I reach the end of the list (ex onEndReached in Flatlist) I want to load more cards, is this possible?

**Describe the solution you'd like**
like onEndReached in Flatlist native

**Comment by computerjazz** [comment]
yes, you can pass all FlatList props to your DraggableFlatList and they'll get spread onto the underlying flatlist. 
Example with onEndReached: https://snack.expo.dev/@computerjazz/rndfl3-onendreached
