### ISSUE TITLE
Wrong start point on drag

### ISSUE THREAD

**Issue by futureinapps** [computerjazz/react-native-draggable-flatlist#322]
I have RNDFlatlist with resizeable header. 

Header resizes on a list scroll event. 

Inside the list I have a collapsable row.

When I try to change size of header or size of row and then drag the row, it is starting drag from an incorrect point. For example if I start draggin when header resized it starts from  point = startPoint - headerHeight.

It can be fix if I reload data variable, but it screen blinks on this action.

Is it possible when making layout changes dynamicly change the list measure?

**Comment by computerjazz** [comment]
yep, that's what `layoutInvalidationKey` is for.

this behavior is fixed in v3
