### ISSUE TITLE
[Feature Request] onItemMove property

### ISSUE THREAD

**Issue by SrBrahma** [computerjazz/react-native-draggable-flatlist#323]
**Is your feature request related to a problem? Please describe.**
When moving an item, it's needed to check if `from !== to`, and the moved item is accessible via data[to], and this is somewhat counter intuitive at first (i was having a now obvious bug, as data has the array after the move)

**Describe the solution you'd like**
`onItemMove` (or onItemMoved) function property, only triggered when the index changes. As property, it will also contain, besides the onDragEnd props, `item` or `movedItem`, being it the data[to]. This property could also be added to onDragEnd.

**Describe alternatives you've considered**
Here is what I am basically doing, not bad but could be better if my feature was included:

```ts
onDragEnd={async ({ from, to, data }) => {
  if (from === newIndex)
    return;
  const { id: categoryId } = data[to]!;
  // server function using 'categoryId' and 'to'
}}
```

Now if the feature is added:

```ts
onItemMove={async ({ item: {categoryId}, to }) => {
  // server function using 'categoryId' and 'to'
}}
```

Not a real big deal, but for me those small stuff that could be simplified really makes the code prettier.

I am really liking this lib! :)

**Comment by computerjazz** [comment]
thanks for the feature request! 
since this information can be derived in one line of code, I don't think it deserves an extra parameter. 
If there's one thing I've learned as a package author, it's to keep things as simple and minimal as possible 😀
