### ISSUE TITLE
onRef never gives me the underlying list reference

### ISSUE THREAD

**Issue by maxfahl** [computerjazz/react-native-draggable-flatlist#324]
**Describe the bug**
onRef never gives me the underlying list reference, all I get is null.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: iOS
 - React Native or Expo version: 42.0.4
 - Reanimated version: 2.2.0
 - React Native Gesture Handler version: 1.10.2

**Additional context**
```typescript
<DraggableFlatList
        data={items}
        extraData={extraData}
        layoutInvalidationKey={layoutInvalidationKey}
        keyExtractor={item => `${item.id}`}
        showsVerticalScrollIndicator={false}
        style={{flex: 1}}
        onRelease={dragRelease}
        onDragBegin={dragBegin}
        onDragEnd={onDragEnd}
        renderItem={renderItem}
        keyboardShouldPersistTaps={keyboardShouldPersistTaps}
        activationDistance={0}
        autoscrollSpeed={100}
        scrollEnabled={scrollEnabled}
        onRef={listRef => {
          console.log('--- listRef', listRef.current)
          // ref.current = listRef.current
        }}
      />
```
onRef gets called once with listRef.current being null.

I don't think Iäm doing anything wrong here, please help me. Would appreciate it big time.

**Comment by computerjazz** [comment]
`onRef` returns the react `ref`, which is not populated until first render. 
see: https://github.com/computerjazz/react-native-draggable-flatlist/issues/186#issuecomment-639654613
