### ISSUE TITLE
Getting undefined is not a function error

### ISSUE THREAD

**Issue by devout-coder** [computerjazz/react-native-draggable-flatlist#326]
I tried to use exactly the example given in the [documentation](https://www.npmjs.com/package/react-native-draggable-flatlist) but I am getting 'undefined is not a function error'

**Comment by maxfahl** [comment]
Hey you stackoverflow guy. I think you need to be a little more specific, also, I'm trying to help you at stack but you stopped answering me :)

**Comment by marlonklc** [comment]
@devout-coder  me too! I following step by step on installation (a little extensive by the way)

![image](https://user-images.githubusercontent.com/9343013/141043618-1cd63c98-5821-4390-96e5-02abef19b7ac.png)

**Comment by chungweileong94** [comment]
> I tried to use exactly the example given in the [documentation](https://www.npmjs.com/package/react-native-draggable-flatlist) but I am getting 'undefined is not a function error'

You might want to provide more information regarding the issue, `undefined is not a function error` is too general and doesn't provide any useful information to debug.

**Comment by devout-coder** [comment]
thanks a lot @marlonklc it works flawlessly after I installed the old version

**Comment by marlonklc** [comment]
> thanks a lot @marlonklc it works flawlessly after I installed the old version

nice!
