### ISSUE TITLE
onRef is returning null on current

### ISSUE THREAD

**Issue by Isaacmeedinaa** [computerjazz/react-native-draggable-flatlist#328]
I want to scroll to the end of the FlatList when the data prop changes. I am trying to set the FlatList ref to a useRef variable but it always returns {current: null}.

**Comment by maxfahl** [comment]
It is working on 3.0 beta 12.

**Comment by computerjazz** [comment]
refs are not populated until the initial render. see: https://github.com/computerjazz/react-native-draggable-flatlist/issues/186#issuecomment-639654613
