### ISSUE TITLE
Conditionally Enable/Disable the ability to drag

### ISSUE THREAD

**Issue by ramiel1999** [computerjazz/react-native-draggable-flatlist#333]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
Optionally enable/disable the ability to drag

**Describe alternatives you've considered**
I thought of adding a state variable 'isEditing' and if true show a DraggableFlatlist  else show a regular Flatlist, but I was wondering if it was possible to just change a prop on DraggableFlatlist instead of changing components

**Comment by computerjazz** [comment]
just don't call `drag()` if `isEditing` is `true`?

**Comment by ramiel1999** [comment]
I should have read the doc more carefully. Thanks for the quick response and thank you for the new version
