### ISSUE TITLE
Default autoscroll speed is good on ios but extremely fast on android

### ISSUE THREAD

**Issue by ramiel1999** [computerjazz/react-native-draggable-flatlist#334]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**
Default autoscroll speed on ios is fine, but on android is way to fast that makes it unusable

**To Reproduce**
The snack provided in the docs is enough to reproduce it. I copy pasted the code

**Platform & Dependencies**
 - Platform: Android
 - Expo version: 42.0.1
 - Reanimated version: 2.2.0
 - React Native Gesture Handler version: 1.10.2

**Additional context**
I changed the autoscroll speed to the following and it was usable: autoscrollSpeed={Platform.select({ android: 5, default: 80 })}

I just thought that probably this behavior is unintentional and hope you could take a look

**Comment by computerjazz** [comment]
yeah, I used to default android autoscroll speed to 1/10 of ios speed (https://github.com/computerjazz/react-native-draggable-flatlist/blob/03ee2b201205b7fef9e55024dae755f51ababca5/src/index.tsx#L653-L654), but as of react-native 64 (expo 43), they seem to be about the same speed (try the example snack using expo 42 and then using 43 and you'll see the difference in speed: https://snack.expo.dev/@computerjazz/rndfl3)

There is also an android bug in react native < 64 that causes jank while autoscrolling. I would recommend using version 2 of this package until you upgrade to react native 64. Documented here: https://github.com/computerjazz/react-native-draggable-flatlist/pull/281#issuecomment-841874260
