### ISSUE TITLE
Draggable Flatlist prevents swiping back to go to a previous screen

### ISSUE THREAD

**Issue by ramiel1999** [computerjazz/react-native-draggable-flatlist#336]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**
I have a screen that has a draggable flatlist. I want the user to be able to go back to a previous screen by swiping back on an ios device, but draggable flatlist prevents it

**To Reproduce**
https://snack.expo.dev/@ramiel99/a62878

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: IOS
 - React Native or Expo version: Expo 43
 - Reanimated version: 2.2.0
 - React Native Gesture Handler version: 1.10.2

**Additional context**

**Comment by computerjazz** [comment]
you can add a `dragHitSlop={{ left: -50 }}` (play around with the value to see what works):
https://snack.expo.dev/@computerjazz/draggable-flatlist-stops-going-back-on-ios

it doesn't seem to work on the expo sim but does on device.

**Comment by ramiel1999** [comment]
My use case actually is that each item is a horizontal box that spans the whole screen width, but the user can only reorder when pressing on a reorder icon on the far right, so this should be fine.

Thanks a lot @computerjazz. You did well on this package
