### ISSUE TITLE
Is layoutInvalidationKey usable in v3?

### ISSUE THREAD

**Issue by ONI-NZ** [computerjazz/react-native-draggable-flatlist#341]
Is layoutInvalidationKey still usable in v3 to update the draggable flatlist?

For example, refreshing if the sizing of the items has changed.

**Comment by computerjazz** [comment]
it should no longer be necessary, since the items should now automatically refresh their own sizing on layout. are you seeing an issue with that?

**Comment by ONI-NZ** [comment]
Thanks for explaining how it works with v3.

I'm currently upgrading a component with v2 to v3 that used layoutInvalidationKey and wasn't sure how the process worked in this version.

Thank you.
