### ISSUE TITLE
Release element without moving, next drag activation just blinks 

### ISSUE THREAD

**Issue by blobski** [computerjazz/react-native-draggable-flatlist#342]
**Describe the bug**
1. Activate drag on an item (say by long press) and then just release it without any moving
2. Try activate drag on same item again - you will see it just "blinking"

**To Reproduce**
Can be reproduces wherever. Including official example snack:
https://snack.expo.io/@computerjazz/rndfl3

**Comment by computerjazz** [comment]
thisi should be fixed in `3.0.4`
