### ISSUE TITLE
onLayout is not a function

### ISSUE THREAD

**Issue by CptMaumau** [computerjazz/react-native-draggable-flatlist#346]
**Describe the bug**
![Simulator Screen Shot - iPhone 13 - 2022-01-12 at 18 06 48](https://user-images.githubusercontent.com/5366008/149098060-fe1d8f33-ec98-416a-a6fc-40c9c4994f41.png)

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - react-native-draggable-flatlist version: 3.0.4
 - Platform: iOS
 - React Native version: 0.65.1
 - Reanimated version: 2.3.0
 - React Native Gesture Handler version: 2.1.0

**Additional context**
I tried adding `onLayout` as a prop to `DraggableFlatList` but it doesn't fix it.

**Comment by computerjazz** [comment]
published `3.0.6`
