### ISSUE TITLE
Not scrolling when reaching end of visible list

### ISSUE THREAD

**Issue by lachtos** [computerjazz/react-native-draggable-flatlist#347]
**Describe the bug**
While dragging an item to start/end of the list, the list doesn't scroll. `autoscrollThreshold` and `autoscrollSpeed` are set.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - react-native-draggable-flatlist version: 3.0.4
 - Platform: iOS (Android unclear)
 - React Native or Expo version: 0.67.0-rc.6
 - Reanimated version: 1.13.3 (any newer version does not work)
 - React Native Gesture Handler version: 2.1.1

**Additional context**
With reanimated 2.3.0 & 2.3.1 the app fails to load
With reanimated 2.2.4 the app works but draggable flatlist does not, item can be picked up but dragging does not work.
I found that with reanimated 1.13.3 dragging works well, however I get the problem of not being able to scroll the flatlist.
I'm not using ScrollView.

**Comment by lachtos** [comment]
Do you think this is a typo in `line 119`?
https://github.com/computerjazz/react-native-draggable-flatlist/blob/3c8a59c095d0328ad4929d1ee0a216293b2d883a/src/hooks/useAutoScroll.tsx#L113-L121

I think it should be
```js
flatListRef.current.getNode();
```

At least it makes the auto scroll work on my end.

**Comment by lachtos** [comment]
This seems non-issue with `reanimated` 2+, because this line is never reached. However, in case older version had to be used, this should be fixed.

**Comment by computerjazz** [comment]
good find, thanks! fixed in 3.0.5
