### ISSUE TITLE
Incompatible Reanimated version

### ISSUE THREAD

**Issue by admapop** [computerjazz/react-native-draggable-flatlist#359]
**Describe the bug**
When running tests I receive the following error
```
      Incompatible Reanimated version (useValue not found)
      at Object.<anonymous> (node_modules/react-native-draggable-flatlist/lib/context/animatedValueContext.js:30:11)
      at Object.require (node_modules/react-native-draggable-flatlist/lib/hooks/useCellTranslate.js:5:30)
```

**To Reproduce**
Have the packages installed.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - react-native-draggable-flatlist version: ^3.0.5
 - Platform: iOS & Android & Jest runner
 - React Native or Expo version: 0.63
 - Reanimated version: ^2.3.0
 - React Native Gesture Handler version: ^1.10.3

**Additional context**
Draggable flatlist is working fine in the app, however, it's breaking all tests.

**Comment by xhirazi** [comment]
+1

**Comment by wardjk87** [comment]
You have to make sure your mock for react-native-reanimated includes useValue, etc.

For example:

jest.mock("react-native-reanimated", () => {
    return {
        abs: jest.fn(),
        add: jest.fn(),
        and: jest.fn(),
        block: jest.fn(),
        call: jest.fn(),
        ceil: jest.fn(),
        Clock: jest.fn(),
        clockRunning: jest.fn(),
        Code: MockedTransitioningView,
        cond: jest.fn(),
        debug: jest.fn(),
        decay: jest.fn(),
        defined: jest.fn(),
        divide: jest.fn(),
        eq: jest.fn(),
        event: jest.fn(),
        floor: jest.fn(),
        Extrapolate: { CLAMP: jest.fn() },
        greaterOrEq: jest.fn(),
        greaterThan: jest.fn(),
        interpolate: jest.fn(),
        lessOrEq: jest.fn(),
        lessThan: jest.fn(),
        max: jest.fn(),
        min: jest.fn(),
        multiply: jest.fn(),
        neq: jest.fn(),
        not: jest.fn(),
        onChange: jest.fn(),
        round: jest.fn(),
        or: jest.fn(),
        set: jest.fn(),
        spring: jest.fn(),
        startClock: jest.fn(),
        stopClock: jest.fn(),
        sub: jest.fn(),
        timing: jest.fn(),
        Value: jest.fn(),
        useValue: jest.fn(),
        proc: jest.fn(),
        View: MockedTransitioningView,
        Transition: {
            In: 'In',
            Out: 'Out',
            Together: 'Together',
        },
        Transitioning: {
            View: MockedTransitioningView
        },
        Easing: {
            in: jest.fn(),
            inOut: jest.fn(),
            out: jest.fn(),
        },
        createAnimatedComponent: jest.fn(),
    };
});

**Comment by admapop** [comment]
> You have to make sure your mock for react-native-reanimated includes useValue, etc.
> 
> For example:
> 
> ```
> jest.mock("react-native-reanimated", () => {
>     return {
>         abs: jest.fn(),
>         add: jest.fn(),
>         and: jest.fn(),
>         block: jest.fn(),
>         call: jest.fn(),
>         ceil: jest.fn(),
>         Clock: jest.fn(),
>         clockRunning: jest.fn(),
>         Code: MockedTransitioningView,
>         cond: jest.fn(),
>         debug: jest.fn(),
>         decay: jest.fn(),
>         defined: jest.fn(),
>         divide: jest.fn(),
>         eq: jest.fn(),
>         event: jest.fn(),
>         floor: jest.fn(),
>         Extrapolate: { CLAMP: jest.fn() },
>         greaterOrEq: jest.fn(),
>         greaterThan: jest.fn(),
>         interpolate: jest.fn(),
>         lessOrEq: jest.fn(),
>         lessThan: jest.fn(),
>         max: jest.fn(),
>         min: jest.fn(),
>         multiply: jest.fn(),
>         neq: jest.fn(),
>         not: jest.fn(),
>         onChange: jest.fn(),
>         round: jest.fn(),
>         or: jest.fn(),
>         set: jest.fn(),
>         spring: jest.fn(),
>         startClock: jest.fn(),
>         stopClock: jest.fn(),
>         sub: jest.fn(),
>         timing: jest.fn(),
>         Value: jest.fn(),
>         useValue: jest.fn(),
>         proc: jest.fn(),
>         View: MockedTransitioningView,
>         Transition: {
>             In: 'In',
>             Out: 'Out',
>             Together: 'Together',
>         },
>         Transitioning: {
>             View: MockedTransitioningView
>         },
>         Easing: {
>             in: jest.fn(),
>             inOut: jest.fn(),
>             out: jest.fn(),
>         },
>         createAnimatedComponent: jest.fn(),
>     };
> });
> ```

I realised it was this in the end.
Thanks!
