### ISSUE TITLE
onScroll performance issue

### ISSUE THREAD

**Issue by ErrorPro** [computerjazz/react-native-draggable-flatlist#367]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**
When scrolling a big list the JS gets blocked and becomes not responsive. 

**To Reproduce**
This is an example of an out-of-box library: https://monosnap.com/file/8EjL414fuMae3GFF6uEr9Oqj3PopgN
This is an example when I comment out [this line](https://github.com/computerjazz/react-native-draggable-flatlist/blob/main/src/components/DraggableFlatList.tsx#L351): https://monosnap.com/file/Mp3OCqZQbUWKlrlbe0e7BPxdXO2Tzn

The difference is quite noticeable. Is there a way to improve this part of functionality?

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - react-native-draggable-flatlist version: ^3.0.6
 - Platform: Both
 - React Native or Expo version: ^0.66.3
 - Reanimated version: ^2.3.1
 - React Native Gesture Handler version: ^2.0.0

**Additional context**

**Comment by toanthangdev** [comment]
How do you fix this issue?
