### ISSUE TITLE
Animation for insert or delete item

### ISSUE THREAD

**Issue by SergeyA** [computerjazz/react-native-draggable-flatlist#371]
Hello!

Is it possible to animate the programmatic insertion or deletion of an item in a list?

Example of deletion animation:
![remove_item](https://user-images.githubusercontent.com/883377/162639552-255063da-4f1f-4a93-87ab-77c3fc360a5d.gif)

**Comment by computerjazz** [comment]
yes, but that's up to you to implement.
The easiest way is via `LayoutAnimation`, see the swipe-to-delete demo here: https://snack.expo.dev/@computerjazz/swipeable-draggable-list
