### ISSUE TITLE
DraggableFlatList does not support RefreshControl

### ISSUE THREAD

**Issue by emir7218** [computerjazz/react-native-draggable-flatlist#372]
Hello,

Looks like the component does not support refreshControl. Here are the snippets that I modified based on the example given

`  return (
    <DraggableFlatList
    	refreshControl={
	<RefreshControl
		refreshing={refresh}
		onRefresh={() => {
		setRefresh(true);
	        }}
	/>
	}
      ref={ref}
      data={data}
      onDragEnd={({ data }) => setData(data)}
      keyExtractor={(item) => item.key}
      renderItem={renderItem}
      onPlaceholderIndexChange={setPlaceholderIndex}
      renderPlaceholder={({ item, index }) => (
        <View style={{ flex: 1, backgroundColor: 'tomato' }}>
          <Text
            style={[
              styles.rowItem,
              styles.text,
            ]}>{`placeholder: index: ${placeholderIndex}`}</Text>
        </View>
      )}
    />
  );`

Any suggestion to make it work?

**Comment by computerjazz** [comment]
duplicate https://github.com/computerjazz/react-native-draggable-flatlist/issues/135
