### ISSUE TITLE
NestableDraggableFlatlist/NestableScrollContainer Ref not being set/obtained

### ISSUE THREAD

**Issue by creambyemute** [computerjazz/react-native-draggable-flatlist#391]
**Describe the bug**
I have just upgraded from V2 to V3 for the new ref handling + being able to replace a hacky solution with NestableScrollContainer and NestableDraggableFlatlist.

On V3, on the new NestableDraggableFlatlist obtaining a ref is not working at all nor is the old `onRef`.

On V3, on the new NestableScrollContainer obtaining a ref always results in null.

**To Reproduce**
Add a `NestableDraggableFlatlist` 

```javascript
<NestableDraggableFlatList
    ref={onDraggableListRefReady} // I also tried React.useRef hook, it's never called/set
    ...
/>
```

Add a `NestableScrollContainer` 

```javascript
<NestablescrollContainer
    ref={onScrollContainerRefReady} // I also tried React.useRef hook, it's always called/set with null
    ...
/>
```

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - react-native-draggable-flatlist version: 3.1.1
 - Platform: Android & iOS
 - React Native or Expo version: 0.65.2
 - Reanimated version: 2.2.3
 - React Native Gesture Handler version: 1.10.3

**Additional context**
Example usage: Retain scrollPosition of currently selected listItem when switching between ReadOnly Mode/Edit Mode

**Comment by computerjazz** [comment]
good catch! can you try https://github.com/computerjazz/react-native-draggable-flatlist/releases/tag/v3.1.2

**Comment by robertcreaner** [comment]
Also facing this issue in v ^3.2.1

**Comment by awalmubarak** [comment]
> good catch! can you try https://github.com/computerjazz/react-native-draggable-flatlist/releases/tag/v3.1.2

Same problem on this version

**Comment by shaheryar-kodexo** [comment]
> good catch! can you try https://github.com/computerjazz/react-native-draggable-flatlist/releases/tag/v3.1.2

Same problem with 3.1.2 and right now i can't update it to 4.0.1 as i am getting ref on 4.0.1 but the nesteddraggableList behaves abnormally on drag

**Comment by scrapecoder** [comment]
+1
