### ISSUE TITLE
demo is not working

### ISSUE THREAD

**Issue by xclidongbo** [computerjazz/react-native-draggable-flatlist#395]
rn version: 0.63.2

demo is not working

**Comment by Hihoa1999** [comment]
import { GestureHandlerRootView } from 'react-native-gesture-handler';

<GestureHandlerRootView style={{ flex: 1 }}>
      //your draggableList Code 
</GestureHandlerRootView>

**Comment by borisnetweb** [comment]
+1 basic demo is not working in the snack https://snack.expo.dev/@computerjazz/draggable-flatlist-examples?platform=ios - on ios emu can not drag list items. Swipeable example however does work, will try and implement that one.
