### ISSUE TITLE
Autoscroll breaks after setting a ref on flatlist 

### ISSUE THREAD

**Issue by robertcreaner** [computerjazz/react-native-draggable-flatlist#403]
**Describe the bug**
Autoscroll works fine until you add a ref to the flatlist. After adding ref the autoscroll stops working. 

**To Reproduce**
Added a ref to the FlatList on the Basic screen to showcase the issue:
https://snack.expo.dev/@hailorob/draggable-flatlist-examples

**Platform & Dependencies**
 - react-native-draggable-flatlist version: 3.1.2
 - Platform: both
 - React Native or Expo version: 0.68.2
 - Reanimated version: 2.2.4
 - React Native Gesture Handler version: 1.9.0

**Comment by LWilsonDev** [comment]
I also have this problem - @robertcreaner did you happen to find a solution? Many thanks

**Comment by wen-kai** [comment]
returning the node in ref allows you to set ref and support autoscroll.
eg: `ref={node => { this._list = node; return node; }}`
