### ISSUE TITLE
Drag between sections

### ISSUE THREAD

**Issue by dcassese** [computerjazz/react-native-draggable-flatlist#404]
Would it be difficult to drag an item from one section to another.? Using the Nested example.

**Comment by computerjazz** [comment]
Yeah, it would require a huge refactor to drag between nested lists. I suggest you look for a different way, maybe using ItemSeparatorComponent, or a section header that's just another flatlist item.

**Comment by CuriosBasant** [comment]
> Yeah, it would require a huge refactor to drag between nested lists. I suggest you look for a different way, maybe using ItemSeparatorComponent, or a section header that's just another flatlist item.

Can you elaborate that a little more? May be provide an example or something.
Thanks!

**Comment by LucaDotti** [comment]
@CuriosBasant you can add a ItemSeparatorComponent and use the leadingItem to see if you want to set the ItemSeparatorComponent or not. For example I have to display a list of weeks and group them by month. I use the leadingItem props from the ItemSeparatorComponent to check if I have to render the "Month header". 
Unfortunately, this cause the item separator component to be dragged together with the actual item. Lets say you want to move the first week of the second month, then you will see the first week item together with the "Month Header" being dragged.

**Comment by LucaDotti** [comment]
@CuriosBasant I have to correct my answer, for some reason, now the ItemSeparatorComponent is not dragged anymore together with the actual item. No idea what caused this.
