### ISSUE TITLE
Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code

### ISSUE THREAD

**Issue by rachellauyui** [computerjazz/react-native-draggable-flatlist#408]
**Describe the bug**
The same error both in Android and iOS: 

> Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"4963":{"module":"AsyncSQLiteDBStorage","method":"multiGet"},"4964":{"module":"AsyncSQLiteDBStorage","method":"multiGet"},"4965":{"module":"AsyncSQLiteDBStorage","method":"multiGet"},"4966":{"module":"AsyncSQLiteDBStorage","method":"multiGet"},"4967":{"module":"AsyncSQLiteDBStorage","method":"multiGet"},"4978":{"module":"NativeUnimoduleProxy","method":"callMethod"},"4979":{"module":"NativeUnimoduleProxy","method":"callMethod"},"5786":{"module":"ReanimatedModule","method":"getValue"},"5848":{"module":"ReanimatedModule","method":"getValue"},"5878":{"module":"ReanimatedModule","method":"getValue"},"5894":{"module":"ReanimatedModule","method":"getValue"},"5921":{"module":"ReanimatedModule","method":"getValue"},"6180":{"module":"ReanimatedModule","method":"getValue"},"6520":{"module":"ReanimatedModule","method":"getValue"},"6531":{"module":"ReanimatedModule","method":"getValue"},"6564":{"module":"ReanimatedModule","method":"getValue"},"6571":{"module":"ReanimatedModule","method":"getValue"},"6605":{"module":"ReanimatedModule","method":"getValue"},"6617":{"module":"ReanimatedModule","method":"getValue"},"6628":{"module":"ReanimatedModule","method":"getValue"},"6632":{"module":"ReanimatedModule","method":"getValue"},"6647":{"module":"ReanimatedModule","method":"getValue"},"6650":{"module":"ReanimatedModule","method":"getValue"},"6653":{"module":"ReanimatedModule","method":"getValue"},"6656":{"module":"ReanimatedModule","method":"getValue"},"6659":{"module":"ReanimatedModule","method":"getValue"},"6662":{"module":"ReanimatedModule","method":"getValue"},"6687":{"module":"ReanimatedModule","method":"getValue"},"6704":{"module":"ReanimatedModule","method":"getValue"},"6713":{"module":"ReanimatedModule","method":"getValue"},"6718":{"module":"ReanimatedModule","method":"getValue"},"6723":{"module":"ReanimatedModule","method":"getValue"},"6728":{"module":"ReanimatedModule","method":"getValue"},"6733":{"module":"ReanimatedModule","method":"getValue"},"6738":{"module":"ReanimatedModule","method":"getValue"},"6743":{"module":"ReanimatedModule","method":"getValue"},"6763":{"module":"ReanimatedModule","method":"getValue"},"6773":{"module":"ReanimatedModule","method":"getValue"},"6776":{"module":"ReanimatedModule","method":"getValue"},"6779":{"module":"ReanimatedModule","method":"getValue"},"6782":{"module":"ReanimatedModule","method":"getValue"},"6785":{"module":"ReanimatedModule","method":"getValue"},"6804":{"module":"ReanimatedModule","method":"getValue"},"6831":{"module":"ReanimatedModule","method":"getValue"},"6835":{"module":"ReanimatedModule","method":"getValue"},"6850":{"module":"ReanimatedModule","method":"getValue"},"6853":{"module":"ReanimatedModule","method":"getValue"},"6856":{"module":"ReanimatedModule","method":"getValue"},"6859":{"module":"ReanimatedModule","method":"getValue"},"6862":{"module":"ReanimatedModule","method":"getValue"},"...(truncated keys)...":451}  

**To Reproduce**
`<DraggableFlatList
          initialNumToRender={15}
          data={draggableData}
          onDragEnd={async ({ data }) => {
            setDraggableData(data);  }}
          keyExtractor={(item) => item.id}
          showsVerticalScrollIndicator={false}
          ListFooterComponent={<View style={{ marginBottom: "40%" }} />}
          renderItem={({ item, drag, isActive, index }) => {
            return (
              <ScaleDecorator>
                <TouchableOpacity
                  onLongPress={drag}
                  disabled={isActive}
                  key={index}
                >
                  ... some text
                </TouchableOpacity>
              </ScaleDecorator>
            );
          }}
        />`

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - react-native-draggable-flatlist version: 3.1.2
 - Platform: Android & iOS
 - React Native or Expo version: expo 45
 - Reanimated version: 2.8.0
 - React Native Gesture Handler version: 2.2.1

Any ideas how to fix it? Many thanks!

**Comment by rachellauyui** [comment]
I am happy to report that the issue resolved once I upgrade from draggable flatlist 3.1.2 to 4.0.0-beta12! It is decently fast now! And my list is having dynamic height and width, yet the library still able to animate well! I would like to thank @computerjazz for this cool library!!

**Comment by gtwilliams03** [comment]
I have getting the same `excessive number of callbacks` error and my app hangs about 2-3 seconds after the screen loads. Running `react-native-draggable-flatlist@4.0.0-beta12`.

Offending code is here (`ListItem` is from `react-native-elements` and I tested with just a basic <Text /> element and I still get the error):

```
            <View style={{ flex: 1 }}>
            {_pickItems.length ?
            <DraggableFlatList horizontal={false} 
                data={_pickItems} 
                keyExtractor={(item, index) => `${item.seasonId}-${item.week}-${item.teamId}-${item.game}`}
                renderItem={({ item, index, isActive, drag }) => (
                <TouchableOpacity onLongPress={drag} disabled={isActive}>
                    <ListItem topDivider={index === 0} bottomDivider
                        containerStyle={[s.container, isActive ? { backgroundColor: Colors.primaryBackgroundColor } : null]}>
                        <Text>{item.rank}</Text>
                    </ListItem>
                </TouchableOpacity>
                )}
                onDragEnd={({ data, from, to }) => onPickDragEnd(from, to)}
            />
            : null}
            </View>

```

**Comment by gtwilliams03** [comment]
Never mind.  I had a `setInterval` timer that was running on the page that was cycling too quickly for the items to load.  I slowed it down, and all seems well.
