### ISSUE TITLE
How to $ Sponsor `react-native-draggable-flatlist`?

### ISSUE THREAD

**Issue by bradleyflood** [computerjazz/react-native-draggable-flatlist#410]
I like to financially support react native projects. But I can't see a way I can sponsor this one.

@computerjazz can you set up a Github Sponsorship account for this project or yourself so I and others can sponsor it?

Thank you!
Brad

**Comment by computerjazz** [comment]
Amazing, thank you so much!
Setting up a Sponsorship account now 🤑

**Comment by computerjazz** [comment]
alright, Sponsorship should be good to go, thanks again!

**Comment by bradleyflood** [comment]
Sorted. Thanks.
