### ISSUE TITLE
Use inside `Animated.ScrollView`

### ISSUE THREAD

**Issue by osvald0** [computerjazz/react-native-draggable-flatlist#412]
I'm using the NestableScrollContainer and NestableDraggableFlatList inside a Animated.ScrollView. I have a cards list and the problem is when I press a card to re order it remain in the position and the scroll action is executed. Is it posible to move the card instead of scroll?

react: 17.0.1 => 17.0.1
react-native: 0.64.2 => 0.64.2

**Comment by computerjazz** [comment]
sounds like you're doing some double-nesting of scrollables. Can you use the `NestableScrollContainer` as your outer scrollview? (that's all it is under the hood, with some extra bookkeeping added: https://github.com/computerjazz/react-native-draggable-flatlist/blob/main/src/components/NestableScrollContainer.tsx#L41)
