### ISSUE TITLE
critical bug 

### ISSUE THREAD

**Issue by ARDcode** [computerjazz/react-native-draggable-flatlist#42]
OS: Android 8.0
RN: 57.7
react-native-draggable-flatlist - latest
On drag, when the animation has not finished yet, but we have moved the element to the place where the animation ends. 
Result: the item disappears.
Expected: normal behavior.
![ezgif-3-761e3193f71f](https://user-images.githubusercontent.com/9216419/49797180-bf634d80-fd4f-11e8-8eca-7442f720579d.gif)

It happens when **spacerIndex** and **activeRow** is equal.

**Comment by appaaaa** [comment]
me too
anyone solve this?

**Comment by eminsr** [comment]
I think if you add the code below, inside the `onPanResponderRelease` after `const { activeRow, spacerIndex } = this.state;` it will prevent this from happening. Could you confirm it?
```
if (activeRow == spacerIndex) {
          this.onReleaseAnimationEnd();
          return;
}
```

**Comment by appaaaa** [comment]
@eminsr No, It doesn't work.....

**Comment by eminsr** [comment]
Well, if you release the active row before sliding animation ends, this little fix won’t work. That’s a whole another thing.

**Comment by MohamadKh75** [comment]
I have this problem too! :frowning_face:

**Comment by AlexLaRochelle** [comment]
Same thing here

**Comment by lidonghua** [comment]
Same thing here

**Comment by ARDcode** [comment]
@computerjazz we need your help :(

**Comment by galias11** [comment]
Looking at a previous comment, i found that the issue can be fixed by getting line 398 like this:
`horizontal ? { width: isActiveRow ? 1 : undefined } : { height: isActiveRow ? 1 : undefined },`
I added a forceUpdate after my components onMoveEnd callback. 
Can you check this solution?

**Comment by ARDcode** [comment]
@galias11 WOW, ITS WORK! Thx!!!
