### ISSUE TITLE
refreshControl prop is not working on Android. (still working fine on iOS)

### ISSUE THREAD

**Issue by tdnhathuy** [computerjazz/react-native-draggable-flatlist#432]
**Describe the bug**
refreshControl prop is not working on Android. (still working fine on iOS)

**Comment by taatiq882** [comment]
I am having the same issue. Have you found any solution ?

**Comment by hakansaglam29** [comment]
```
      <DraggableFlatList
        data={draggableData}
        renderItem={renderItem}
        onDragBegin={() => setIsDragging(true)}
        onDragEnd={({ data }) => {
          setIsDragging(false)
          setOnDragEnd(data)
        }}
        keyExtractor={(item: Item) => item.id}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.contentContainerStyle}
        refreshControl={<RefreshControl enabled={!isDragging} onRefresh={onRefresh} refreshing={false} />}
      />
```
1. RefreshControl should be imported from  'react-native-gesture-handler',
2. enabled prop should be used, otherwise scroll  while drugging is not working properly.

it is working properly both in IOS and Android

**Comment by taatiq882** [comment]
Hi, I am a bit confused coz I couldn't find the RefreshControl component from 'react-native-gesture-handler'. Can you help me in this regard?

**Comment by hakansaglam29** [comment]
"react-native-gesture-handler": "^2.8.0",
    "react-native-draggable-flatlist": "^4.0.0",
    
    you can find it like this
    `import { RefreshControl } from 'react-native-gesture-handler'`

**Comment by taatiq882** [comment]
Thanks for the quick reply. Actually I was using the old version of react-native-gesture-handler. After the updating I could easily import and RefreshControl is also working on android.

**Comment by tdnhathuy** [comment]
> ```
> "react-native-gesture-handler": "^2.8.0",
> "react-native-draggable-flatlist": "^4.0.0",
> 
> you can find it like this
> `import { RefreshControl } from 'react-native-gesture-handler'`
> ```

Thanks. It worked for me

**Comment by jonghyeokFF** [comment]
The solution above isn't working in react-native 0.77.
Any updates in 2025?

**Comment by lxh1579419223** [comment]
Not applicable in React Native 0.77.1 version, is there a latest solution?
