### ISSUE TITLE
react-native  dropdown with flat list

### ISSUE THREAD

**Issue by SruthiSNair** [computerjazz/react-native-draggable-flatlist#45]
I am a begginner  in react-native as well as coding too. 
I need to show a flat list having multiple details under  a down list . Can anyone help please..

Here i am attaching the sketch which i meant  to be....

![gitt](https://user-images.githubusercontent.com/35486395/50446987-1f581780-093e-11e9-8853-491b66602f88.jpg)

**Comment by computerjazz** [comment]
Not appropriate issue. Good luck though!
