### ISSUE TITLE
Could not resolve dependency: react-native-reanimated@">=2.8.0" from react-native-draggable-flatlist@4.0.0

### ISSUE THREAD

**Issue by MedyxDev** [computerjazz/react-native-draggable-flatlist#454]
**Describe the bug**
react-native requires react-native-reanimated 3.0.0-rc.10, however react-native-draggable-flatlist requires react-native-reanimated 2.8.0. When I try to use reanimated 2.8.0 in my project, it fails to build.

I get the peer error message when trying to install react-native-draggable-flatlist.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: MyApp@0.0.1
npm ERR! Found: react-native-reanimated@3.0.0-rc.10
npm ERR! node_modules/react-native-reanimated
npm ERR!   react-native-reanimated@"^3.0.0-rc.10" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-reanimated@">=2.8.0" from react-native-draggable-flatlist@4.0.0
npm ERR! node_modules/react-native-draggable-flatlist
npm ERR!   react-native-draggable-flatlist@"*" from the root project

**To Reproduce**
Using the following React Native version;
- react-native: 0.70.6 => 0.70.6 

How to resolve this? Or is an update required to react-native-draggable-flatlist to handle newer versions of reanimated?

**Comment by computerjazz** [comment]
huh, i wonder if npm doesn't recognize non-numeric semver (the `-rc.10` part). Otherwise I would expect reanimated v3.x to fulfill `react-native-reanimated@">=2.8.0`

**Comment by MedyxDev** [comment]
Fixed it with using the latest beta build of react-native-draggable-flatlist. You still get the error installing through NPM, using --force will work...
