### ISSUE TITLE
Offset not recalculated if container layout changes

### ISSUE THREAD

**Issue by maxschmeling** [computerjazz/react-native-draggable-flatlist#46]
**STEPS**
1. Create a list that takes up half the screen.
2. Add a button that changes the styling of the list to take up the full screen (or some other size)

**EXPECTED**
Drag & drop still works correctly

**ACTUAL**
The drag & drop works but the item being dragged isn't shown in the right location.

**Comment by maxschmeling** [comment]
I can fix this locally by initializing `_contentOffset` to `0` as in #43 and then also calling `measureContainer` in the wrapper `View` `onLayout` callback. This requires storing the ref for future use in `measureContainer`.

**Comment by computerjazz** [comment]
fixed in v2
