### ISSUE TITLE
Animations are choppy in Android

### ISSUE THREAD

**Issue by Skaty** [computerjazz/react-native-draggable-flatlist#52]
When running the demo/example on a fresh Expo project (CRNA), the animation for dragging and dropping are choppy (i.e. when I pick up an item, it “jumps” up and when I put it to a position, it jumps from the released position to its intended position).

Note that this doesn’t affect the iOS version of the app.

I’ll get back with a demo once I am able to record it.

**Comment by pratikbhumkar** [comment]
This happens because there are several conditions to check and updations. If you keep the colors to constant value, it becomes a bit better

**Comment by Skaty** [comment]
@pratikbhumkar Yes, I tried with a single component (like a text component) and it's still quite laggy.

**Comment by karensg** [comment]
Same for me, pretty laggy on Android

**Comment by anniewey** [comment]
Same here. It was pretty smooth on iOS but not on Android

**Comment by Shedav** [comment]
The same lags on Android. Do you have any updates?

**Comment by computerjazz** [comment]
which version are you currently running? v2 shipped with major perf improvements
