### ISSUE TITLE
Error: Exception in HostFunction: expected 0 arguments, got 1, js engine: hermes

### ISSUE THREAD

**Issue by OoDeLally** [computerjazz/react-native-draggable-flatlist#529]
This post intends to guide a future developer (be it me or someone else).

If getting the following obscure error
```
Error: Exception in HostFunction: expected 0 arguments, got 1, js engine: hermes
```

Possible explaination (in my case) is that it is missing `react-native-reanimated`: https://docs.expo.dev/versions/latest/sdk/reanimated/

```
npx expo install react-native-reanimated
```

**Comment by thayllor** [comment]
I had the same error and this solve the problem, thank you very much.
