### ISSUE TITLE
Tried to modify key `current` of an object which has been already passed to a worklet

### ISSUE THREAD

**Issue by rodrigo2392** [computerjazz/react-native-draggable-flatlist#539]
**Describe the bug**
I can see a warning realated to modify a prop from a ref i think, not shure were is it happening

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - react-native-draggable-flatlist version: 4
 - Platform: Android
 - React Native or Expo version: 0.74.2
 - Reanimated version: 3.12.1
 - React Native Gesture Handler version:

**Additional context**
![Screenshot_1718991693](https://github.com/computerjazz/react-native-draggable-flatlist/assets/91278835/abe730be-c569-45ff-972f-edca9a361d9e)

https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#tried-to-modify-key-of-an-object-which-has-been-converted-to-a-shareable

**Comment by Sistemas7penna** [comment]
+2
 I have the same issue
 "react-native-draggable-flatlist": "4.0.1"
"react-native-reanimated": "3.12.1"

**Comment by s-mikulich** [comment]
+ the same issue

**Comment by rogerdribeiro** [comment]
+1

    "react-native-draggable-flatlist": "^4.0.1",
    "react-native-reanimated": "^3.12.1",

**Comment by zhanglei1996** [comment]
+1
the same issue
"react-native-draggable-flatlist": "^4.0.1",
"react-native-reanimated": "^3.6.1",

**Comment by inho1019** [comment]
+ 1
same issue
  "react-native-draggable-flatlist": "^4.0.1",
  "react-native-reanimated": "^3.12.1",

**Comment by rssj** [comment]
+1
same issue
"react-native-draggable-flatlist": "^4.0.1",
"react-native-reanimated": "^3.6.1",

**Comment by trxkhiem** [comment]
+1
same issue
"react-native-draggable-flatlist": "^4.0.1",
"react-native-reanimated": "^3.6.1",

**Comment by adorum** [comment]
+1
same issue
"react-native-draggable-flatlist": "^4.0.1",
"react-native-reanimated": "^3.13.0",

**Comment by PeterHasitschka** [comment]
+1
same issue
"react-native-draggable-flatlist": "^4.0.1",
"react-native-reanimated": "^3.13.0",

**Comment by ElicaInc** [comment]
+1
same issue
"react-native-draggable-flatlist": "^4.0.1",
"react-native-reanimated": "^3.13.0",

**Comment by ddrozdov** [comment]
Fixed with this patch.
[react-native-draggable-flatlist+4.0.1.patch.txt](https://github.com/user-attachments/files/16273404/react-native-draggable-flatlist%2B4.0.1.patch.txt)

**Comment by rodrigo2392** [comment]
> Fixed with this patch. [react-native-draggable-flatlist+4.0.1.patch.txt](https://github.com/user-attachments/files/16273404/react-native-draggable-flatlist%2B4.0.1.patch.txt)

I can confirm its fixed with this patch

**Comment by luca-tomasetti** [comment]
The warning disappear

> Fixed with this patch. [react-native-draggable-flatlist+4.0.1.patch.txt](https://github.com/user-attachments/files/16273404/react-native-draggable-flatlist%2B4.0.1.patch.txt)

The warning disappeared when the component is initialised, but when I am dragging an element of the list, the warning reappears.

I fixed it by changing this file (react-native-draggable-flatlist/src/hooks/useOnCellActiveAnimation.ts) on top of @ddrozdov's patch with this: 
[react-native-draggable-flatlist+4.0.1.patch](https://github.com/user-attachments/files/16280498/react-native-draggable-flatlist%2B4.0.1.patch)

**Comment by tom-sherman** [comment]
Can we leave this open until the fix lands?

**Comment by ngdbao** [comment]
> Can we leave this open until the fix lands?

yeah, It doesn't make sense to close an unsolved issue

**Comment by rodrigo2392** [comment]
> > Can we leave this open until the fix lands?
> 
> 
> 
> yeah, It doesn't make sense to close an unsolved issue

Well last update was a year ago so...

**Comment by callaars** [comment]
@computerjazz are you still updating this lib or are you looking for maintainers to hand it over to?

**Comment by angusryer** [comment]
> @computerjazz are you still updating this lib or are you looking for maintainers to hand it over to?

This is a good question!
https://github.com/computerjazz/react-native-draggable-flatlist/issues/542#issue-2398865097

**Comment by byungchanKo99** [comment]
> Fixed with this patch. [react-native-draggable-flatlist+4.0.1.patch.txt](https://github.com/user-attachments/files/16273404/react-native-draggable-flatlist%2B4.0.1.patch.txt)

this work to me thx!

**Comment by pleerock** [comment]
Looks like issue reproduced with the newer versions of react-native. Obviously, we cannot use patch, can maintainers publish a new package version with patch applied?

**Comment by CyborgCodes** [comment]
Im have this issue too and had followed the installation guide, any solutions found? 

"react-native-draggable-flatlist": "^4.0.1",
"react-native-reanimated": "^3.14.0",
"react-native-gesture-handler": "^2.17.1",

**Comment by ukcasso** [comment]
[react-native-draggable-flatlist+4.0.1.patch.txt](https://github.com/user-attachments/files/16677871/react-native-draggable-flatlist%2B4.0.1.patch.txt)

my env
```
"react-native-draggable-flatlist": "^4.0.1",
"react-native-reanimated": "^3.14.0",
"react-native-gesture-handler": "^2.14.1",
```
hope this helps.

@pleerock @CyborgCodes

**Comment by emmawestbrook** [comment]
I'm also having this issue!

**Comment by jzaefferer** [comment]
> Obviously, we cannot use patch

With https://www.npmjs.com/package/patch-package you could, until https://github.com/computerjazz/react-native-draggable-flatlist/pull/551 gets merged and released.

**Comment by bezenson** [comment]
@bwjohns4 Could you open source it please? Your profile is fully closed 😕

**Comment by ddrozdov** [comment]
I updated the patch so that it doesn't introduce a warning about `value` being updated during render on RN 0.76.

[react-native-draggable-flatlist+4.0.1.patch.txt](https://github.com/user-attachments/files/17959021/react-native-draggable-flatlist%2B4.0.1.patch.txt)

**Comment by sanjivpaul** [comment]
on update react-native-reanimated version 3.18.0 its fix for me. after update react-native-reanimated version delete node_modules and package-lock.json file and re-install it.
