### ISSUE TITLE
How can i change the id inside array after moveEnd?

### ISSUE THREAD

**Issue by galuh1300d** [computerjazz/react-native-draggable-flatlist#56]

**Comment by computerjazz** [comment]
I don't follow. Can you explain in more detail?

**Comment by galuh1300d** [comment]
<img width="564" alt="screen shot 2019-03-08 at 10 56 36" src="https://user-images.githubusercontent.com/43464041/54006678-ef748e00-4190-11e9-90db-ebbc5086bb0b.png">

<img width="373" alt="screen shot 2019-03-08 at 10 59 48" src="https://user-images.githubusercontent.com/43464041/54006789-585c0600-4191-11e9-956e-975596eb17b9.png">


In the detail_id: 3885
i drag it under detail_id: 3887 

i want timefrime in 3885 change from 1 to 2

how can i do it? after i drag my component under 3887 component

**Comment by computerjazz** [comment]
It's up to you to manipulate your data on move end -- the callback will give you the `from` id, the `to` id, and the updated `data` array: https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/index.js#L165-L169
