### ISSUE TITLE
Multiple level of draggable flatlist

### ISSUE THREAD

**Issue by alanyong91** [computerjazz/react-native-draggable-flatlist#57]
Is it possible that i can have draggable flatlist inside another draggable flatlist ?
I tested but in second level of item keep hanging  on the same position when dragging.

Anyone can help me on this ? Really appreciate if you could help me.

itemChild = (item) => {
    return(
        <DraggableFlatList
            data={item.item}
            renderItem={this.renderItem}
            keyExtractor={(items, indexs) => `draggable-item-${items.key}`}
            scrollPercent={5}
            onMoveEnd={({ datas }) => this.setState({ testing: datas })}
        />
    )
}

renderItem = ({ item, index, move, moveEnd, isActive }) => {
    return (
        <View style={{ 
            marginBottom: 5,
            paddingHorizontal: 15, paddingVertical: 10,
            backgroundColor: isActive ? '#fcfcfc' : '#fff', 
            elevation: isActive ? 3 : 0,  
        }}
        >
        <View style={{ flexDirection: 'row', alignItems: "center" }}>
            <TouchableOpacity
                style={{ height: 40, justifyContent: 'center'}}
                onLongPress={move}
                onPressOut={moveEnd}
            >
                <Text>{ item.label }</Text>
            </TouchableOpacity>
        </View>
        <View style={{ flex: 1 }}>
            { this.itemChild(item) }
        </View>
        </View>
    )
}

render() {
    return(
        <View style={{ flex: 1 }}>
            <DraggableFlatList
                data={this.state.layout}
                renderItem={this.renderItem}
                keyExtractor={(item, index) => `draggable-item-${item.key}`}
                scrollPercent={5}
                onMoveEnd={({ data }) => this.setState({ layout: data })}
            />
        </View>
    )
}

**Comment by computerjazz** [comment]
this is not a supported feature. Nested scrollables get weird.
