### ISSUE TITLE
Bug in drag and drop

### ISSUE THREAD

**Issue by gazedash** [computerjazz/react-native-draggable-flatlist#58]
See the video http://cl.ly/a62d4f793685/Kapture%202019-03-21%20at%2015.28.13.mp4

It is pretty hard to reproduce, but it happens sometimes. Don't know what is causing it though

If not for this bug, this library would be amazing!

Platform: iOS

**Comment by gazedash** [comment]
I think it might be related to https://github.com/facebook/react-native/issues/16895
So how do we fix it? Maybe there is a way to disable easeInEaseOut?

**Comment by agnieszkabugla** [comment]
I had the same problem because the most parent component of <DraggableFlatList> was <Scrollview>. I changed it to <View> and now it doesn't behave like that.

**Comment by gazedash** [comment]
But I don’t have a scroll view. I have just this component

**Comment by CapitanRedBeard** [comment]
@gazedash Did you ever find a complete fix for this? Seeing the exact same thing with the draggable list NOT in a scrollview. 

I tried [commenting out this line](https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/index.js#L194) to avoid any easing problems which seems to help a little but elements still go invisible when moving them around (I think them going invisible just means onMove they fly off the screen. Also onMoveEnd seems to never drop them in the correct spot initially, they're always off a 10ish pixels then jump to the right spot

**Comment by computerjazz** [comment]
please try v2 and reopen if still an issue
