### ISSUE TITLE
StatusBar hidden issue

### ISSUE THREAD

**Issue by tvelev92** [computerjazz/react-native-draggable-flatlist#6]
The animated component offset jumps up by the height of the statusbar if statusbar is rendered `<StatusBar hidden = {true}`, had to add translucent true as so: `<StatusBar hidden = {true} translucent = {true} />` to force that statusbar offset to be subtracted.

**Comment by computerjazz** [comment]
fixed in 1.1.2 https://github.com/computerjazz/react-native-draggable-flatlist/commit/c8226f0c064c4c2fabe733811647bacbb39e87e2

**Comment by tvelev92** [comment]
@computerjazz thanks!
