### ISSUE TITLE
Problem with the scrolling behaviour while selecting the first or last element

### ISSUE THREAD

**Issue by uprevTech** [computerjazz/react-native-draggable-flatlist#61]
First of all, great tool! Thank you for your time developing this. 

While using the default example, I encountered a small bug regarding the scrolling behaviour. When selecting the first element, scroll down a bit. You will realize the scrolling-up will not work (while still holding the same element). If you pick the second element it will work just fine. The same behaviour is seen when dragging the last element up and trying to scroll back down while still holding it.

I am using the following versions:
    "react": "16.8.3"
    "react-native": "0.58.6"
    "react-native-draggable-flatlist": "^1.1.7"

**Comment by computerjazz** [comment]
fixed in v2
