### ISSUE TITLE
FlatList animation performance

### ISSUE THREAD

**Issue by markbrown4** [computerjazz/react-native-draggable-flatlist#62]
Hey @computerjazz!

This isn't an issue with your library but we've found a performance issue with Animated FlatList's.  If you instead use a SectionList with one section you'll see smooth animations with animated values.

```
<FlatList data={[1,2,3]} />
// =>
<SectionList sections={[{ data: [1,2,3]}]} />
```

Sounds stupid, but it's the only way we've found to fix it until the root issues with FlatList are resolved.  https://github.com/facebook/react-native/issues/24364

I don't believe there's any downsides to using this approach.

**Comment by computerjazz** [comment]
Interesting, thanks for the heads up -- I'll check it out!

**Comment by vvusts** [comment]
@markbrown4 can you please provide some example how to apply this fix. We also suffer android performance issue.
What need to be changed?

**Comment by joshua-turner** [comment]
If you do implement this you'll need to also update how you access scrollTo* methods.

From `this._flatList.scrollToEnd()` to `this._flatList._wrapperListRef._listRef.scrollToEnd()`.

**Comment by markbrown4** [comment]
There was an update on the issue I raised:
https://github.com/facebook/react-native/issues/24364#issuecomment-482431369

The react team suggests `scrollEventThrottle={1}` on the FlatList when it's tied to native animations, may be worth a test to see if that improves things.
