### ISSUE TITLE
Component not rendering at all

### ISSUE THREAD

**Issue by cjinghong** [computerjazz/react-native-draggable-flatlist#65]
The following code is not rendering anything at all

`<DraggableFlatList
            data={['a', 'b', 'c']}
            renderItem={({ item }) => (
              <Text>{item}</Text>
            )}
            keyExtractor={item => item}
            scrollPercent={5}
          />`

**Comment by cjinghong** [comment]
@computerjazz

**Comment by themcmaneh** [comment]
I have the same issue over here, It renders a blank screen

**Comment by cjinghong** [comment]
Hey I figured it out, after giving the `DraggableFlatList` a fixed height everything is rendering fine.

**Comment by nirmaldalmia** [comment]
I am facing the same issue. Everything renders fine when I use FlatList but the moment I replace FlatList with DraggableFlatList, it shows a blank screen. Even tried setting the height as mentioned by @cjinghong but no use.

**Comment by ShavaShav** [comment]
I think if `DraggableFlatList` is wrapped in a `View`, that `View` needs specific dimensions (`height`/`width`) or `flex:1` in it's style. At least that's what worked for me when nothing rendered.
