### ISSUE TITLE
Android hiding items after dragging a few times

### ISSUE THREAD

**Issue by icew1nd** [computerjazz/react-native-draggable-flatlist#66]
Hey @computerjazz 

First of all, crisp component - its super awesome to work with! Well on iOS at least :( After implementing this, i noticed that some of my items started to dissapear after dragging them a few times. Then i figured out they would just lay below other list items. 

Afterwards I replicated this in the example code 

*Steps to replicate*
Drag several times, possibly if you drag an item several spots towards the top.

*Screenshot*
![thumbnail_Screenshot_20190429-234859](https://user-images.githubusercontent.com/9656945/56929671-8cd9a780-6ada-11e9-84c7-4d51fb6bc5ee.jpg)

Tested on a Huaweii P20 Lite

*Setup*
"react-native": "0.59.2",
"react": "16.8.3",
"react-native-draggable-flatlist": "^1.1.7",

**Comment by leenakhaled** [comment]
What the solution ? @icew1nd

**Comment by npmun** [comment]
I have noticed same issue on Windows app as well. #48 (yet to merge) resolved the issue.

**Comment by icew1nd** [comment]
@leenakhaled never Solved it im afraid - had a bit of a weird usecase so ended up rendering a regular flatlist until going into edit mode where i made my own (not as this fast rendering draggable list) but it signifantly improved rendering times in the end anyway

**Comment by computerjazz** [comment]
@npmun #48  is not ideal as it shifts everything by 1px.
I've rewritten this pkg to be more robust, please check out #81 and see if it fixes your issue. I'm just waiting on the corresponding reanimated release before I publish.

**Comment by npmun** [comment]
@icew1nd We are probably looking at two different issues with similar symptoms. It was very easy for me to recreate before adding 1px offset and fix definitely resolved the issue. Please note that I was only testing example code in this repository (not in the actual app)
@computerjazz I will test V2 this evening and let you know how it goes.

**Comment by computerjazz** [comment]
please reopen if still an issue on 2.x
