### ISSUE TITLE
Item position offset on move begin and end

### ISSUE THREAD

**Issue by nitramleahpar** [computerjazz/react-native-draggable-flatlist#69]
Hi everyone,

Not a huge deal, but there seems to be an unwanted position offset when selecting/releasing an item. As seen on the GIF attached, the item moves upwards when the long press is detected, as well as when it is released (before moving to its final position). Any thoughts ?

This is the code from the example, running on an android phone through Expo.

![draggable_flatlist_offset](https://user-images.githubusercontent.com/50497598/57545623-d5068e80-7352-11e9-9f10-fae0af34f2c7.gif)

**Comment by stylehuan** [comment]
+1

**Comment by daybreaker** [comment]
In my current app, if I've scrolled any, whenever the longPress activates, it sends the active item to the top of the screen, instead of remaining in place.

Dont know if this is the same issue, or a different one. Havent debugged it too much yet. :-/

**Comment by paulxuca** [comment]
If you're using `react-navigation` (especially with the IOS 13 Modal Presentation animation or the card animation), the calculated container offset will be incorrect as it's measured during the screen transition. I've fixed it by adding an `InteractionManager.runAfterInteractions(...)` around the code which measures the container offset.

**Comment by simonecorsato** [comment]
> If you're using `react-navigation` (especially with the IOS 13 Modal Presentation animation or the card animation), the calculated container offset will be incorrect as it's measured during the screen transition. I've fixed it by adding an `InteractionManager.runAfterInteractions(...)` around the code which measures the container offset.

Could you please write exactly where you added `InteractionManager.runAfterInteractions(...)`? I am using react-native-navigator and I have a similar offset problem when I start dragging.

**Comment by paulxuca** [comment]
This seems to be fixed in v2 for me

**Comment by simonecorsato** [comment]
I'm using react-native-navigation 2.27.7 and react-native-draggable-flatlist 2.0.1

**Comment by computerjazz** [comment]
@simonecorsato does that mean it is fixed for you or no?

**Comment by simonecorsato** [comment]
yes, it is fixed. Now i'm using version 2.0.14 of react-native-draggable-flatlist
