### ISSUE TITLE
Implementation Question

### ISSUE THREAD

**Issue by JackAgarwal** [computerjazz/react-native-draggable-flatlist#7]
First of all thank you for your work on this great component,

This isn't really an issue but more of a question, however I wasn't sure where else to ask.

I am implementing a draggable flatlist and trying to display a travel time between (and overlapping) two rows. I cannot for the life of me figure out how to force the child view of the first row not to be clipped by the next row in the flatlist. The view is positioned correctly and when the row is being dragged everything displays correctly. 

I have tried using overflow='visible', removeClippedSubviews={false}, and position: 'absolute' but haven't been able to find a solution. 

If there is another approach that I am missing to accomplishing this please let me know.

Thanks

**Comment by computerjazz** [comment]
So you're trying to create a list without a spacer? That's not going to be possible. It's an interesting idea though ,maybe I'll explore that in the future. Note that android will clip subviews regardless of overflow style. https://github.com/facebook/react-native/issues/6802

**Comment by JackAgarwal** [comment]
Looking at the source code, it seems like the spacer is indeed what prevents what I'm attempting. I managed a workaround using a separate render loop for the travel times and a Z-index change for the two components onMoveBegin, however its not ideal and will probably just resort to a UI change for the sake of maintainability.

Thanks for the point in the right direction
