### ISSUE TITLE
Is there any prop to enable or disable draggable feature?

### ISSUE THREAD

**Issue by ManalLiaquat** [computerjazz/react-native-draggable-flatlist#72]
I have only one component and I am rendering it on two separate screens, on one screen I have to enable the drag feature but on the other screen I have to disable the drag feature. What can I do? Let me know, if any prop is available! 

```
<DraggableFlatList enable={ true || false }  />
```

Thanks in advance! 😊〽

**Comment by computerjazz** [comment]
can you just never call `move()` in the component you don't want to be draggable?

**Comment by computerjazz** [comment]
update for v2: does it work to not call `drag()` when you don't want the component to be draggable?

**Comment by ElicaInc** [comment]
> update for v2: does it work to not call `drag()` when you don't want the component to be draggable?

Works for me. 
Thank you for providing this great library!!!
