### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by kevgrig** [computerjazz/react-native-draggable-flatlist#74]
This project does not have a license and [GitHub states](https://help.github.com/en/articles/licensing-a-repository), "[...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license."

Can you please consider [adding an open source license](https://choosealicense.com/) such as [MIT](https://choosealicense.com/licenses/mit/)? Otherwise, I am not a lawyer, but I believe that no one may actually use this code in a production project (which would be reproducing and distributing it) without your explicit permission.

**Comment by kevgrig** [comment]
The [npmjs page for this project](https://www.npmjs.com/package/react-native-draggable-flatlist) lists its license as [ISC](https://choosealicense.com/licenses/isc/) so I think users are safe to use the binary package from npmjs, although be careful forking the source.

**Comment by computerjazz** [comment]
done!
