### ISSUE TITLE
How drag between multiple rows?

### ISSUE THREAD

**Issue by haolipang** [computerjazz/react-native-draggable-flatlist#78]
Is is possible to make the items draggable vertically and horizontally at the same time? I set horizontal to ‘true’ and turned it into 2 rows. However, I could only drag the items within the same row. Is is possible to drag swap Item 1 with Item 4?
![Screenshot_1563337248](https://user-images.githubusercontent.com/51696790/61346906-574c8b00-a88d-11e9-8fbc-d876aac04b01.png)

**Comment by chauhan19911** [comment]
any solution you found?

**Comment by computerjazz** [comment]
not supported

**Comment by rodgomesc** [comment]
some one can implement this?

**Comment by lakshyastech** [comment]
@haolipang Did you find any solution?
