### ISSUE TITLE
How can I create two sections and inter transfer of the tabs

### ISSUE THREAD

**Issue by vedant17** [computerjazz/react-native-draggable-flatlist#79]
I plan to create two sections in the flatlist and I want to transfer cells in between then. How can I do this? Thanks in advance

**Comment by computerjazz** [comment]
Do you mean multicolumn lists? If so, that's not possible with this.

**Comment by vedant17** [comment]
I meant a section list where there are two sections and I am using drag and drop in between them? If it isn't possible can you please suggest some different library?

**Comment by curiousdustin** [comment]
@vedant17 you were probably wanting to create a draggable version of the basic [SectionList](https://facebook.github.io/react-native/docs/sectionlist), correct?

This would be a great feature. @computerjazz , can you confirm `react-native-draggable-flatlist` does not currently provide this sort of functionality?

**Comment by ReemaVinodGangdev** [comment]
Any update on this? I need similar kind of functionality. Can someone help please?

**Comment by lyseiha** [comment]
Any update on it? SectionList support?

**Comment by joeyscarim** [comment]
would also like an update on this, in search of a draggable section list

**Comment by mykelaballe** [comment]
same here, badly need a feature like this

**Comment by Danue1** [comment]
Same here.
Can we have hope?

**Comment by computerjazz** [comment]
this would require a significant refactor. it's not in the cards for me to do right now and is likely outside the scope of this package.

**Comment by DavidTaylor96** [comment]
Is there any update on this? Does anyone have a good package to use for section lists?

**Comment by jsg2021** [comment]
> this would require a significant refactor. it's not in the cards for me to do right now and is likely outside the scope of this package.

This person seems to have done it for pre-reanimated v2: https://github.com/computerjazz/react-native-draggable-flatlist/compare/main...upacyxou:react-native-draggable-flatlist:master
