### ISSUE TITLE
Is there any way to use scrollEnabled?

### ISSUE THREAD

**Issue by jngcii** [computerjazz/react-native-draggable-flatlist#82]
i know that its props are underlying FlatList and Flatlist is using ScrollView's props.

but I can't use scrollEnabled.

i wanna make this component disabled when single renderItem swiping horizontally.

is there any way please..?😄

**Comment by imammuhtadi** [comment]
can you just never call move() in the component you don't want to be draggable?

**Comment by jngcii** [comment]
hmm.. thanks for answering. 
i wanna use this component and react-native-swiper-swipeable together.
but when i swipe component horizontally, there are no way to fix this flatlist.
this issue is not related with move() function.

**Comment by computerjazz** [comment]
forwarded `scrollEnabled` prop to flatlist in v2: https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/index.tsx#L806
