### ISSUE TITLE
list disappear after drag n drop with some error

### ISSUE THREAD

**Issue by ZeroCool00** [computerjazz/react-native-draggable-flatlist#9]
```
"react-native": "0.55.4",
"react-native-draggable-flatlist": "^1.1.2",
```

![listerror](https://user-images.githubusercontent.com/18139594/43034561-46dbe1d8-8cfc-11e8-9b51-59880ac68379.png)

this is what i done:

```
<DraggableFlatList
          data={this.state.rowData}
          renderItem={this.renderRowItem}
          scrollPercent={5}
          keyExtractor={(item, index) => `draggable-item-${index}`}
          onMoveEnd={({ rowData }) => this.setState({ rowData })}
    />

renderRowItem = ({ item, index, move, moveEnd, isActive }) => {
    return (
      <TouchableOpacity
        onLongPress={move}
        onPressOut={moveEnd}
        style={{
          height: 100,
          alignItems: 'center',
          justifyContent: 'center'
        }}
      >
      <Text>{item.name}</Text>
      {/*   <Row data={item} active={active} columnSchema={this.state.columnSchema} searchValue={this.state.searchValue} />; */}
      </TouchableOpacity>
    )
  }
```

i m getting list successfully. but after drag it just disappear.

**Comment by Sakthimalar** [comment]
I am having the same problem. Did you get any solution?

**Comment by ZeroCool00** [comment]
@Sakthimalar  no i simply give up on this lib.

**Comment by nihp** [comment]
@ZeroCool00 Can you able to show the list in Flatlist

**Comment by Sakthimalar** [comment]
We can show the flatlets for that we have to change the name of data.
For example, change From this 
` data={this.state.rowData}`
To this
`data={this.state.data}`

**Comment by nihp** [comment]
@Sakthimalar can you able to drag and drop the data in the screen

**Comment by nihp** [comment]
@Sakthimalar 
I need to drag and drop the column and place it in another location and form a layout. https://github.com/computerjazz/react-native-draggable-flatlist/issues/14

**Comment by ironworkshop** [comment]
I had a somewhat similar issue but my error was something about 'measure cannot find view with tag xxxx'. When i debugged it i noticed that after the moveEnd function was called my data object (this.state.myData) was undefined. However I also noticed that 'this.state' was undefined, it appears to be a strange context issue so this;

const self = this;

Then i used the self.state.myObject and the issue appears to be fixed. Hope this helps someone else.

**Comment by sunrise1002** [comment]
On `onMoveEnd` method the name parameter must be `'data'` like in the example:
```
onMoveEnd={({ data }) => this.setState({ data })}
```

**Comment by radekzz** [comment]
I'm using hooks and i had to set state out of object
`onMoveEnd={({data}) => setData(data)}`
