### ISSUE TITLE
Clickable icon on each item doesn't work

### ISSUE THREAD

**Issue by saikats5** [computerjazz/react-native-draggable-flatlist#99]
I'm using this library in my application and I'm struggling to using icon click with popover kindof thing in the code, the click doesn't work but on reorder it shows the popover where the icon was clicked
Please find below the screenshot

**Comment by saikats5** [comment]
![image](https://user-images.githubusercontent.com/8777561/69902739-e5e22480-13b6-11ea-8cdd-709a220629b0.png)

**Comment by Soul244** [comment]
i am struggling with the same problem. onPress function does not work for list items. When i change draggable list to flatlist, onPress function works i expected.

**Comment by LuigiMaestrelli** [comment]
Same here

**Comment by osignite** [comment]
Same experience on Android.  When using a Touchable element inside of renderItem(), any onPress action stops working.   The existence of onLongPress={drag} doesn't seem to matter, the other touches won't work regardless.
The Touchable elements still give visual feedback of being pressed, but stop executing any action.

**Comment by asurare** [comment]
Same here.. Trying to find a workaround, will update if I find anything.

**Comment by Soul244** [comment]
> Same here.. Trying to find a workaround, will update if I find anything.
> 
> EDIT : Using `onPressOut` instead of `onPress` seems to be working for me. That's only a workaround though.

Thanks. It worked.

**Comment by AnOptimistSeePessimist** [comment]
using react-native-gesture-handler -> Touchables  instead of react-native -> Touchables

**Comment by curiousdustin** [comment]
> using react-native-gesture-handler -> Touchables instead of react-native -> Touchables

Doing this, I run into a different issue involving nesting. If you want the entire item to be touchable, along with certain buttons within that item, you run into this bug in react-native-gesture-handler: https://github.com/software-mansion/react-native-gesture-handler/issues/784

**Comment by panda0603** [comment]
@computerjazz still a problem only on android

**Comment by curiousdustin** [comment]
Does anyone understand why the presses on normal `react-native` Touchables are being cancelled by `react-native-gesture-handler` on Android? I think that could help narrow down a solution or at least work around.

I have noticed that a quick tap does not fire the `onPress` callback, BUT, a somewhat longer tap DOES! However, this does not appear to be related to `onLongPress`.

**Comment by computerjazz** [comment]
thanks, closing in favor of https://github.com/computerjazz/react-native-draggable-flatlist/issues/120 as they are duplicates and there's more context on that issue

**Comment by bakialmaci** [comment]
> Same here.. Trying to find a workaround, will update if I find anything.
> 
> EDIT : Using `onPressOut` instead of `onPress` seems to be working for me. That's only a workaround though.

OnPressOut is triggering when you try to drag an item.
Ex. If you attach an navigate into the "OnPressOut" you can't be drag item because navigate is triggering.
